<?php

declare(strict_types=1);
namespace App\Controllers\Admin\System;
use App\Core\{Csrf,Request,Response,Session};
use App\Repositories\{PlatformAdminTenantAuditRepository,TenantRepository};
use App\Services\Tenant\TenantAdminAuditService;
use Throwable;
final class SystemTenantInterventionController {
 public function __construct(private ?TenantRepository $tenants=null,private ?PlatformAdminTenantAuditRepository $repo=null,private ?TenantAdminAuditService $audit=null){$this->tenants??=new TenantRepository();$this->repo??=new PlatformAdminTenantAuditRepository();$this->audit??=new TenantAdminAuditService($this->repo);}
 public function show(Request $r,array $p=[]): Response {$id=(int)($p['id']??0);$tenant=$id>1?$this->tenants->findById($id):null;if(!$tenant)return (new Response())->setStatusCode(404);$sessions=[];try{$active=$this->repo->activeForTenant($id);if($active)$sessions[]=$active;}catch(Throwable){}return Response::view('layout.main',['title'=>'Intervention tenant','content'=>'admin.system.tenant_intervention','tenant'=>$tenant,'activeIntervention'=>$sessions[0]??null,'history'=>null,'backOfficePageCss'=>['platform-admin.css']]);}
 public function enter(Request $r,array $p=[]): Response {if(!Csrf::validate($r->input('_csrf_token')))return $this->back((int)($p['id']??0),'Session expirée.');$id=(int)($p['id']??0);$tenant=$id>1?$this->tenants->findById($id):null;if(!$tenant)return $this->back($id,'Organisation introuvable.');$admin=(int)Session::get('user_id');$reason=mb_substr(trim((string)$r->input('reason','Support')),0,500);$sid=$this->audit->beginSession($admin,$id,$reason,$r->ip(),(string)($_SERVER['HTTP_USER_AGENT']??''));Session::set('platform_admin_id',$admin);Session::set('admin_tenant_id',$id);Session::set('admin_tenant_started_at',gmdate('Y-m-d H:i:s'));Session::set('admin_tenant_session_id',$sid);Session::set('admin_tenant_reason',$reason);Session::set('platform_admin_tenant_context',true);Session::regenerate();return Response::redirect(url('dashboard'));}
 public function journal(Request $r,array $p=[]): Response {$id=(int)($p['id']??0);$sessionId=(int)Session::get('admin_tenant_session_id');$session=$this->repo->findSession($sessionId);if(!$session||(int)$session['tenant_id']!==$id)return $this->back($id,'Intervention invalide.');return Response::view('layout.main',['title'=>'Journal intervention','content'=>'admin.system.tenant_intervention','tenant'=>$this->tenants->findById($id),'activeIntervention'=>$session,'history'=>$this->audit->getSessionHistory($sessionId,($r->query('type')?:null)),'backOfficePageCss'=>['platform-admin.css']]);}
 public function rollback(Request $r,array $p=[]): Response {if(!Csrf::validate($r->input('_csrf_token')))return $this->back((int)($p['id']??0),'Session expirée.');try{$this->audit->rollbackAction((int)($p['actionId']??0));Session::flash('success','Modification restaurée et journalisée.');}catch(Throwable $e){Session::flash('error',$e->getMessage());}return Response::redirect(url('admin/system/tenants/'.(int)$p['id'].'/intervention/journal'));}
 public function leave(Request $r,array $p=[]): Response {if(!Csrf::validate($r->input('_csrf_token')))return Response::redirect(url('dashboard'));$sid=(int)Session::get('admin_tenant_session_id');$admin=(int)Session::get('platform_admin_id');$this->audit->recordAction('session_end','Sortie de l’organisation');$this->audit->endSession($sid,$admin);Session::forgetMany(['platform_admin_id','admin_tenant_id','admin_tenant_started_at','admin_tenant_session_id','admin_tenant_reason','platform_admin_tenant_context']);Session::regenerate();return Response::redirect(url('admin/tenants'));}
 private function back(int $id,string $message): Response {Session::flash('error',$message);return Response::redirect(url('admin/system/tenants/'.$id.'/intervention'));}
}
