<?php
declare(strict_types=1);
namespace App\Controllers\Web;
use App\Core\Csrf;use App\Core\Request;use App\Core\Response;use App\Core\Session;use App\Repositories\AtakDeviceAuthRepository;use App\Services\Atak\AtakDeviceAuthService;use App\Services\Auth\AuthService;use App\Services\Security\FileRateLimiter;
final class AtakDeviceSecurityController
{
 public function __construct(private AuthService $auth,private AtakDeviceAuthService $service,private AtakDeviceAuthRepository $repo,private FileRateLimiter $limits){}
 private function actor():array{return $this->auth->user()??[];} private function ip():string{return substr((string)($_SERVER['REMOTE_ADDR']??''),0,45);}
 public function index(Request $r,array $p=[]):Response{$u=$this->actor();$uid=(int)($u['id']??0);$tid=(int)($u['tenant_id']??0);return Response::view('layout.main',['content'=>'account.atak_devices','title'=>'Sécurité · Terminaux ATAK','accountHubPage'=>true,'accountUser'=>$u,'devices'=>$this->repo->devices($uid,$tid),'recovery'=>$this->repo->recoverySummary($uid,$tid),'events'=>$this->repo->recentEvents($uid,$tid),'pending'=>Session::get('atak_pair_preview'),'recoveryCodes'=>Session::getFlash('atak_recovery_codes')]);}
 public function lookup(Request $r,array $p=[]):Response{if(!Csrf::validate($r->input('_csrf_token')))return Response::json(['error'=>'csrf_invalid'],419);$u=$this->actor();$uid=(int)$u['id'];if($this->limits->tooManyAttempts('atak:approve:'.$uid,20,600)){Session::flash('error','Trop de tentatives. Réessayez plus tard.');return Response::redirect(url('account/security/devices'));}$pair=$this->service->inspect((string)$r->input('user_code',''));if(!$pair||$pair['status']!=='pending'){Session::flash('error','Code introuvable, expiré ou déjà traité.');Session::forget('atak_pair_preview');}else Session::set('atak_pair_preview',$pair);return Response::redirect(url('account/security/devices').'#pairing');}
 public function decide(Request $r,array $p=[]):Response{if(!Csrf::validate($r->input('_csrf_token')))return Response::json(['error'=>'csrf_invalid'],419);$u=$this->actor();$pair=Session::get('atak_pair_preview');$approve=$r->input('decision')==='approve';if(!is_array($pair)||!$this->service->decide($pair,(int)$u['id'],(int)$u['tenant_id'],$approve,$this->ip()))Session::flash('error','La demande ne peut plus être traitée.');else Session::flash('success',$approve?'Terminal autorisé et enrôlé.':'Demande refusée.');Session::forget('atak_pair_preview');return Response::redirect(url('account/security/devices'));}
 public function recovery(Request $r,array $p=[]):Response{if(!Csrf::validate($r->input('_csrf_token')))return Response::json(['error'=>'csrf_invalid'],419);$u=$this->actor();$password=(string)$r->input('confirm_password','');if(!password_verify($password,(string)($u['password_hash']??''))){Session::flash('error','Mot de passe actuel incorrect.');return Response::redirect(url('account/security/devices').'#recovery');}Session::flash('atak_recovery_codes',$this->service->generateCodes((int)$u['id'],(int)$u['tenant_id'],$this->ip()));return Response::redirect(url('account/security/devices').'#recovery');}
 public function revoke(Request $r,array $p=[]):Response{if(!Csrf::validate($r->input('_csrf_token')))return Response::json(['error'=>'csrf_invalid'],419);$u=$this->actor();$id=(int)($p['id']??0);$ok=$this->repo->revokeDevice($id,(int)$u['id'],(int)$u['tenant_id']);if($ok)$this->repo->event('ATAK_DEVICE_REVOKED',(int)$u['id'],(int)$u['tenant_id'],$id,$this->ip());Session::flash($ok?'success':'error',$ok?'Terminal et sessions révoqués.':'Terminal introuvable.');return Response::redirect(url('account/security/devices'));}
}
