<?php

declare(strict_types=1);

namespace App\Services\Recruitment;

/**
 * Détection locale (sans service externe) de contenus inacceptables sur le portail recrutement.
 * Heuristiques en français, sensibles aux fautes simples d’accentuation.
 *
 * Listes : {@see selfHarmNeedles()}, {@see harassmentPhrases()}, {@see harassmentTokenSet()}.
 * Les aiguilles sont comparées au texte {@see normalize()} : ASCII uniquement (pas d’accents).
 */
final class EnlistmentPortalTextModerationScanner
{
    /**
     * @return array{code: string, public_label: string}|null
     */
    public function scan(string $text): ?array
    {
        $t = trim($text);
        if ($t === '') {
            return null;
        }
        $n = $this->normalize($t);

        foreach (self::selfHarmNeedles() as $needle) {
            if (str_contains($n, $needle)) {
                return [
                    'code' => 'self_harm',
                    'public_label' => 'Contenu évoquant la mise en danger de personnes (suicide, automutilation, etc.)',
                ];
            }
        }

        foreach (self::harassmentPhrases() as $phrase) {
            if (str_contains($n, $phrase)) {
                return [
                    'code' => 'harassment',
                    'public_label' => 'Contenu injurieux, haineux ou de harcèlement',
                ];
            }
        }
        $tokens = preg_split('/[^a-z0-9]+/u', $n, -1, PREG_SPLIT_NO_EMPTY) ?: [];
        $badTokens = self::harassmentTokenSet();
        foreach ($tokens as $tok) {
            if (isset($badTokens[$tok])) {
                return [
                    'code' => 'harassment',
                    'public_label' => 'Contenu injurieux, haineux ou de harcèlement',
                ];
            }
        }

        return null;
    }

    private function normalize(string $s): string
    {
        $s = mb_strtolower($s, 'UTF-8');
        $map = [
            'à' => 'a', 'á' => 'a', 'â' => 'a', 'ä' => 'a', 'ã' => 'a', 'å' => 'a',
            'è' => 'e', 'é' => 'e', 'ê' => 'e', 'ë' => 'e',
            'ì' => 'i', 'í' => 'i', 'î' => 'i', 'ï' => 'i',
            'ò' => 'o', 'ó' => 'o', 'ô' => 'o', 'ö' => 'o', 'õ' => 'o',
            'ù' => 'u', 'ú' => 'u', 'û' => 'u', 'ü' => 'u',
            'ý' => 'y', 'ÿ' => 'y', 'ç' => 'c', 'ñ' => 'n',
            'œ' => 'oe', 'æ' => 'ae',
        ];
        $s = strtr($s, $map);
        $s = preg_replace('/\s+/u', ' ', $s) ?? $s;

        return $s;
    }

    /**
     * @return list<string>
     */
    private static function selfHarmNeedles(): array
    {
        return [
            'suicide',
            'suicidaire',
            'suicid',
            'me suicid',
            'suicide moi',
            'suicide-toi',
            'idees noires suicide',
            'me pendre',
            'me faire pendre',
            'une corde pour me pendre',
            'me tuer',
            'me faire tuer',
            'envie de me tuer',
            'mourir demain',
            'mourir ce soir',
            'mourir seul',
            'je veux mourir',
            'j ai envie de mourir',
            'envie de mourir',
            'plus envie de vivre',
            'plus aucune envie de vivre',
            'je veux plus vivre',
            'je ne veux plus vivre',
            'je ne veux plus etre la',
            'finir avec ma vie',
            'mettre fin a mes jours',
            'mettre fin a ma vie',
            'en finir avec ma vie',
            'mettre fin a tout',
            'plus personne ne me manquera',
            'personne ne me comprend je veux mourir',
            'plus aucune raison de vivre',
            'plus rien ne compte je veux mourir',
            'plus rien a perdre je vais me tuer',
            'personne ne remarquerait si je disparaissais',
            'tout le monde serait mieux sans moi',
            'monde mieux sans moi',
            'automutilation',
            'auto mutilation',
            'auto-mutilation',
            'me blesser gravement',
            'me faire du mal',
            'me couper les veines',
            'me scarifier',
            'me scarifier la peau',
            'me lacerer',
            'me taillader',
            'me sectionner',
            'me trancher',
            'me bruler',
            'saigner jusqu a la mort',
            'overdose volontaire',
            'prendre toutes les pilules',
            'prendre toute la boite',
            'sauter du pont',
            'sauter d un pont',
            'sauter d un immeuble',
            'me jeter sous',
            'me jeter devant',
            'plus la force de continuer a vivre',
            'plus la force de me lever',
            'plus envie de me lever',
            'je veux disparaitre pour toujours',
            'disparaitre pour toujours',
            'disparaitre sans laisser de trace',
            'planifier mon suicide',
            'lettre d adieu',
            'lettre d adieu avant',
            'dernier message avant de mourir',
            'dernier message avant de partir',
            'je ne me sentirai plus jamais mieux',
            'plus aucun espoir de guerir',
            'mutiler mon corps',
            'me mutiler',
            'ne plus me reveiller',
            'dormir et ne plus me reveiller',
            'dormir pour ne plus me reveiller',
            'ne plus jamais me reveiller',
            'je veux plus respirer',
            'arreter de respirer',
            'je veux plus exister',
            'cesser d exister',
            'ne plus exister du tout',
            'partir sans retour',
            'partir sans revenir',
            'partir pour toujours',
            'en finir une bonne fois',
            'en finir avec la douleur',
            'en finir avec moi',
            'en finir avec moi-meme',
            'en finir avec moi meme',
            'plus aucun sens a ma vie',
            'plus aucun sens a continuer',
            'plus aucun espoir',
            'plus aucun avenir',
            'plus d issue que la mort',
            'plus d issue que mourir',
            'plus d issue que le suicide',
            'de toute facon je vais mourir',
            'de toute facon c est fini pour moi',
            'c est fini pour moi',
            'trop tard pour moi',
            'plus jamais sourire',
            'plus jamais rire',
            'coince dans la douleur pour toujours',
            'rejoindre les morts',
            'retrouver les autres la bas',
            'partir les rejoindre la bas',
            'plus personne pour m aider',
            'plus personne a qui parler',
            'plus personne pour m ecouter',
            'plus aucune raison de tenir le coup',
            'plus la force de tenir le coup',
            'plus l envie de vivre',
            'plus l envie de continuer',
            'plus l envie de me battre',
            'plus courage pour vivre',
            'plus de force pour continuer',
            'plus de raison de continuer',
            'je veux que tout s arrete',
            'tout arreter pour toujours',
            'tout abandonner pour toujours',
            'plus rien ne vaut la peine',
            'plus rien n a de sens pour moi',
            'plus rien ne compte pour moi',
            'plus envie de souffrir',
            'plus supporter de vivre',
            'plus supporter la vie',
            'plus envie d etre la',
            'plus envie d ouvrir les yeux',
            'plus envie de parler a personne',
            'plus envie de voir personne',
            'plus envie de sortir',
            'plus envie de bouger',
            'plus envie de manger',
            'plus envie de boire',
            'je veux plus sentir la douleur',
            'plus sentir rien du tout',
            'plus rien ressentir',
            'anesthesie pour toujours',
            'plus exister pour personne',
            'plus etre la pour personne',
            'plus personne a qui me confier',
            'plus aucun espoir que ca aille mieux',
            'plus aucun espoir que ca s arrange',
            'plus aucune raison de tenir',
            'plus tenir le coup',
            'plus lutter pour vivre',
            'plus la force de lutter',
            'plus la force d avancer',
            'plus la force de me battre',
            'plus la force de me lever',
            'plus la force de continuer',
            'plus la force d aller de l avant',
            'je veux arreter de souffrir pour toujours',
            'arreter de souffrir pour toujours',
            'plus souffrir jamais',
            'plus jamais souffrir',
            'plus jamais pleurer',
            'plus jamais parler',
            'plus jamais sortir',
            'plus jamais sortir du lit',
            'plus quitter mon lit',
            'rester au lit pour toujours',
            'ne plus jamais sortir de chez moi',
            'ne plus jamais rien faire',
            'ne plus rien faire de ma vie',
            'tout laisser tomber pour toujours',
            'abandonner la vie',
            'laisser tomber la vie',
            'laisser tomber tout espoir',
            'plus d avenir pour moi',
            'plus d avenir possible',
            'plus d espoir possible',
            'plus d espoir en moi',
            'plus d espoir en l avenir',
            'plus d espoir du tout',
            'plus d espoir nulle part',
        ];
    }

    /**
     * @return list<string>
     */
    private static function harassmentPhrases(): array
    {
        return [
            'ta gueule',
            'ta geule',
            'ferme la',
            'ferme ta gueule',
            'ferme ta geule',
            'ferme ta bouche',
            'ferme la bouche',
            'tais toi',
            'tais-toi',
            'fils de pute',
            'fils de putes',
            'fil de pute',
            'nique ta mere',
            'nique ta race',
            'nique ta famille',
            'nique bien ta',
            'nique bien ta mere',
            'nique bien ta race',
            'nique ton pere',
            'nique ta soeur',
            'nique ta fille',
            'nique ton fils',
            'nique ta grand mere',
            'nique ta grand-mere',
            'va niquer',
            'va te faire niquer',
            'va te faire enculer',
            'va te faire mettre',
            'va te faire foutre',
            'va chier',
            'casse toi',
            'casse-toi',
            'casse les couilles',
            'tu me casses les couilles',
            'je te deteste',
            'je te hais',
            'je te hais a mort',
            'je vais te tuer',
            'je te tue',
            'je vais te defoncer',
            'je vais te fracasser',
            'je vais te casser la gueule',
            'je vais te casser la figure',
            'je vais te pete la gueule',
            'je vais te peter la gueule',
            'je vais t enculer',
            'je vais t eclater',
            'je vais te faire la peau',
            'je vais te faire du mal',
            'je vais te retrouver',
            'je vais te retrouver chez toi',
            'je vais te retrouver au boulot',
            'je vais te retrouver a ton taf',
            'je vais te retrouver a ton travail',
            'tu vas payer',
            'tu vas regretter',
            'tu vas souffrir',
            'tu vas morfler',
            'tu vas prendre cher',
            'tuer ta famille',
            'tuer ton chien',
            'bruler ta maison',
            'sale race',
            'sale juif',
            'sale juive',
            'sale arabe',
            'sale negre',
            'sale negresse',
            'sale bougnoule',
            'sale bicot',
            'sale feuj',
            'sale youpin',
            'sale youpine',
            'sale rebeu',
            'sale rebeue',
            'sale meteque',
            'sale raton',
            'sale singe',
            'sale singe va',
            'retourne dans ton pays',
            'retourne dans ton bled',
            'rentre chez toi',
            'rentre dans ton pays',
            'va crever',
            'va crev',
            'creve toi',
            'creve-toi',
            'creve la gueule ouverte',
            'va crever seul',
            'creve tout seul',
            'encule toi',
            'encule-toi',
            'enculer ta mere',
            'enculer ta race',
            'nique bien',
            'nique les morts',
            'nique les morts de',
            'sale pute',
            'sale putes',
            'grosse pute',
            'grosse pute va crever',
            'sale pute va crever',
            'sale connard',
            'sale connasse',
            'trou du cul',
            'trou du cul de',
            'grosse merde',
            'sale merde',
            'sous merde',
            't es une merde',
            'tes une merde',
            'tu es une merde',
            't es qu une merde',
            'piece de merde',
            'peau de merde',
            'espece de merde',
            'espece de connard',
            'espece de salope',
            'bouffon va crever',
            'sale batard',
            'sale batards',
            'sale batard va',
            'fous le camp',
            'fout le camp',
            'fous-toi',
            'remballe toi',
            'remballe-toi',
            'va mourir',
            'creve bien',
            'je te baise ta mere',
            'je baise ta mere',
            'je te nique',
            'je vais te niquer',
            'suce ma bite',
            'suce ma queue',
            't es qu un chien',
            't es qu une chienne',
            'sale chienne',
            'sale chien',
            'ferme ta gueule de merde',
            'grosse garce',
            'sale garce',
            'va te pendre',
            'pend toi',
            't es fini',
            'je vais te pourrir la vie',
            'je vais te ruiner la vie',
            'je vais te faire virer',
            'je vais te faire expulser',
            'je vais te doxxer',
            'je vais te dox',
            'je poste ton adresse',
            'je connais ton adresse',
            'je sais ou tu habites',
            'je sais ou tu vis',
            'je te retrouve',
            'on va te retrouver',
            'menace de mort',
            'tuer sur place',
            'crever comme un chien',
            'mange tes morts',
            'va manger tes morts',
            'mange la merde',
            'bouffe ta merde',
            'bouffe ta race',
            'bouffe ton char',
            'va en enfer',
            'brule en enfer',
            'creve en enfer',
            'pourris en enfer',
            'j espere que tu creves',
            'j espere que tu meurs',
            'j espere que tu vas crever',
            'j espere que tu vas mourir',
            'j espere que tu te suicides',
            'j espere que tu te suicid',
            'j espere que tu te pendes',
            'je te souhaite la mort',
            'je te souhaite de crever',
            'je te souhaite de mourir',
            'je te souhaite le cancer',
            'je te souhaite le sida',
            'creve du sida',
            'creve du cancer',
            'tire toi une balle',
            'tire une balle dans la tete',
            'une balle dans la tete',
            'balle dans la tete',
            'sale pedophile',
            'sale pedo',
            'sale pd de merde',
            'sale pede de merde',
            'sale pede va crever',
            'sale pd va crever',
            'sale tarlouze',
            'sale pedale',
            'sale tapette',
            'sale gouine',
            'sale gouinasse',
            'sale gay de merde',
            'sale lesbienne de merde',
            'sale trans de merde',
            'sale trans va crever',
            'sale zoophile',
            'sale hermaphrodite',
            'sale travesti',
            'sale travestie',
            'sale transgenre de merde',
            'sale transgenre va crever',
            'sale violeur',
            'sale violeuse',
            'sale violeur de merde',
            'sale violeuse de merde',
            'sale type va',
            'sale mec va',
            'sale meuf',
            'sale meuf va',
            'sale meuf va crever',
            'sale mec va crever',
            'sale gonzesse',
            'sale espece',
            'sale espece de',
        ];
    }

    /**
     * @return array<string, true>
     */
    private static function harassmentTokenSet(): array
    {
        $w = [
            // Abréviations / argot écrit (le texte est normalisé en minuscules : FDP → fdp).
            'fdp', 'ftg', 'slp', 'ptg', 'tgm', 'tml', 'tmr', 'ntg', 'ntm', 'ntm2', 'nt1', 'nt1m',
            'ptn', 'pt1', 'pt1n', 'pd', 'pds', 'pd2', 'pd3', 'tg', 'tgl', 'tglpt',
            'n1k', 'n1que', 'n1quer', 'n1k1', 'n1k3', 'n1k3r',
            'nazi', 'nazis', 'nazl', 'nazo', 'ns', 'ss',
            'juif', 'juifs', 'juive', 'juives',
            'arabe', 'arabes', 'bic', 'bng', 'bngl', 'rebeu', 'rebeus', 'rebeue', 'rebeues',
            'neg', 'negs', 'n3gr', 'n3gre',
            'youp', 'youps', 'feuj', 'feujs',
            'connard', 'connards', 'connasse', 'connasses', 'conasse', 'conard', 'conards',
            'salope', 'salopes', 'pute', 'putes', 'putain', 'put1', 'put2', 'put3',
            'merde', 'merdes', 'emmerde', 'emmerder', 'emmerdeur', 'emmerdeuse',
            'bouffon', 'bouffonne', 'bouffons', 'debile', 'debiles', 'imbecile', 'imbeciles',
            'encule', 'encules', 'enculee', 'enculees', 'enculer', 'niquer', 'nique', 'niques', 'niquez',
            'idiot', 'idiots', 'idiote', 'idiotes', 'salaud', 'salauds', 'ordure', 'ordures',
            'goujat', 'goujats', 'enfoire', 'enfoires', 'batard', 'batards', 'batarde', 'batardes',
            'trouduc', 'trouducs', 'poufiasse', 'poufiasses', 'pouffiasse', 'pouffiasses',
            'grognasse', 'grognasses',
            'tapette', 'tapettes', 'pedale', 'pedales', 'tarlouze', 'tarlouzes',
            'chienne', 'chiennes', 'pourriture', 'pourritures',
            'vaurien', 'vauriens', 'vaurienne', 'vauriennes', 'racaille', 'racailles',
            'clochard', 'clochards', 'clocharde', 'clochardes',
            'lache', 'laches', 'lachette', 'lachettes',
            'degueulasse', 'deguelasse', 'degueu', 'sacmerde', 'sacmerdes', 'sacrammerde',
            'glandu', 'glandus', 'glandue', 'glandues', 'gogole', 'gogoles', 'gogol',
            'cretin', 'cretins', 'cretine', 'cretines', 'abruti', 'abrutis', 'abrutie', 'abruties',
            'teube', 'teubes', 'teub', 'teubs', 'tafiole', 'tafioles', 'fiotte', 'fiottes',
            'lopette', 'lopettes', 'pede', 'pedes',
            'nazi', 'nazis', 'hitler', 'heil', 'sieg', 'hitlerien', 'hitleriens',
            'negre', 'negres', 'negresse', 'negresses',
            'bicot', 'bicots', 'bougnoule', 'bougnoules', 'rebeu', 'rebeus', 'rebeue', 'rebeues',
            'youpin', 'youpins', 'youpine', 'youpines', 'feuj', 'feujs',
            'enculeur', 'enculeurs', 'enculeuse', 'enculeuses',
            'foutre', 'foutres',
            'garce', 'garces', 'pouf', 'poufs', 'trainee', 'trainees',
            'sousrace', 'untermensch',
            'kk', 'kikoo', 'kikoulol',
            'couillon', 'couillons', 'couillonne', 'couillonnes',
            'burne', 'burnes',
            'zguegue', 'zigounette', 'zigounettes',
            'branleur', 'branleurs', 'branleuse', 'branleuses',
            'troufignon', 'troufignons', 'fiottard', 'fiottards',
            'schmock', 'schmocks',
            'pedo', 'pedos', 'pedophile', 'pedophiles',
            'zoophile', 'zoophiles',
            'gouine', 'gouines', 'gouinasse', 'gouinasses',
            'bougnoul', 'bougnouls',
            'youpinasse', 'youpinasses',
            'facho', 'fachos', 'fasciste', 'fascistes',
            'collabo', 'collabos',
            'necrophile', 'necrophiles',
            'coprophile', 'coprophiles',
        ];

        $w = array_values(array_unique($w));

        return array_fill_keys($w, true);
    }
}
