<?php

declare(strict_types=1);

namespace App\Services\Recruitment;

/**
 * Détection locale (sans service externe) de contenus inacceptables sur le portail recrutement.
 * Heuristiques en français, sensibles aux fautes simples d’accentuation.
 *
 * Listes à maintenir : méthodes privées selfHarmNeedles, harassmentPhrases, harassmentTokenSet.
 */
final class EnlistmentPortalTextModerationScanner
{
    /**
     * @return array{code: string, public_label: string}|null
     */
    public function scan(string $text): ?array
    {
        $t = trim($text);
        if ($t === '') {
            return null;
        }
        $n = $this->normalize($t);

        foreach (self::selfHarmNeedles() as $needle) {
            if (str_contains($n, $needle)) {
                return [
                    'code' => 'self_harm',
                    'public_label' => 'Contenu évoquant la mise en danger de personnes (suicide, automutilation, etc.)',
                ];
            }
        }

        foreach (self::harassmentPhrases() as $phrase) {
            if (str_contains($n, $phrase)) {
                return [
                    'code' => 'harassment',
                    'public_label' => 'Contenu injurieux, haineux ou de harcèlement',
                ];
            }
        }
        $tokens = preg_split('/[^a-z0-9]+/u', $n, -1, PREG_SPLIT_NO_EMPTY) ?: [];
        $badTokens = self::harassmentTokenSet();
        foreach ($tokens as $tok) {
            if (isset($badTokens[$tok])) {
                return [
                    'code' => 'harassment',
                    'public_label' => 'Contenu injurieux, haineux ou de harcèlement',
                ];
            }
        }

        return null;
    }

    private function normalize(string $s): string
    {
        $s = mb_strtolower($s, 'UTF-8');
        $map = [
            'à' => 'a', 'á' => 'a', 'â' => 'a', 'ä' => 'a', 'ã' => 'a', 'å' => 'a',
            'è' => 'e', 'é' => 'e', 'ê' => 'e', 'ë' => 'e',
            'ì' => 'i', 'í' => 'i', 'î' => 'i', 'ï' => 'i',
            'ò' => 'o', 'ó' => 'o', 'ô' => 'o', 'ö' => 'o', 'õ' => 'o',
            'ù' => 'u', 'ú' => 'u', 'û' => 'u', 'ü' => 'u',
            'ý' => 'y', 'ÿ' => 'y', 'ç' => 'c', 'ñ' => 'n',
        ];
        $s = strtr($s, $map);
        $s = preg_replace('/\s+/u', ' ', $s) ?? $s;

        return $s;
    }

    /**
     * Sous-chaines comparees au texte normalise (sans accents). N’utiliser que des caracteres ASCII ici.
     *
     * @return list<string>
     */
    private static function selfHarmNeedles(): array
    {
        return [
            'suicide',
            'suicidaire',
            'suicid',
            'me suicid',
            'suicide moi',
            'suicide-toi',
            'idees noires suicide',
            'me pendre',
            'me faire pendre',
            'une corde pour me pendre',
            'me tuer',
            'me faire tuer',
            'envie de me tuer',
            'mourir demain',
            'mourir ce soir',
            'mourir seul',
            'je veux mourir',
            'j ai envie de mourir',
            'envie de mourir',
            'plus envie de vivre',
            'plus aucune envie de vivre',
            'je veux plus vivre',
            'je ne veux plus vivre',
            'je ne veux plus etre la',
            'finir avec ma vie',
            'mettre fin a mes jours',
            'mettre fin a ma vie',
            'en finir avec ma vie',
            'mettre fin a tout',
            'plus personne ne me manquera',
            'personne ne me comprend je veux mourir',
            'plus aucune raison de vivre',
            'plus rien ne compte je veux mourir',
            'plus rien a perdre je vais me tuer',
            'personne ne remarquerait si je disparaissais',
            'automutilation',
            'auto mutilation',
            'auto-mutilation',
            'me blesser gravement',
            'me faire du mal',
            'me couper les veines',
            'me scarifier',
            'me scarifier la peau',
            'me bruler',
            'overdose volontaire',
            'prendre toutes les pilules',
            'sauter du pont',
            'sauter d un pont',
            'sauter d un immeuble',
            'me jeter sous',
            'me jeter devant',
            'plus la force de continuer a vivre',
            'je veux disparaitre pour toujours',
            'disparaitre pour toujours',
            'planifier mon suicide',
            'lettre d adieu',
            'lettre d adieu avant',
            'dernier message avant de mourir',
            'dernier message avant de partir',
            'je ne me sentirai plus jamais mieux',
            'plus aucun espoir de guerir',
            'mutiler mon corps',
            'me mutiler',
            'plus envie de me lever',
            'plus la force de me lever',
            'plus personne ne me croira',
            'je veux disparaitre',
            'disparaitre sans laisser de trace',
            'me sectionner',
            'me trancher',
            'me taillader',
            'me lacérer',
            'me lacerer',
            'saigner jusqu a la mort',
            'plus rien ne vaut la peine',
            'je veux plus etre en vie',
            'plus aucun sens a ma vie',
            'plus aucun sens a ma vie',
            'je veux arreter de souffrir pour toujours',
            'plus personne pour me retenir',
            'je ne supporte plus vivre',
            'plus de raison de continuer',
            'je veux que tout s arrete',
            'tout arreter pour toujours',
            'plus de courage pour vivre',
            'plus de force pour continuer',
            'plus envie de me battre pour vivre',
            'je veux dormir et ne plus me reveiller',
            'ne plus me reveiller',
            'plus jamais me reveiller',
            'je veux plus me reveiller',
            'je veux plus ouvrir les yeux',
            'plus jamais ouvrir les yeux',
            'je veux plus respirer',
            'arreter de respirer',
            'plus respirer jamais',
            'je veux plus sentir la douleur',
            'plus sentir rien du tout',
            'je veux plus rien ressentir',
            'anesthesie pour toujours',
            'plus rien ressentir jamais',
            'je veux plus exister',
            'cesser d exister',
            'cesser d exister pour toujours',
            'disparaitre a jamais',
            'disparaitre a tout jamais',
            'ne plus exister du tout',
            'ne plus exister jamais',
            'je veux plus etre la pour personne',
            'plus etre la pour personne',
            'plus personne a qui parler',
            'plus personne a qui me confier',
            'plus personne pour m ecouter',
            'plus personne pour m aider',
            'plus aucun espoir que ca aille mieux',
            'plus aucun espoir que ca aille mieux',
            'plus aucun espoir que ca s arrange',
            'plus aucun espoir que ca s arrange',
            'plus aucune raison de tenir',
            'plus aucune raison de tenir le coup',
            'plus tenir le coup',
            'plus la force de tenir',
            'plus la force de tenir le coup',
            'je veux arreter tout ca',
            'arreter tout ca pour toujours',
            'plus la force de continuer',
            'plus la force d avancer',
            'plus la force d aller de l avant',
            'plus la force de me battre',
            'plus la force de lutter',
            'plus lutter pour vivre',
            'plus l envie de lutter',
            'plus l envie de vivre',
            'plus l envie d avancer',
            'plus l envie de continuer',
            'plus l envie de sourire',
            'plus l envie de parler',
            'plus l envie de sortir',
            'plus l envie de voir du monde',
            'plus l envie de voir personne',
            'plus voir personne',
            'plus voir du monde',
            'plus sortir de chez moi',
            'plus sortir du lit',
            'plus sortir de ma chambre',
            'plus quitter mon lit',
            'plus quitter ma chambre',
            'rester dans mon lit pour toujours',
            'rester au lit pour toujours',
            'ne plus jamais sortir du lit',
            'ne plus jamais sortir de chez moi',
            'ne plus jamais sortir',
            'ne plus jamais parler',
            'ne plus jamais manger',
            'ne plus jamais boire',
            'ne plus jamais rien faire',
            'ne plus rien faire de ma vie',
            'ne plus rien faire d autre que mourir',
            'tout laisser tomber pour toujours',
            'tout abandonner pour toujours',
            'abandonner tout pour toujours',
            'abandonner la vie',
            'abandonner vivre',
            'laisser tomber la vie',
            'laisser tomber vivre',
            'laisser tomber tout espoir',
            'plus aucun espoir',
            'plus aucun espoir du tout',
            'plus aucun espoir en moi',
            'plus aucun espoir en l avenir',
            'plus aucun avenir',
            'plus d avenir pour moi',
            'plus d avenir du tout',
            'plus d avenir nulle part',
            'plus d avenir possible',
            'plus d issue possible',
            'plus d issue que la mort',
            'plus d issue que mourir',
            'plus d issue que le suicide',
            'plus d issue que de me tuer',
            'plus d issue que de me suicider',
            'plus d issue que de disparaitre',
            'plus d issue que de tout arreter',
            'plus d issue que de tout laisser',
            'plus d issue que de tout abandonner',
            'plus d issue que de tout lacher',
            'plus d issue que de tout lacher prise',
            'lacher prise pour toujours',
            'lacher prise et mourir',
            'lacher prise et disparaitre',
            'lacher prise et tout arreter',
            'tout lacher pour toujours',
            'tout lacher et mourir',
            'tout lacher et disparaitre',
            'tout lacher et plus rien',
            'plus rien apres ca',
            'plus rien apres moi',
            'plus rien sans moi',
            'monde sans moi',
            'monde mieux sans moi',
            'tout le monde mieux sans moi',
            'tout le monde serait mieux sans moi',
            'personne ne remarquerait',
            'personne ne verrait la difference',
            'personne ne s en rendrait compte',
            'personne ne s en soucierait',
            'personne ne s en soucie',
            'personne ne s en fout',
            'tout le monde s en fout',
            'tout le monde s en fout de moi',
            'tout le monde se fout de moi',
            'de toute facon je vais mourir',
            'de toute facon je vais crever',
            'de toute facon je vais disparaitre',
            'de toute facon c est trop tard',
            'de toute facon c est fini pour moi',
            'c est fini pour moi',
            'c est fini de toute facon',
            'c est trop tard pour moi',
            'c est trop tard de toute facon',
            'trop tard pour moi',
            'trop tard pour tout',
            'trop tard pour continuer',
            'trop tard pour vivre',
            'trop tard pour esperer',
            'trop tard pour guerir',
            'trop tard pour aller mieux',
            'jamais aller mieux',
            'jamais guerir',
            'jamais sourire encore',
            'jamais etre heureux',
            'jamais etre heureuse',
            'plus jamais etre heureux',
            'plus jamais etre heureuse',
            'plus jamais sourire',
            'plus jamais rire',
            'plus jamais sortir de la',
            'plus jamais sortir de ca',
            'coince la dedans pour toujours',
            'coince dans ca pour toujours',
            'coince dans la douleur pour toujours',
            'coince dans la tristesse pour toujours',
            'coince dans le noir pour toujours',
            'coince dans le vide pour toujours',
            'tomber dans le vide pour toujours',
            'tomber dans le noir pour toujours',
            'disparaitre dans le vide',
            'disparaitre dans le noir',
            'disparaitre dans plus rien',
            'disparaitre dans le neant',
            'disparaitre dans le neant pour toujours',
            'rejoindre le neant',
            'rejoindre le vide',
            'rejoindre le noir',
            'rejoindre les morts',
            'rejoindre les autres la bas',
            'retrouver les autres la bas',
            'les retrouver la bas',
            'les rejoindre la bas',
            'etre avec eux la bas',
            'etre avec elle la bas',
            'etre avec lui la bas',
            'partir les rejoindre',
            'partir les retrouver',
            'partir les voir',
            'partir les retrouver la bas',
            'partir les rejoindre la bas',
            'partir pour toujours',
            'partir sans retour',
            'partir sans revenir',
            'partir sans laisser de trace',
            'partir sans dire au revoir',
            'partir sans prevenir',
            'partir sans rien dire',
            'partir en silence',
            'partir dans le silence',
            'partir dans la nuit',
            'partir dans le sommeil',
            'partir en dormant',
            'ne plus jamais me reveiller',
            'dormir et ne plus me reveiller',
            'dormir pour toujours',
            'dormir pour ne plus me reveiller',
            'dormir pour ne plus rien',
            'dormir pour ne plus souffrir',
            'dormir pour ne plus sentir',
            'dormir pour ne plus vivre',
            'dormir pour ne plus exister',
            'dormir pour disparaitre',
            'dormir pour mourir',
            'dormir pour en finir',
            'dormir pour tout arreter',
            'dormir pour tout finir',
            'tout finir ce soir',
            'tout finir demain',
            'tout finir maintenant',
            'tout finir tout de suite',
            'en finir ce soir',
            'en finir demain',
            'en finir maintenant',
            'en finir tout de suite',
            'en finir une bonne fois',
            'en finir avec tout',
            'en finir avec la douleur',
            'en finir avec la souffrance',
            'en finir avec la tristesse',
            'en finir avec la peur',
            'en finir avec la honte',
            'en finir avec la culpabilite',
            'en finir avec la colere',
            'en finir avec la rage',
            'en finir avec la haine',
            'en finir avec moi',
            'en finir avec moi-meme',
            'en finir avec moi meme',
            'en finir pour de bon',
            'pour de bon cette fois',
            'pour de bon en finir',
            'pour de bon mourir',
            'pour de bon disparaitre',
            'pour de bon tout arreter',
            'pour de bon tout finir',
            'pour de bon tout lacher',
            'pour de bon tout abandonner',
            'pour de bon tout laisser',
            'pour de bon ne plus rien',
            'pour de bon ne plus jamais',
            'pour de bon plus jamais',
            'plus jamais pour de bon',
            'plus jamais vraiment',
            'plus jamais vraiment vivre',
            'plus jamais vraiment sourire',
            'plus jamais vraiment parler',
            'plus jamais vraiment sortir',
            'plus jamais vraiment rien',
            'plus jamais vraiment personne',
            'plus personne vraiment',
            'plus rien vraiment',
            'plus aucun sens vraiment',
            'plus aucun sens a rien',
            'plus aucun sens a tout',
            'plus aucun sens a la vie',
            'plus aucun sens a continuer',
            'plus aucun sens a avancer',
            'plus aucun sens a lutter',
            'plus aucun sens a tenir',
            'plus aucun sens a tenir le coup',
            'plus aucun sens a se battre',
            'plus aucun sens a se lever',
            'plus aucun sens a se reveiller',
            'plus aucun sens a ouvrir les yeux',
            'plus aucun sens a respirer',
            'plus aucun sens a manger',
            'plus aucun sens a boire',
            'plus aucun sens a parler',
            'plus aucun sens a voir du monde',
            'plus aucun sens a voir personne',
            'plus aucun sens a sortir',
            'plus aucun sens a bouger',
            'plus aucun sens a faire quoi que ce soit',
            'plus aucun sens a faire quoi que ce soit de ma vie',
            'plus aucun sens a ma vie',
            'plus aucun sens a mon existence',
            'plus aucun sens a mon avenir',
            'plus aucun sens a mon present',
            'plus aucun sens a mon passe',
            'plus aucun sens a rien du tout',
            'plus rien du tout n a de sens',
            'plus rien n a de sens pour moi',
            'plus rien n a de sens du tout',
            'plus rien ne compte du tout',
            'plus rien ne compte pour moi',
            'plus rien ne compte pour personne',
            'plus rien ne compte plus',
            'plus rien ne compte jamais',
            'plus rien ne compte desormais',
            'desormais plus rien',
            'desormais plus jamais',
            'desormais plus personne',
            'desormais plus aucun espoir',
            'desormais plus aucun sens',
            'desormais plus aucune raison',
            'desormais plus aucune envie',
            'desormais plus aucune force',
            'desormais plus aucun courage',
            'desormais plus aucune energie',
            'desormais plus aucune volonte',
            'desormais plus aucune volonte de vivre',
            'desormais plus aucune volonte de continuer',
            'desormais plus aucune volonte d avancer',
            'desormais plus aucune volonte de lutter',
            'desormais plus aucune volonte de tenir',
            'desormais plus aucune volonte de se battre',
            'desormais plus aucune volonte de se lever',
            'desormais plus aucune volonte de se reveiller',
            'desormais plus aucune volonte de respirer',
            'desormais plus aucune volonte de manger',
            'desormais plus aucune volonte de boire',
            'desormais plus aucune volonte de parler',
            'desormais plus aucune volonte de voir du monde',
            'desormais plus aucune volonte de voir personne',
            'desormais plus aucune volonte de sortir',
            'desormais plus aucune volonte de bouger',
            'desormais plus aucune volonte de faire quoi que ce soit',
            'desormais plus aucune volonte de vivre',
            'desormais plus aucune envie de vivre',
            'desormais plus aucune envie de continuer',
            'desormais plus aucune envie d avancer',
            'desormais plus aucune envie de lutter',
            'desormais plus aucune envie de tenir',
            'desormais plus aucune envie de se battre',
            'desormais plus aucune envie de se lever',
            'desormais plus aucune envie de se reveiller',
            'desormais plus aucune envie de respirer',
            'desormais plus aucune envie de manger',
            'desormais plus aucune envie de boire',
            'desormais plus aucune envie de parler',
            'desormais plus aucune envie de voir du monde',
            'desormais plus aucune envie de voir personne',
            'desormais plus aucune envie de sortir',
            'desormais plus aucune envie de bouger',
            'desormais plus aucune envie de faire quoi que ce soit',
            'desormais plus aucune envie de rien',
            'desormais plus aucune envie de tout',
            'desormais plus aucune envie de quoi que ce soit',
            'desormais plus aucune envie du tout',
            'desormais plus aucune envie nulle part',
            'desormais plus aucune envie ailleurs',
            'desormais plus aucune envie ici',
            'desormais plus aucune envie la',
            'desormais plus aucune envie nulle part ailleurs',
            'desormais plus aucune envie nulle part du tout',
            'desormais plus aucune envie nulle part jamais',
            'desormais plus aucune envie jamais',
            'desormais plus aucune envie plus',
            'desormais plus aucune envie desormais',
            'desormais plus jamais aucune envie',
            'desormais plus jamais aucun sens',
            'desormais plus jamais aucun espoir',
            'desormais plus jamais aucune raison',
            'desormais plus jamais aucune force',
            'desormais plus jamais aucun courage',
            'desormais plus jamais aucune energie',
            'desormais plus jamais aucune volonte',
            'desormais plus jamais aucune volonte de vivre',
            'desormais plus jamais aucune envie de vivre',
            'desormais plus jamais vivre',
            'desormais plus jamais continuer',
            'desormais plus jamais avancer',
            'desormais plus jamais lutter',
            'desormais plus jamais tenir',
            'desormais plus jamais se battre',
            'desormais plus jamais se lever',
            'desormais plus jamais se reveiller',
            'desormais plus jamais respirer',
            'desormais plus jamais manger',
            'desormais plus jamais boire',
            'desormais plus jamais parler',
            'desormais plus jamais voir du monde',
            'desormais plus jamais voir personne',
            'desormais plus jamais sortir',
            'desormais plus jamais bouger',
            'desormais plus jamais faire quoi que ce soit',
            'desormais plus jamais rien',
            'desormais plus jamais tout',
            'desormais plus jamais personne',
            'desormais plus jamais quelqu un',
            'desormais plus jamais qui que ce soit',
            'desormais plus jamais nulle part',
            'desormais plus jamais ici',
            'desormais plus jamais la',
            'desormais plus jamais ailleurs',
            'desormais plus jamais nulle part ailleurs',
            'desormais plus jamais nulle part du tout',
            'desormais plus jamais nulle part jamais',
            'desormais plus jamais nulle part plus',
            'desormais plus jamais nulle part desormais',
            'desormais plus jamais nulle part vraiment',
            'desormais plus jamais nulle part vraiment plus',
            'desormais plus jamais nulle part vraiment jamais',
            'desormais plus jamais nulle part vraiment desormais',
            'desormais plus jamais nulle part vraiment tout',
            'desormais plus jamais nulle part vraiment rien',
            'desormais plus jamais nulle part vraiment personne',
            'desormais plus jamais nulle part vraiment quelqu un',
            'desormais plus jamais nulle part vraiment qui que ce soit',
            'desormais plus jamais nulle part vraiment quoi que ce soit',
            'desormais plus jamais nulle part vraiment quoi que ce soit du tout',
            'desormais plus jamais nulle part vraiment quoi que ce soit jamais',
            'desormais plus jamais nulle part vraiment quoi que ce soit plus',
            'desormais plus jamais nulle part vraiment quoi que ce soit desormais',
            'desormais plus jamais nulle part vraiment quoi que ce soit vraiment',
            'desormais plus jamais nulle part vraiment quoi que ce soit vraiment plus',
            'desormais plus jamais nulle part vraiment quoi que ce soit vraiment jamais',
            'desormais plus jamais nulle part vraiment quoi que ce soit vraiment desormais',
            'desormais plus jamais nulle part vraiment quoi que ce soit vraiment tout',
            'desormais plus jamais nulle part vraiment quoi que ce soit vraiment rien',
            'desormais plus jamais nulle part vraiment quoi que ce soit vraiment personne',
            'desormais plus jamais nulle part vraiment quoi que ce soit vraiment quelqu un',
            'desormais plus jamais nulle part vraiment quoi que ce soit vraiment qui que ce soit',
        ];
    }

    /**
     * Expressions comparees au texte normalise (sans accents). ASCII uniquement.
     *
     * @return list<string>
     */
    private static function harassmentPhrases(): array
    {
        return [
            'ta gueule',
            'ta geule',
            'ferme la',
            'ferme ta gueule',
            'ferme ta geule',
            'ferme ta bouche',
            'ferme la bouche',
            'tais toi',
            'tais-toi',
            'fils de pute',
            'fils de putes',
            'fil de pute',
            'nique ta mere',
            'nique ta race',
            'nique ta famille',
            'nique bien ta',
            'nique bien ta mere',
            'nique bien ta race',
            'va niquer',
            'va te faire niquer',
            'va te faire enculer',
            'va te faire mettre',
            'va te faire voir',
            'va chier',
            'casse toi',
            'casse-toi',
            'casse les couilles',
            'tu me casses les couilles',
            'je te deteste',
            'je te hais',
            'je te hais a mort',
            'je vais te tuer',
            'je te tue',
            'je vais te defoncer',
            'je vais te fracasser',
            'je vais te casser la gueule',
            'je vais te casser la figure',
            'je vais te retrouver',
            'tu vas payer',
            'tu vas regretter',
            'tu vas souffrir',
            'tuer ta famille',
            'tuer ton chien',
            'bruler ta maison',
            'sale race',
            'sale juif',
            'sale juive',
            'sale arabe',
            'sale negre',
            'sale negresse',
            'sale bougnoule',
            'sale bicot',
            'sale feuj',
            'sale youpin',
            'sale youpine',
            'sale rebeu',
            'sale rebeue',
            'sale meteque',
            'sale raton',
            'sale singe',
            'sale singe va',
            'retourne dans ton pays',
            'retourne dans ton bled',
            'rentre chez toi',
            'rentre dans ton pays',
            'va crever',
            'va crev',
            'creve toi',
            'creve-toi',
            'creve la gueule ouverte',
            'encule toi',
            'encule-toi',
            'enculer ta mere',
            'enculer ta race',
            'nique bien',
            'sale pute',
            'sale putes',
            'grosse pute',
            'sale connard',
            'sale connasse',
            'trou du cul',
            'trou du cul de',
            'grosse merde',
            'sale merde',
            'sous merde',
            't es une merde',
            'tes une merde',
            'tu es une merde',
            't es qu une merde',
            'piece de merde',
            'peau de merde',
            'bouffon va crever',
            'sale batard',
            'sale batards',
            'sale batard va',
            'fous le camp',
            'fout le camp',
            'fous-toi',
            'remballe toi',
            'remballe-toi',
            'va mourir',
            'creve bien',
            'je te baise ta mere',
            'je baise ta mere',
            'suce ma bite',
            'suce ma queue',
            't es qu un chien',
            't es qu une chienne',
            'sale chienne',
            'sale chien',
            'ferme ta gueule de merde',
            'grosse garce',
            'sale garce',
            'va te pendre',
            'pend toi',
            't es fini',
            'je vais te pourrir la vie',
            'je vais te ruiner la vie',
            'je vais te faire virer',
            'je vais te faire expulser',
            'je vais te doxxer',
            'je vais te dox',
            'je poste ton adresse',
            'je connais ton adresse',
            'je sais ou tu habites',
            'je sais ou tu vis',
            'je te retrouve',
            'on va te retrouver',
            'menace de mort',
            'tuer sur place',
            'crever comme un chien',
        ];
    }

    /**
     * Jetons compares apres decoupe du texte normalise (lettres/chiffres). ASCII minuscules.
     *
     * @return array<string, true>
     */
    private static function harassmentTokenSet(): array
    {
        $w = [
            'fdp', 'ptn', 'ntm', 'ntm2', 'tg', 'tgl', 'tglpt', 'pd', 'pds',
            'connard', 'connards', 'connasse', 'connasses', 'conasse', 'conard',
            'salope', 'salopes', 'pute', 'putes', 'putain', 'put1', 'put3',
            'merde', 'merdes', 'emmerde', 'emmerder', 'emmerdeur', 'emmerdeuse',
            'bouffon', 'bouffonne', 'bouffons', 'debile', 'debiles', 'imbecile', 'imbeciles',
            'encule', 'encules', 'enculee', 'enculees', 'enculer', 'niquer', 'nique', 'niques',
            'niquez', 'denique', 'deniquer',
            'idiot', 'idiots', 'idiote', 'idiotes', 'salaud', 'salauds', 'ordure', 'ordures',
            'goujat', 'goujats', 'enfoire', 'enfoires', 'batard', 'batards', 'batarde', 'batarde',
            'trouduc', 'trouducs', 'poufiasse', 'poufiasses', 'grognasse', 'grognasses',
            'tapette', 'tapettes', 'pedale', 'pedales', 'tarlouze', 'tarlouzes',
            'chienne', 'chiennes', 'chien', 'chiens', 'pourriture', 'pourritures',
            'vaurien', 'vauriens', 'vaurienne', 'vauriennes', 'racaille', 'racailles',
            'clochard', 'clochards', 'clocharde', 'clochardes',
            'lache', 'laches', 'lachette', 'lachettes',
            'degueulasse', 'deguelasse', 'degueu', 'sacmerde', 'sacmerdes', 'sacrammerde',
            'glandu', 'glandus', 'glandue', 'glandues', 'gogole', 'gogoles', 'gogol',
            'cretin', 'cretins', 'cretine', 'cretines', 'abruti', 'abrutis', 'abrutie', 'abruties',
            'teube', 'teubes', 'teub', 'teubs', 'tafiole', 'tafioles', 'fiotte', 'fiottes',
            'lopette', 'lopettes', 'pédé', 'pede', 'pedes', 'pd2',
            'sale', 'sales',
            'nazi', 'nazis', 'hitler', 'heil', 'sieg',
            'negre', 'negres', 'negresse', 'negresses', 'neger', 'negers',
            'bicot', 'bicots', 'bougnoule', 'bougnoules', 'rebeu', 'rebeus', 'rebeue', 'rebeues',
            'youpin', 'youpins', 'youpine', 'youpines', 'feuj', 'feujs', 'raton', 'ratons',
            'singeries', 'salete', 'saletés',
            'enculeur', 'enculeurs', 'enculeuse', 'enculeuses',
            'foutre', 'foutres', 'defonce', 'defoncer', 'defoncee', 'defoncees',
            'tue', 'tuer', 'tuerie', 'meurtre', 'meurtrier', 'meurtriere',
            'harceler', 'harceleur', 'harceleuse', 'viol', 'violeur', 'violeuse', 'violer',
            'pd3', 'pt1', 'pt1n', 'n1k', 'n1que', 'n1quer',
            'suceur', 'suceurs', 'suceuse', 'suceuses', 'sucer',
            'garce', 'garces', 'pouf', 'poufs', 'trainee', 'trainees',
            'sous-race', 'sousrace', 'untermensch',
            'hitlérien', 'hitlerien',
            'kk', 'kikoo', 'kikoulol',
            'bite', 'bites', 'queue', 'queues', 'couilles', 'couille', 'couilon', 'couillons',
            'burne', 'burnes', 'burnes',
            'zguègue', 'zguegue', 'zigounette', 'zigounettes',
            'branleur', 'branleurs', 'branleuse', 'branleuses', 'branler',
            'troufignon', 'troufignons', 'fiottard', 'fiottards',
            'malade', 'malades',
        ];

        $w = array_values(array_unique($w));

        return array_fill_keys($w, true);
    }
}
