-- MEDEVAC — DDL portable (MariaDB / MySQL partagé)
-- Pas de GENERATED / FK / COMMENT / triggers (gérés côté appli + bootstrap).

CREATE TABLE IF NOT EXISTS atak_medevac_requests (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    tenant_id INT UNSIGNED NOT NULL,
    context_id INT UNSIGNED NOT NULL,
    medevac_number VARCHAR(50) NOT NULL,
    priority ENUM('URGENT', 'PRIORITY', 'ROUTINE', 'CONVENIENCE') NOT NULL DEFAULT 'URGENT',
    pickup_grid VARCHAR(50) NOT NULL,
    pickup_pos_x DECIMAL(12, 4) NULL,
    pickup_pos_y DECIMAL(12, 4) NULL,
    pickup_elevation INT NULL,
    radio_frequency VARCHAR(20) NULL,
    radio_callsign VARCHAR(100) NULL,
    patients_t1_urgent INT UNSIGNED DEFAULT 0,
    patients_t2_urgent INT UNSIGNED DEFAULT 0,
    patients_t3_delayed INT UNSIGNED DEFAULT 0,
    patients_t4_expectant INT UNSIGNED DEFAULT 0,
    total_patients INT UNSIGNED NOT NULL DEFAULT 0,
    equipment_needed JSON NULL,
    patients_litter INT UNSIGNED DEFAULT 0,
    patients_ambulatory INT UNSIGNED DEFAULT 0,
    security_status ENUM('NO_ENEMY', 'POSSIBLE_ENEMY', 'ENEMY_IN_AREA', 'ENEMY_TROOPS', 'HOT_LZ') NOT NULL DEFAULT 'NO_ENEMY',
    enemy_description TEXT NULL,
    lz_marking ENUM('NONE', 'PANEL', 'PYRO', 'SMOKE', 'OTHER') DEFAULT 'NONE',
    lz_marking_color VARCHAR(50) NULL,
    lz_marking_details TEXT NULL,
    patient_nationality VARCHAR(100) DEFAULT 'FRIENDLY',
    patient_status ENUM('MILITARY', 'CIVILIAN', 'EPW', 'CHILD') DEFAULT 'MILITARY',
    nbc_contamination ENUM('NONE', 'NUCLEAR', 'BIOLOGICAL', 'CHEMICAL') DEFAULT 'NONE',
    nbc_details TEXT NULL,
    terrain_description TEXT NULL,
    obstacles TEXT NULL,
    approach_direction VARCHAR(100) NULL,
    remarks TEXT NULL,
    requested_by_user_id INT UNSIGNED NULL,
    requested_by_callsign VARCHAR(100) NULL,
    requested_by_unit VARCHAR(100) NULL,
    requested_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status ENUM('REQUESTED', 'ACKNOWLEDGED', 'ASSIGNED', 'INBOUND', 'ON_SITE', 'EVACUATING', 'COMPLETED', 'CANCELLED') DEFAULT 'REQUESTED',
    assigned_asset_callsign VARCHAR(100) NULL,
    assigned_pilot_user_id INT UNSIGNED NULL,
    assigned_at DATETIME NULL,
    acknowledged_at DATETIME NULL,
    eta DATETIME NULL,
    arrived_at DATETIME NULL,
    departed_at DATETIME NULL,
    completed_at DATETIME NULL,
    cancelled_at DATETIME NULL,
    cancellation_reason TEXT NULL,
    golden_hour_expires_at DATETIME NULL,
    is_golden_hour_critical TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_tenant_context (tenant_id, context_id),
    INDEX idx_status (status),
    INDEX idx_priority (priority),
    INDEX idx_requested_at (requested_at),
    INDEX idx_assigned_asset (assigned_asset_callsign),
    INDEX idx_golden_hour (golden_hour_expires_at, patients_t1_urgent)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS atak_medevac_patients (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    medevac_request_id INT UNSIGNED NOT NULL,
    patient_name VARCHAR(200) NULL,
    patient_callsign VARCHAR(100) NULL,
    patient_unit VARCHAR(100) NULL,
    patient_steam_id VARCHAR(50) NULL,
    triage_category ENUM('T1', 'T2', 'T3', 'T4') NOT NULL,
    triage_timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    triaged_by_callsign VARCHAR(100) NULL,
    consciousness ENUM('ALERT', 'VERBAL', 'PAIN', 'UNRESPONSIVE') DEFAULT 'ALERT',
    breathing ENUM('NORMAL', 'ABNORMAL', 'ABSENT') DEFAULT 'NORMAL',
    circulation ENUM('NORMAL', 'COMPROMISED', 'ABSENT') DEFAULT 'NORMAL',
    injuries JSON NULL,
    primary_injury TEXT NULL,
    treatments_given JSON NULL,
    medications_given JSON NULL,
    is_stabilized TINYINT(1) DEFAULT 0,
    stabilized_at DATETIME NULL,
    requires_litter TINYINT(1) DEFAULT 0,
    can_walk TINYINT(1) DEFAULT 0,
    evacuated TINYINT(1) DEFAULT 0,
    evacuated_at DATETIME NULL,
    outcome ENUM('SURVIVED', 'KIA', 'DOW', 'UNKNOWN') NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_medevac_request (medevac_request_id),
    INDEX idx_triage_category (triage_category),
    INDEX idx_patient_steam (patient_steam_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS atak_medevac_status_updates (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    medevac_request_id INT UNSIGNED NOT NULL,
    previous_status VARCHAR(50) NULL,
    new_status VARCHAR(50) NOT NULL,
    update_message TEXT NULL,
    updated_by_callsign VARCHAR(100) NULL,
    updated_by_user_id INT UNSIGNED NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_medevac_request (medevac_request_id),
    INDEX idx_updated_at (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
