-- Suivi véhicules — DDL portable (MariaDB / MySQL partagé)
-- Pas de GENERATED / FK / COMMENT / triggers (gérés côté appli + bootstrap).

CREATE TABLE IF NOT EXISTS atak_vehicle_tracking (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    tenant_id INT UNSIGNED NOT NULL,
    context_id INT UNSIGNED NOT NULL,
    vehicle_callsign VARCHAR(100) NOT NULL,
    vehicle_name VARCHAR(200) NULL,
    vehicle_class ENUM(
        'LIGHT_VEHICLE', 'TRUCK', 'APC', 'IFV', 'TANK', 'ARTILLERY',
        'HELICOPTER', 'FIXED_WING', 'UAV', 'BOAT', 'STATIC', 'OTHER'
    ) NOT NULL,
    vehicle_type VARCHAR(100) NULL,
    side ENUM('BLUFOR', 'OPFOR', 'INDEPENDENT', 'CIVILIAN') DEFAULT 'BLUFOR',
    unit_assigned VARCHAR(200) NULL,
    crew_commander_callsign VARCHAR(100) NULL,
    crew_commander_user_id INT UNSIGNED NULL,
    crew_count INT UNSIGNED DEFAULT 0,
    crew_max INT UNSIGNED NULL,
    passenger_count INT UNSIGNED DEFAULT 0,
    passenger_max INT UNSIGNED NULL,
    passengers_json JSON NULL,
    pos_x DECIMAL(12, 4) NOT NULL,
    pos_y DECIMAL(12, 4) NOT NULL,
    pos_z DECIMAL(12, 4) NULL,
    heading DECIMAL(6, 2) NULL,
    speed DECIMAL(8, 2) NULL,
    status ENUM('OPERATIONAL', 'DAMAGED', 'IMMOBILIZED', 'DESTROYED', 'ABANDONED') DEFAULT 'OPERATIONAL',
    fuel_percent DECIMAL(5, 2) NULL,
    fuel_capacity INT UNSIGNED NULL,
    fuel_consumption_rate DECIMAL(8, 2) NULL,
    ammo_percent DECIMAL(5, 2) NULL,
    weapons JSON NULL,
    engine_health DECIMAL(5, 2) NULL,
    hull_health DECIMAL(5, 2) NULL,
    tracks_wheels_health DECIMAL(5, 2) NULL,
    turret_health DECIMAL(5, 2) NULL,
    is_fuel_critical TINYINT(1) NOT NULL DEFAULT 0,
    is_ammo_critical TINYINT(1) NOT NULL DEFAULT 0,
    is_damaged TINYINT(1) NOT NULL DEFAULT 0,
    destination_pos_x DECIMAL(12, 4) NULL,
    destination_pos_y DECIMAL(12, 4) NULL,
    mission_type ENUM('PATROL', 'TRANSPORT', 'COMBAT', 'SUPPORT', 'LOGISTICS', 'MEDEVAC', 'RECON', 'IDLE') NULL,
    mission_description TEXT NULL,
    properties JSON NULL,
    is_visible TINYINT(1) DEFAULT 1,
    last_seen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    immobilized_since DATETIME NULL,
    destroyed_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_tenant_context (tenant_id, context_id),
    INDEX idx_vehicle_callsign (vehicle_callsign),
    INDEX idx_vehicle_class (vehicle_class),
    INDEX idx_side (side),
    INDEX idx_status (status),
    INDEX idx_position (pos_x, pos_y),
    INDEX idx_last_seen (last_seen_at),
    UNIQUE KEY uk_tenant_context_callsign (tenant_id, context_id, vehicle_callsign)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS atak_vehicle_position_history (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    vehicle_tracking_id INT UNSIGNED NOT NULL,
    pos_x DECIMAL(12, 4) NOT NULL,
    pos_y DECIMAL(12, 4) NOT NULL,
    pos_z DECIMAL(12, 4) NULL,
    heading DECIMAL(6, 2) NULL,
    speed DECIMAL(8, 2) NULL,
    fuel_percent DECIMAL(5, 2) NULL,
    ammo_percent DECIMAL(5, 2) NULL,
    recorded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_vehicle (vehicle_tracking_id),
    INDEX idx_recorded_at (recorded_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS atak_vehicle_events (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    vehicle_tracking_id INT UNSIGNED NOT NULL,
    event_type ENUM(
        'DEPLOYED', 'MOVED', 'STOPPED', 'DAMAGED', 'REPAIRED', 'IMMOBILIZED',
        'DESTROYED', 'ABANDONED', 'RECOVERED', 'REFUELED', 'REARMED',
        'CREW_CHANGED', 'MISSION_ASSIGNED', 'MISSION_COMPLETED'
    ) NOT NULL,
    event_description TEXT NULL,
    event_pos_x DECIMAL(12, 4) NULL,
    event_pos_y DECIMAL(12, 4) NULL,
    actor_callsign VARCHAR(100) NULL,
    actor_user_id INT UNSIGNED NULL,
    event_data JSON NULL,
    event_timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_vehicle (vehicle_tracking_id),
    INDEX idx_event_type (event_type),
    INDEX idx_event_timestamp (event_timestamp)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS atak_vehicle_service_requests (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    vehicle_tracking_id INT UNSIGNED NOT NULL,
    request_type ENUM('REFUEL', 'REARM', 'REPAIR', 'MAINTENANCE', 'RECOVERY') NOT NULL,
    priority ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT') DEFAULT 'MEDIUM',
    request_details TEXT NULL,
    requested_by_callsign VARCHAR(100) NULL,
    requested_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    service_pos_x DECIMAL(12, 4) NULL,
    service_pos_y DECIMAL(12, 4) NULL,
    status ENUM('REQUESTED', 'ACKNOWLEDGED', 'ENROUTE', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED') DEFAULT 'REQUESTED',
    assigned_to_callsign VARCHAR(100) NULL,
    assigned_at DATETIME NULL,
    service_started_at DATETIME NULL,
    service_completed_at DATETIME NULL,
    completion_notes TEXT NULL,
    INDEX idx_vehicle (vehicle_tracking_id),
    INDEX idx_request_type (request_type),
    INDEX idx_status (status),
    INDEX idx_requested_at (requested_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
