-- Parcours d’intégration des nouveaux membres (RH / communauté).
-- Idempotent via bootstrap/member_integration_migration.php.

CREATE TABLE IF NOT EXISTS member_integration_templates (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id INT UNSIGNED NOT NULL,
    name VARCHAR(160) NOT NULL,
    description TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    duration_days INT UNSIGNED NULL,
    auto_rules_json JSON NULL,
    default_referent_user_id INT UNSIGNED NULL,
    referent_rule VARCHAR(32) NOT NULL DEFAULT 'none',
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_mit_tenant_active (tenant_id, is_active),
    CONSTRAINT fk_mit_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_mit_referent FOREIGN KEY (default_referent_user_id) REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_mit_author FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS member_integration_template_steps (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id INT UNSIGNED NOT NULL,
    template_id BIGINT UNSIGNED NOT NULL,
    position INT UNSIGNED NOT NULL DEFAULT 1,
    step_key VARCHAR(64) NOT NULL,
    title VARCHAR(180) NOT NULL,
    description TEXT NULL,
    step_type VARCHAR(40) NOT NULL DEFAULT 'task',
    responsible_kind VARCHAR(32) NOT NULL DEFAULT 'member',
    responsible_role_id INT UNSIGNED NULL,
    due_after_days INT UNSIGNED NULL,
    is_required TINYINT(1) NOT NULL DEFAULT 1,
    is_member_visible TINYINT(1) NOT NULL DEFAULT 1,
    linked_matrix_id INT UNSIGNED NULL,
    linked_course_id INT UNSIGNED NULL,
    linked_document_id INT UNSIGNED NULL,
    configuration_json JSON NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_mits_template_pos (tenant_id, template_id, position),
    UNIQUE KEY uq_mits_template_key (template_id, step_key),
    CONSTRAINT fk_mits_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_mits_template FOREIGN KEY (template_id) REFERENCES member_integration_templates (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS member_integrations (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id INT UNSIGNED NOT NULL,
    user_id INT UNSIGNED NOT NULL,
    template_id BIGINT UNSIGNED NULL,
    template_version INT UNSIGNED NOT NULL DEFAULT 1,
    status VARCHAR(32) NOT NULL DEFAULT 'to_start',
    progress_percent TINYINT UNSIGNED NOT NULL DEFAULT 0,
    primary_referent_user_id INT UNSIGNED NULL,
    current_step_id BIGINT UNSIGNED NULL,
    overdue_count INT UNSIGNED NOT NULL DEFAULT 0,
    dossier_complete TINYINT(1) NOT NULL DEFAULT 0,
    next_appointment_at DATETIME NULL,
    source VARCHAR(32) NOT NULL DEFAULT 'manual',
    started_at DATETIME NULL,
    target_completion_at DATETIME NULL,
    completed_at DATETIME NULL,
    cancelled_at DATETIME NULL,
    created_by INT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    active_user_key INT UNSIGNED GENERATED ALWAYS AS (
        CASE WHEN status IN ('completed', 'cancelled') THEN NULL ELSE user_id END
    ) STORED,
    PRIMARY KEY (id),
    UNIQUE KEY uq_mi_active_user (tenant_id, active_user_key),
    KEY idx_mi_tenant_status (tenant_id, status),
    KEY idx_mi_tenant_user (tenant_id, user_id),
    KEY idx_mi_referent (tenant_id, primary_referent_user_id),
    KEY idx_mi_started (tenant_id, started_at),
    CONSTRAINT fk_mi_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_mi_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_mi_template FOREIGN KEY (template_id) REFERENCES member_integration_templates (id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_mi_referent FOREIGN KEY (primary_referent_user_id) REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_mi_author FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS member_integration_steps (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id INT UNSIGNED NOT NULL,
    integration_id BIGINT UNSIGNED NOT NULL,
    template_step_id BIGINT UNSIGNED NULL,
    step_key VARCHAR(64) NOT NULL,
    position INT UNSIGNED NOT NULL DEFAULT 1,
    title VARCHAR(180) NOT NULL,
    description TEXT NULL,
    step_type VARCHAR(40) NOT NULL DEFAULT 'task',
    responsible_kind VARCHAR(32) NOT NULL DEFAULT 'member',
    responsible_user_id INT UNSIGNED NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    due_at DATETIME NULL,
    is_required TINYINT(1) NOT NULL DEFAULT 1,
    is_member_visible TINYINT(1) NOT NULL DEFAULT 1,
    linked_matrix_id INT UNSIGNED NULL,
    linked_course_id INT UNSIGNED NULL,
    linked_document_id INT UNSIGNED NULL,
    linked_personnel_bilan_id BIGINT UNSIGNED NULL,
    configuration_json JSON NULL,
    started_at DATETIME NULL,
    completed_at DATETIME NULL,
    validated_by INT UNSIGNED NULL,
    force_reason VARCHAR(500) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_mis_integration_pos (tenant_id, integration_id, position),
    KEY idx_mis_status_due (tenant_id, status, due_at),
    CONSTRAINT fk_mis_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_mis_integration FOREIGN KEY (integration_id) REFERENCES member_integrations (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_mis_responsible FOREIGN KEY (responsible_user_id) REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_mis_validator FOREIGN KEY (validated_by) REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS member_integration_referents (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id INT UNSIGNED NOT NULL,
    integration_id BIGINT UNSIGNED NOT NULL,
    user_id INT UNSIGNED NOT NULL,
    is_primary TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_mir_integration_user (integration_id, user_id),
    KEY idx_mir_tenant (tenant_id, user_id),
    CONSTRAINT fk_mir_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_mir_integration FOREIGN KEY (integration_id) REFERENCES member_integrations (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_mir_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS member_integration_events (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id INT UNSIGNED NOT NULL,
    integration_id BIGINT UNSIGNED NOT NULL,
    step_id BIGINT UNSIGNED NULL,
    actor_user_id INT UNSIGNED NULL,
    event_type VARCHAR(64) NOT NULL,
    visibility VARCHAR(16) NOT NULL DEFAULT 'staff',
    message TEXT NULL,
    metadata_json JSON NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_mie_integration (tenant_id, integration_id, created_at),
    KEY idx_mie_visibility (tenant_id, visibility),
    CONSTRAINT fk_mie_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_mie_integration FOREIGN KEY (integration_id) REFERENCES member_integrations (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_mie_step FOREIGN KEY (step_id) REFERENCES member_integration_steps (id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_mie_actor FOREIGN KEY (actor_user_id) REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS member_integration_appointments (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id INT UNSIGNED NOT NULL,
    integration_id BIGINT UNSIGNED NULL,
    step_id BIGINT UNSIGNED NULL,
    title VARCHAR(180) NOT NULL,
    description TEXT NULL,
    event_type VARCHAR(40) NOT NULL DEFAULT 'custom',
    starts_at DATETIME NOT NULL,
    ends_at DATETIME NOT NULL,
    timezone VARCHAR(64) NOT NULL DEFAULT 'UTC',
    location VARCHAR(255) NULL,
    meeting_url VARCHAR(500) NULL,
    organizer_user_id INT UNSIGNED NULL,
    max_attendees INT UNSIGNED NULL,
    linked_course_id INT UNSIGNED NULL,
    linked_training_session_id INT UNSIGNED NULL,
    ics_uid VARCHAR(180) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'scheduled',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_mia_ics (ics_uid),
    KEY idx_mia_tenant_start (tenant_id, starts_at),
    KEY idx_mia_integration (tenant_id, integration_id),
    CONSTRAINT fk_mia_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_mia_integration FOREIGN KEY (integration_id) REFERENCES member_integrations (id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_mia_step FOREIGN KEY (step_id) REFERENCES member_integration_steps (id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_mia_organizer FOREIGN KEY (organizer_user_id) REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS member_integration_invitations (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id INT UNSIGNED NOT NULL,
    appointment_id BIGINT UNSIGNED NOT NULL,
    user_id INT UNSIGNED NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    response_token_hash CHAR(64) NOT NULL,
    token_expires_at DATETIME NOT NULL,
    revoked_at DATETIME NULL,
    personal_message TEXT NULL,
    response_comment VARCHAR(500) NULL,
    invited_by INT UNSIGNED NULL,
    invited_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    responded_at DATETIME NULL,
    email_sent_at DATETIME NULL,
    reminded_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_mii_appointment_user (appointment_id, user_id),
    UNIQUE KEY uq_mii_token (response_token_hash),
    KEY idx_mii_tenant_user (tenant_id, user_id, status),
    CONSTRAINT fk_mii_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_mii_appointment FOREIGN KEY (appointment_id) REFERENCES member_integration_appointments (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_mii_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_mii_inviter FOREIGN KEY (invited_by) REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS member_integration_invitation_history (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id INT UNSIGNED NOT NULL,
    invitation_id BIGINT UNSIGNED NOT NULL,
    actor_user_id INT UNSIGNED NULL,
    from_status VARCHAR(32) NULL,
    to_status VARCHAR(32) NOT NULL,
    comment VARCHAR(500) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_miih_invitation (invitation_id, created_at),
    KEY idx_miih_tenant (tenant_id, created_at),
    CONSTRAINT fk_miih_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_miih_invitation FOREIGN KEY (invitation_id) REFERENCES member_integration_invitations (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_miih_actor FOREIGN KEY (actor_user_id) REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
