params ["_page"]; disableSerialization; private _d=findDisplay 88500; if (isNull _d) exitWith {false};
private _map=_d displayCtrl 88530; private _group=_d displayCtrl 88531; {ctrlDelete _x} forEach (uiNamespace getVariable ["COMSPEC_ATAK_PageControls",[]]); uiNamespace setVariable ["COMSPEC_ATAK_PageControls",[]];
private _native=_page isEqualTo "MAP"; _map ctrlShow _native; _group ctrlShow !_native; if (_native) exitWith {[] call comspec_atak_native_fnc_inspectorUpdate; true};
private _made=[]; private _new={params ["_class","_idc","_pos",["_text",""]]; private _c=_d ctrlCreate [_class,_idc,_group]; _c ctrlSetPosition _pos; _c ctrlSetText _text; _c ctrlCommit 0; _made pushBack _c; _c};
private _title=["COMSPEC_RscText",88700,[0.015,0.012,0.60,0.055],_page] call _new; _title ctrlSetTextColor [0.36,0.78,0.42,1];
private _data=uiNamespace getVariable ["COMSPEC_ATAK_Data",createHashMap]; private _body="";
switch _page do {
 case "HOME": { _body=format ["OPÉRATEUR\n%1  |  %2\n\nMISSION\n%3  |  %4\nPosition %5\n\nATHENA\n%6\n\nACCÈS RAPIDES\nMAP  ·  TASK  ·  CHAT  ·  SSE  ·  BRIEFING",name player,groupId group player,worldName,daytime,mapGridPosition player,(uiNamespace getVariable ["COMSPEC_ATAK_State",createHashMap]) getOrDefault ["networkState","OFFLINE"]]; };
 case "C2": { _body=format ["SITUATION C2\n\nUnités suivies : %1\nOrdres : %2\nMarqueurs : %3\n\nLa carte native reste la vue opérationnelle principale.",count (_data getOrDefault ["units",createHashMap]),count (_data getOrDefault ["tasks",createHashMap]),count (_data getOrDefault ["markers",createHashMap])]; };
 case "BFT": { private _lines=["BLUE FORCE TRACKING",""]; {private _u=_y; private _obj=_u getOrDefault ["object",objNull]; private _grid=if (isNull _obj) then {"------"} else {mapGridPosition _obj}; _lines pushBack format ["%1  |  %2  |  %3",_u getOrDefault ["callsign",_x],_u getOrDefault ["freshness","LIVE"],_grid];} forEach (_data getOrDefault ["units",createHashMap]); _body=_lines joinString "\n"; };
 case "CHAT": { private _lines=["MESSAGERIE ATHENA",""]; {_lines pushBack format ["[%1] %2: %3",_x getOrDefault ["time","--:--"],_x getOrDefault ["author","SYSTEM"],_x getOrDefault ["body",""]];} forEach (_data getOrDefault ["messages",[]]); _body=_lines joinString "\n"; private _edit=["COMSPEC_RscEdit",88720,[0.015,0.76,0.70,0.055],""] call _new; uiNamespace setVariable ["COMSPEC_ATAK_ChatEdit",_edit]; private _send=["COMSPEC_RscButton",88721,[0.73,0.76,0.20,0.055],"ENVOYER"] call _new; _send ctrlAddEventHandler ["ButtonClick",{[] call comspec_atak_native_fnc_chatSend;}]; };
 case "TASK": { private _lines=["ORDRES / TASK",""]; {private _t=_y; _lines pushBack format ["[%1] %2 — %3\n%4",_t getOrDefault ["priority","NORMAL"],_t getOrDefault ["type","ORDER"],_t getOrDefault ["status","PENDING"],_t getOrDefault ["payload",""]];} forEach (_data getOrDefault ["tasks",createHashMap]); _body=_lines joinString "\n"; {private _status=_x select 0; private _b=["COMSPEC_RscButton",88730+_forEachIndex,[0.015+_forEachIndex*0.18,0.76,0.17,0.055],_x select 1] call _new; _b setVariable ["status",_status]; _b ctrlAddEventHandler ["ButtonClick",{params ["_c"];[_c getVariable "status"] call comspec_atak_native_fnc_taskAction;}];} forEach [["ACK","REÇU"],["EXEC","EN COURS"],["DELIVERED","TERMINÉ"],["FAILED","IMPOSSIBLE"]]; };
 case "SSE": { _body=format ["SSE / EXPLOITATION\n\nEntrées renseignement : %1\n\nPersonnes · objets · sites · documents · biométrie\nLes données COMSPEC SSE présentes sont agrégées sans imposer son interface.",count (_data getOrDefault ["intel",createHashMap])]; };
 case "INTEL": { _body="RENSEIGNEMENT\n\nVue compacte des signalements, sources, dates et niveaux de confiance.\nSélectionnez un contact sur la carte pour l'inspecter."; };
 case "BDA": { _body="BATTLE DAMAGE ASSESSMENT\n\nLes événements BDA Athena/Iceman importés apparaissent ici et sur la carte."; };
 case "BRIEFING": {private _b=_data getOrDefault ["briefing",createHashMap]; _body=format ["BRIEFING NATIF\n\nPage %1 / %2\n%3",(_b getOrDefault ["index",0])+1,_b getOrDefault ["total",0],if ((_b getOrDefault ["path",""]) isEqualTo "") then {"Aucune image locale disponible."} else {_b get "path"}]; private _prev=["COMSPEC_RscButton",88740,[0.015,0.76,0.20,0.055],"PRÉCÉDENT"] call _new; _prev ctrlAddEventHandler ["ButtonClick",{[-1] call comspec_atak_native_fnc_briefingStep;}]; private _next=["COMSPEC_RscButton",88741,[0.73,0.76,0.20,0.055],"SUIVANT"] call _new; _next ctrlAddEventHandler ["ButtonClick",{[1] call comspec_atak_native_fnc_briefingStep;}]; };
 case "PHOTOS": {private _lines=["PHOTOS / RECON",""]; {_lines pushBack format ["%1  —  %2",_x getOrDefault ["name","Capture"],_x getOrDefault ["path","format non affichable"]];} forEach (_data getOrDefault ["photos",[]]); _body=_lines joinString "\n";};
 case "SETTINGS": {_body=format ["PARAMÈTRES\n\nDétail carte : %1\nLabels : %2\nTrails : %3\nNotifications : %4\nBFT refresh : %5 s\nDebug : %6\n\nLa persistance utilise profileNamespace.",profileNamespace getVariable ["COMSPEC_ATAK_MapDetail",2],profileNamespace getVariable ["COMSPEC_ATAK_Labels",true],profileNamespace getVariable ["COMSPEC_ATAK_Trails",true],profileNamespace getVariable ["COMSPEC_ATAK_Notifications",true],profileNamespace getVariable ["COMSPEC_ATAK_BftRefresh",3],profileNamespace getVariable ["COMSPEC_ATAK_Debug",false]];};
 case "STATUS": {private _s=uiNamespace getVariable ["COMSPEC_ATAK_State",createHashMap]; _body=format ["STATUT SYSTÈME\n\nATHENA  %1\nEXT  %2\nMOD  1.0.0\nLAST SYNC  %3\nBACKOFF  %4 s\nUI  native-rsc-v1\n\nLe terminal et la carte restent disponibles hors ligne.",_s getOrDefault ["networkState","OFFLINE"],missionNamespace getVariable ["COMSPEC_ExtensionVersion","unknown"],_data getOrDefault ["lastNetworkUpdate",-1],missionNamespace getVariable ["COMSPEC_SendBackoffSec",0]];};
};
private _text=["COMSPEC_RscStructuredText",88701,[0.015,0.080,0.92,0.65],""] call _new; _text ctrlSetStructuredText parseText ((_body splitString "\n") joinString "<br/>"); uiNamespace setVariable ["COMSPEC_ATAK_PageControls",_made]; true
