<?php

declare(strict_types=1);

use App\Controllers\Web\HomeController;
use App\Controllers\Web\HubController;
use App\Controllers\Web\PersonnelController;
use App\Controllers\Web\EnlistmentController;
use App\Controllers\Web\DocumentsController;
use App\Controllers\Web\EquipmentController;
use App\Controllers\Web\TrainingController;
use App\Controllers\Web\AtakController;
use App\Controllers\Web\AccountController;
use App\Controllers\Web\ModpackController;
use App\Controllers\Web\ForumController;
use App\Controllers\Web\ForumCategoryController;
use App\Controllers\Web\ForumTopicController;
use App\Controllers\Web\ForumNewTopicController;
use App\Controllers\Web\ForumModerationController;
use App\Controllers\Web\ExternalLeaveController;
use App\Controllers\Web\ForumModerationDashboardController;
use App\Controllers\Web\ContentModerationController;
use App\Controllers\Api\ForumApiController;
use App\Controllers\Api\ForumModerationApiController;
use App\Controllers\Api\ForumUploadController;
use App\Controllers\Api\ForumRestController;
use App\Controllers\Api\AtakIntelController;
use App\Controllers\Api\AtakApiController;
use App\Controllers\Api\FireSupportController;
use App\Controllers\Api\DangerZoneController;
use App\Controllers\Api\LogisticsController;
use App\Controllers\Api\IntelController;
use App\Controllers\Api\ReplayController;
use App\Controllers\Api\IffController;
use App\Controllers\Api\HealthController;
use App\Controllers\Api\StripeWebhookController;
use App\Controllers\Web\CommunityController;
use App\Controllers\Admin\AdminDashboardController;
use App\Controllers\Admin\AdminUsersController;
use App\Controllers\Admin\AdminUnitsController;
use App\Controllers\Admin\AdminModpackController;
use App\Controllers\Admin\AdminAtakConfigController;
use App\Controllers\Admin\AdminAtakModController;
use App\Controllers\Admin\AdminConfigurationController;
use App\Controllers\Admin\AdminRecruitmentsController;
use App\Controllers\Admin\AdminDocumentsController;
use App\Controllers\Admin\AdminTrainingController;
use App\Controllers\Courrier\CourrierDashboardController;
use App\Controllers\Courrier\CourrierEditorController;
use App\Controllers\Courrier\CourrierTemplateController;
use App\Controllers\Courrier\CourrierPresetController;
use App\Controllers\Courrier\CourrierWorkflowController;
use App\Controllers\Courrier\CourrierPdfController;
use App\Controllers\Courrier\CourrierSnippetController;
use App\Controllers\Courrier\CourrierSignatureController;
use App\Controllers\Courrier\CourrierNotificationController;
use App\Controllers\Admin\System\SystemDashboardController;
use App\Controllers\Admin\System\SystemRoleController;
use App\Controllers\Admin\System\SystemSettingsController;
use App\Controllers\Admin\System\SystemPlatformAlertsController;
use App\Controllers\Admin\Organization\TenantAlertsController;
use App\Controllers\Api\AlertDismissController;
use App\Controllers\Api\MePreferencesApiController;
use App\Controllers\Admin\System\SystemAuditController;
use App\Controllers\Admin\System\SystemSiteRoleAssignmentController;
use App\Controllers\Admin\System\SystemMaintenanceController;
use App\Controllers\Admin\Organization\OrganizationDashboardController;
use App\Controllers\Admin\Organization\OrganizationAuditController;
use App\Controllers\Admin\Organization\OrganizationPlaceholderController;
use App\Controllers\Admin\Organization\UserAdminController;
use App\Controllers\Admin\Organization\RoleAdminController;
use App\Controllers\Admin\Organization\CategoryAdminController;
use App\Controllers\Admin\Organization\GradeReferentielController;
use App\Controllers\Admin\Organization\GroupAdminController;
use App\Controllers\Admin\Organization\TeamAdminController;
use App\Controllers\Auth\AuthController;
use App\Controllers\Web\RegisterController;
use App\Controllers\Web\JoinController;
use App\Controllers\Web\ReferralInviteController;
use App\Controllers\Web\InvitationAcceptController;
use App\Controllers\Web\CommunityEventsController;
use App\Controllers\Web\PortalSearchController;
use App\Controllers\Web\TenantMessagesController;
use App\Controllers\Admin\Organization\InvitationAdminController;
use App\Controllers\Admin\Organization\ModerationOrganizationController;
use App\Controllers\Admin\Organization\OrganizationAnalyticsController;
use App\Controllers\Admin\Organization\OrganizationCommunityController;
use App\Controllers\Admin\Organization\CommunityEventsAdminController;
use App\Controllers\Api\TrainingApiController;
use App\Core\Router;
use App\Middleware\AuthMiddleware;
use App\Middleware\GuestMiddleware;
use App\Middleware\ForumModerateMiddleware;
use App\Middleware\SystemAdminMiddleware;
use App\Middleware\OrganizationAdminMiddleware;
use App\Middleware\NonDefaultTenantMiddleware;
use App\Middleware\TenantResourceAdminMiddleware;
use App\Middleware\InvitationSenderMiddleware;
use App\Middleware\ForumModerationConsoleMiddleware;
use App\Controllers\Web\VerifyEmailController;
use App\Controllers\Web\SecurityDeviceController;

return function (Router $router) {
    $router->get('/', [HomeController::class, 'index']);
    // Communautés multi-tenant (slug) + Stripe (sans auth)
    $router->get('/c/{slug}', [CommunityController::class, 'show']);
    $router->post('/c/{slug}/contact', [CommunityController::class, 'contactPublic']);
    $router->get('/c/{slug}/forum', [CommunityController::class, 'enterForum'], [AuthMiddleware::class]);
    $router->get('/c/{slug}/enlistment/enter', [CommunityController::class, 'enterEnlistment'], [AuthMiddleware::class]);
    $router->get('/c/{slug}/setup', [CommunityController::class, 'setupForm'], [AuthMiddleware::class]);
    $router->post('/c/{slug}/setup', [CommunityController::class, 'setupStore'], [AuthMiddleware::class]);
    $router->get('/communities/create', [CommunityController::class, 'createForm'], [AuthMiddleware::class]);
    $router->post('/communities/create', [CommunityController::class, 'create'], [AuthMiddleware::class]);
    $router->get('/communities/create/preview', [CommunityController::class, 'createPreview'], [AuthMiddleware::class]);
    $router->post('/communities/create/preview', [CommunityController::class, 'createPreview'], [AuthMiddleware::class]);
    $router->get('/communities/create/pay', [CommunityController::class, 'pay'], [AuthMiddleware::class]);
    $router->get('/communities/create/complete', [CommunityController::class, 'createComplete'], [AuthMiddleware::class]);
    $router->get('/communities', [CommunityController::class, 'registry'], [AuthMiddleware::class]);
    $router->post('/community/switch', [CommunityController::class, 'switchTenant'], [AuthMiddleware::class]);
    $router->post('/api/stripe/webhook', [StripeWebhookController::class, 'handle']);
    $router->get('/register', [RegisterController::class, 'show'], [GuestMiddleware::class]);
    $router->post('/register', [RegisterController::class, 'store'], [GuestMiddleware::class]);
    $router->get('/register/check-email', [VerifyEmailController::class, 'showCheckEmail'], [GuestMiddleware::class]);
    $router->get('/verify-email', [VerifyEmailController::class, 'verify'], [GuestMiddleware::class]);
    $router->get('/security/device-deny', [SecurityDeviceController::class, 'denyDevice'], [GuestMiddleware::class]);
    $router->get('/join', [JoinController::class, 'show']);
    $router->post('/community/resolve-code', [JoinController::class, 'resolve']);
    $router->get('/platform/upgrade', [HomeController::class, 'platformUpgrade'], [AuthMiddleware::class]);
    $router->get('/platform/invite-unit', [ReferralInviteController::class, 'index'], [AuthMiddleware::class]);
    $router->get('/invitations/accept', [InvitationAcceptController::class, 'show']);
    $router->post('/invitations/accept', [InvitationAcceptController::class, 'accept']);
    $router->get('/login', [AuthController::class, 'showLogin'], [GuestMiddleware::class]);
    $router->post('/login', [AuthController::class, 'login'], [GuestMiddleware::class]);
    $router->get('/login/select-community', [AuthController::class, 'showSelectCommunity'], [GuestMiddleware::class]);
    $router->post('/login/select-community', [AuthController::class, 'selectCommunity'], [GuestMiddleware::class]);
    $router->post('/logout', [AuthController::class, 'logout']);
    $router->get('/forgot-password', [AuthController::class, 'showForgotPassword'], [GuestMiddleware::class]);
    $router->post('/forgot-password', [AuthController::class, 'sendResetLink'], [GuestMiddleware::class]);
    $router->get('/reset-password', [AuthController::class, 'showResetPassword'], [GuestMiddleware::class]);
    $router->post('/reset-password', [AuthController::class, 'processResetPassword'], [GuestMiddleware::class]);
    $router->get('/evenements', [CommunityEventsController::class, 'index'], [AuthMiddleware::class]);
    $router->post('/evenements/rsvp', [CommunityEventsController::class, 'rsvp'], [AuthMiddleware::class]);
    $router->get('/dashboard', [HomeController::class, 'dashboard'], [AuthMiddleware::class]);
    $router->get('/messages', [TenantMessagesController::class, 'index'], [AuthMiddleware::class]);
    $router->post('/messages', [TenantMessagesController::class, 'create'], [AuthMiddleware::class]);
    $router->get('/messages/{id}', [TenantMessagesController::class, 'show'], [AuthMiddleware::class]);
    $router->post('/messages/{id}/reply', [TenantMessagesController::class, 'reply'], [AuthMiddleware::class]);
    $router->get('/search', [PortalSearchController::class, 'index'], [AuthMiddleware::class]);
    $router->get('/hub', [HubController::class, 'index'], [AuthMiddleware::class]);
    $router->get('/account', [AccountController::class, 'index'], [AuthMiddleware::class]);
    $router->get('/account/preferences', [AccountController::class, 'preferences'], [AuthMiddleware::class]);
    $router->post('/account/preferences', [AccountController::class, 'preferences'], [AuthMiddleware::class]);
    $router->get('/account/mail', [AccountController::class, 'mail'], [AuthMiddleware::class]);
    $router->post('/account/mail', [AccountController::class, 'mail'], [AuthMiddleware::class]);
    $router->get('/account/image', [AccountController::class, 'image'], [AuthMiddleware::class]);
    $router->post('/account/image', [AccountController::class, 'image'], [AuthMiddleware::class]);
    $router->get('/account/portrait', [AccountController::class, 'portrait'], [AuthMiddleware::class]);
    $router->post('/account/portrait', [AccountController::class, 'portrait'], [AuthMiddleware::class]);
    $router->get('/account/password', [AccountController::class, 'password'], [AuthMiddleware::class]);
    $router->post('/account/password', [AccountController::class, 'password'], [AuthMiddleware::class]);
    $router->get('/account/recruitment-presets', [AccountController::class, 'recruitmentPresets'], [AuthMiddleware::class]);
    $router->get('/account/recruitment-presets/create', [AccountController::class, 'recruitmentPresetsCreate'], [AuthMiddleware::class]);
    $router->post('/account/recruitment-presets/create', [AccountController::class, 'recruitmentPresetsCreate'], [AuthMiddleware::class]);
    $router->get('/account/recruitment-presets/{id}/edit', [AccountController::class, 'recruitmentPresetsEdit'], [AuthMiddleware::class]);
    $router->post('/account/recruitment-presets/{id}/edit', [AccountController::class, 'recruitmentPresetsEdit'], [AuthMiddleware::class]);
    $router->post('/account/recruitment-presets/{id}/delete', [AccountController::class, 'recruitmentPresetsDelete'], [AuthMiddleware::class]);
    $router->get('/personnel/me', [PersonnelController::class, 'me'], [AuthMiddleware::class]);
    $router->get('/personnel/me/edit', [PersonnelController::class, 'edit'], [AuthMiddleware::class]);
    $router->get('/personnel/{id}', [PersonnelController::class, 'show'], [AuthMiddleware::class]);
    $router->get('/personnel/{id}/edit', [PersonnelController::class, 'edit'], [AuthMiddleware::class]);
    $router->post('/personnel/{id}/update', [PersonnelController::class, 'update'], [AuthMiddleware::class]);
    $router->post('/personnel/{id}/generate-matricule', [PersonnelController::class, 'generateMatricule'], [AuthMiddleware::class]);
    $router->post('/personnel/{id}/notes', [PersonnelController::class, 'updateNotes'], [AuthMiddleware::class]);
    $router->get('/orbat', [PersonnelController::class, 'orbat'], [AuthMiddleware::class]);
    $router->get('/enlistment', [EnlistmentController::class, 'show']);
    $router->post('/enlistment', [EnlistmentController::class, 'store']);
    $router->get('/c/{slug}/enlistment', [EnlistmentController::class, 'show']);
    $router->post('/c/{slug}/enlistment', [EnlistmentController::class, 'store']);
    $router->get('/enlistment/success', [EnlistmentController::class, 'success']);
    $router->get('/enlistment/error', [EnlistmentController::class, 'error']);
    $router->get('/recrutement', [HomeController::class, 'recrutement']);
    $router->get('/equipement', [HomeController::class, 'equipement']);
    $router->get('/documents', [DocumentsController::class, 'index'], [AuthMiddleware::class]);
    // Gestion documentaire (liste, détail, édition, historique, accès, arborescence) — accès par permissions documents.*
    $router->get('/documents/gestion', [AdminDocumentsController::class, 'index'], [AuthMiddleware::class]);
    $router->get('/documents/gestion/ajout', [AdminDocumentsController::class, 'uploadForm'], [AuthMiddleware::class]);
    $router->post('/documents/gestion/ajout', [AdminDocumentsController::class, 'upload'], [AuthMiddleware::class]);
    $router->get('/documents/gestion/arborescence', [AdminDocumentsController::class, 'tree'], [AuthMiddleware::class]);
    $router->get('/documents/gestion/{id}', [AdminDocumentsController::class, 'show'], [AuthMiddleware::class]);
    $router->get('/documents/gestion/{id}/modifier', [AdminDocumentsController::class, 'edit'], [AuthMiddleware::class]);
    $router->post('/documents/gestion/{id}/modifier', [AdminDocumentsController::class, 'update'], [AuthMiddleware::class]);
    $router->post('/documents/gestion/{id}/nouvelle-version', [AdminDocumentsController::class, 'newVersion'], [AuthMiddleware::class]);
    $router->post('/documents/gestion/{id}/archiver', [AdminDocumentsController::class, 'archive'], [AuthMiddleware::class]);
    $router->get('/documents/gestion/{id}/historique', [AdminDocumentsController::class, 'history'], [AuthMiddleware::class]);
    $router->get('/documents/gestion/{id}/acces', [AdminDocumentsController::class, 'access'], [AuthMiddleware::class]);
    $router->get('/documents/{id}/file', [DocumentsController::class, 'file'], [AuthMiddleware::class]);
    $router->get('/documents/{id}/download', [DocumentsController::class, 'download'], [AuthMiddleware::class]);
    $router->get('/documents/{slug}', [DocumentsController::class, 'show'], [AuthMiddleware::class]);
    $router->get('/equipment', [EquipmentController::class, 'index'], [AuthMiddleware::class]);
    $router->get('/equipment/{slug}', [EquipmentController::class, 'show'], [AuthMiddleware::class]);
    $router->get('/modpacks', [ModpackController::class, 'index'], [AuthMiddleware::class]);
    $router->get('/modpacks/images/{id}', [ModpackController::class, 'image'], [AuthMiddleware::class]);
    $router->get('/modpacks/{id}/download', [ModpackController::class, 'download'], [AuthMiddleware::class]);
    $router->get('/modpacks/{slug}', [ModpackController::class, 'show'], [AuthMiddleware::class]);
    $router->get('/formations', [TrainingController::class, 'index'], [AuthMiddleware::class]);
    $router->get('/formations/mes-formations', [TrainingController::class, 'myTraining'], [AuthMiddleware::class]);
    $router->get('/formations/lesson/{id}', [TrainingController::class, 'lesson'], [AuthMiddleware::class]);
    $router->get('/formations/quiz/{id}', [TrainingController::class, 'quiz'], [AuthMiddleware::class]);
    $router->get('/formations/certificate/{id}', [TrainingController::class, 'certificate'], [AuthMiddleware::class]);
    $router->get('/formations/{slug}', [TrainingController::class, 'showBySlug'], [AuthMiddleware::class]);
    $router->get('/atak', [AtakController::class, 'index'], [AuthMiddleware::class]);
    $router->get('/atak/setup', [AtakController::class, 'setup'], [AuthMiddleware::class]);
    $router->get('/atak/mod/download', [AtakController::class, 'downloadMod'], [AuthMiddleware::class]);
    $router->get('/atak/tuto', [AtakController::class, 'tuto'], [AuthMiddleware::class]);
    $router->get('/tacmap', [HomeController::class, 'tacmap'], [AuthMiddleware::class]);
    $router->get('/overwatch', [HomeController::class, 'overwatch'], [AuthMiddleware::class]);
    // Administration plateforme (super-admin) — préfixe /admin
    $router->get('/admin/roles', [SystemRoleController::class, 'index'], [AuthMiddleware::class, SystemAdminMiddleware::class]);
    $router->get('/admin/roles/{id}', [SystemRoleController::class, 'show'], [AuthMiddleware::class, SystemAdminMiddleware::class]);
    $router->get('/admin/roles/{id}/edit', [SystemRoleController::class, 'edit'], [AuthMiddleware::class, SystemAdminMiddleware::class]);
    $router->post('/admin/roles/{id}/update', [SystemRoleController::class, 'update'], [AuthMiddleware::class, SystemAdminMiddleware::class]);
    $router->get('/admin/settings', [SystemSettingsController::class, 'index'], [AuthMiddleware::class, SystemAdminMiddleware::class]);
    $router->get('/admin/system/alerts/create', [SystemPlatformAlertsController::class, 'create'], [AuthMiddleware::class, SystemAdminMiddleware::class]);
    $router->post('/admin/system/alerts', [SystemPlatformAlertsController::class, 'store'], [AuthMiddleware::class, SystemAdminMiddleware::class]);
    $router->get('/admin/system/alerts/{id}/edit', [SystemPlatformAlertsController::class, 'edit'], [AuthMiddleware::class, SystemAdminMiddleware::class]);
    $router->post('/admin/system/alerts/{id}/update', [SystemPlatformAlertsController::class, 'update'], [AuthMiddleware::class, SystemAdminMiddleware::class]);
    $router->post('/admin/system/alerts/{id}/delete', [SystemPlatformAlertsController::class, 'delete'], [AuthMiddleware::class, SystemAdminMiddleware::class]);
    $router->get('/admin/system/alerts', [SystemPlatformAlertsController::class, 'index'], [AuthMiddleware::class, SystemAdminMiddleware::class]);
    $router->get('/admin/audit', [SystemAuditController::class, 'index'], [AuthMiddleware::class, SystemAdminMiddleware::class]);
    $router->get('/admin/maintenance/create', [SystemMaintenanceController::class, 'create'], [AuthMiddleware::class, SystemAdminMiddleware::class]);
    $router->post('/admin/maintenance', [SystemMaintenanceController::class, 'store'], [AuthMiddleware::class, SystemAdminMiddleware::class]);
    $router->get('/admin/maintenance/{id}/audit', [SystemMaintenanceController::class, 'audit'], [AuthMiddleware::class, SystemAdminMiddleware::class]);
    $router->get('/admin/maintenance/{id}/edit', [SystemMaintenanceController::class, 'edit'], [AuthMiddleware::class, SystemAdminMiddleware::class]);
    $router->post('/admin/maintenance/{id}/update', [SystemMaintenanceController::class, 'update'], [AuthMiddleware::class, SystemAdminMiddleware::class]);
    $router->post('/admin/maintenance/{id}/delete', [SystemMaintenanceController::class, 'delete'], [AuthMiddleware::class, SystemAdminMiddleware::class]);
    $router->post('/admin/maintenance/{id}/toggle', [SystemMaintenanceController::class, 'toggle'], [AuthMiddleware::class, SystemAdminMiddleware::class]);
    $router->get('/admin/maintenance', [SystemMaintenanceController::class, 'index'], [AuthMiddleware::class, SystemAdminMiddleware::class]);
    $router->get('/admin/site-roles', [SystemSiteRoleAssignmentController::class, 'index'], [AuthMiddleware::class, SystemAdminMiddleware::class]);
    $router->post('/admin/site-roles/assign', [SystemSiteRoleAssignmentController::class, 'assign'], [AuthMiddleware::class, SystemAdminMiddleware::class]);
    $router->post('/admin/site-roles/revoke', [SystemSiteRoleAssignmentController::class, 'revoke'], [AuthMiddleware::class, SystemAdminMiddleware::class]);
    $router->get('/admin', [SystemDashboardController::class, 'index'], [AuthMiddleware::class, SystemAdminMiddleware::class]);
    // Back-office communauté (tenant) — préfixe /back-office
    $router->get('/back-office', [OrganizationDashboardController::class, 'index'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->get('/back-office/community', [OrganizationCommunityController::class, 'settings'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->post('/back-office/community', [OrganizationCommunityController::class, 'settingsUpdate'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->get('/back-office/community/presentation', [OrganizationCommunityController::class, 'presentation'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->post('/back-office/community/presentation', [OrganizationCommunityController::class, 'presentationUpdate'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->get('/back-office/onboarding-recovery', [OrganizationCommunityController::class, 'onboardingRecovery'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->post('/back-office/onboarding-recovery/apply', [OrganizationCommunityController::class, 'onboardingRecoveryApply'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->get('/back-office/users', [UserAdminController::class, 'index'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->get('/back-office/users/create', [UserAdminController::class, 'create'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->post('/back-office/users/store', [UserAdminController::class, 'store'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->get('/back-office/users/{id}', [UserAdminController::class, 'show'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->get('/back-office/users/{id}/edit', [UserAdminController::class, 'edit'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->post('/back-office/users/{id}/update', [UserAdminController::class, 'update'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->post('/back-office/users/{id}/deactivate', [UserAdminController::class, 'deactivate'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->get('/back-office/invitations', [InvitationAdminController::class, 'index'], [AuthMiddleware::class, InvitationSenderMiddleware::class]);
    $router->post('/back-office/invitations', [InvitationAdminController::class, 'store'], [AuthMiddleware::class, InvitationSenderMiddleware::class]);
    $router->post('/back-office/invitations/revoke', [InvitationAdminController::class, 'revoke'], [AuthMiddleware::class, InvitationSenderMiddleware::class]);
    $router->get('/back-office/moderation', [ModerationOrganizationController::class, 'index'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->get('/back-office/audit', [OrganizationAuditController::class, 'index'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->post('/back-office/moderation/apply', [ModerationOrganizationController::class, 'apply'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->post('/back-office/moderation/revoke', [ModerationOrganizationController::class, 'revoke'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->get('/back-office/analytics', [OrganizationAnalyticsController::class, 'index'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->get('/back-office/events', [CommunityEventsAdminController::class, 'index'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->post('/back-office/events', [CommunityEventsAdminController::class, 'store'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->get('/back-office/roles', [RoleAdminController::class, 'index'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->get('/back-office/roles/{id}', [RoleAdminController::class, 'show'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->get('/back-office/categories', [CategoryAdminController::class, 'index'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->get('/back-office/categories/create', [CategoryAdminController::class, 'create'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->post('/back-office/categories/store', [CategoryAdminController::class, 'store'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->get('/back-office/categories/{id}/edit', [CategoryAdminController::class, 'edit'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->post('/back-office/categories/{id}/update', [CategoryAdminController::class, 'update'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->get('/back-office/referentiels/grades', [GradeReferentielController::class, 'index'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->get('/back-office/referentiels/grades/create', [GradeReferentielController::class, 'create'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->post('/back-office/referentiels/grades/store', [GradeReferentielController::class, 'store'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->get('/back-office/referentiels/grades/{id}/edit', [GradeReferentielController::class, 'edit'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->post('/back-office/referentiels/grades/{id}/update', [GradeReferentielController::class, 'update'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->post('/back-office/referentiels/grades/{id}/deactivate', [GradeReferentielController::class, 'deactivate'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->get('/back-office/groups', [GroupAdminController::class, 'index'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->get('/back-office/groups/create', [GroupAdminController::class, 'create'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->post('/back-office/groups/store', [GroupAdminController::class, 'store'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->get('/back-office/groups/{id}', [GroupAdminController::class, 'show'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->get('/back-office/groups/{id}/edit', [GroupAdminController::class, 'edit'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->post('/back-office/groups/{id}/update', [GroupAdminController::class, 'update'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->post('/back-office/groups/{id}/delete', [GroupAdminController::class, 'delete'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->get('/back-office/teams', [TeamAdminController::class, 'index'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->get('/back-office/teams/create', [TeamAdminController::class, 'create'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->post('/back-office/teams/store', [TeamAdminController::class, 'store'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->get('/back-office/teams/{id}', [TeamAdminController::class, 'show'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->get('/back-office/teams/{id}/edit', [TeamAdminController::class, 'edit'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->post('/back-office/teams/{id}/update', [TeamAdminController::class, 'update'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->post('/back-office/teams/{id}/delete', [TeamAdminController::class, 'delete'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->get('/back-office/configuration', [AdminConfigurationController::class, 'index'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->get('/back-office/alerts/create', [TenantAlertsController::class, 'create'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->post('/back-office/alerts', [TenantAlertsController::class, 'store'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->get('/back-office/alerts/{id}/edit', [TenantAlertsController::class, 'edit'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->post('/back-office/alerts/{id}/update', [TenantAlertsController::class, 'update'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->post('/back-office/alerts/{id}/delete', [TenantAlertsController::class, 'delete'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->get('/back-office/alerts', [TenantAlertsController::class, 'index'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->get('/back-office/recruitments', [AdminRecruitmentsController::class, 'index'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    $router->get('/back-office/recruitments/{id}', [AdminRecruitmentsController::class, 'show'], [AuthMiddleware::class, OrganizationAdminMiddleware::class]);
    // Anciennes URL — redirections
    $router->get('/admin/system', fn (\App\Core\Request $r, array $p) => \App\Core\Response::redirect(url('admin')), [AuthMiddleware::class]);
    $router->get('/admin/organization', fn (\App\Core\Request $r, array $p) => \App\Core\Response::redirect(url('back-office')), [AuthMiddleware::class]);
    $router->get('/admin/configuration', fn (\App\Core\Request $r, array $p) => \App\Core\Response::redirect(url('back-office/configuration')), [AuthMiddleware::class]);
    $router->get('/admin/recruitments', fn (\App\Core\Request $r, array $p) => \App\Core\Response::redirect(url('back-office/recruitments')), [AuthMiddleware::class]);
    // Anciennes routes admin — redirections vers le back-office
    $router->get('/admin/users', fn (\App\Core\Request $r, array $p) => \App\Core\Response::redirect(url('back-office/users')), [AuthMiddleware::class]);
    $router->get('/admin/users/create', fn (\App\Core\Request $r, array $p) => \App\Core\Response::redirect(url('back-office/users/create')), [AuthMiddleware::class]);
    $router->get('/admin/units', fn (\App\Core\Request $r, array $p) => \App\Core\Response::redirect(url('back-office/groups')), [AuthMiddleware::class]);
    $router->get('/admin/units/create', fn (\App\Core\Request $r, array $p) => \App\Core\Response::redirect(url('back-office/groups/create')), [AuthMiddleware::class]);
    $router->get('/admin/units/{id}/edit', fn (\App\Core\Request $r, array $p) => \App\Core\Response::redirect(url('back-office/groups/' . ($p['id'] ?? '') . '/edit')), [AuthMiddleware::class]);
    $router->post('/admin/units/store', [AdminUnitsController::class, 'store'], [AuthMiddleware::class, TenantResourceAdminMiddleware::class]);
    $router->post('/admin/units/{id}/update', [AdminUnitsController::class, 'update'], [AuthMiddleware::class, TenantResourceAdminMiddleware::class]);
    $router->post('/admin/units/{id}/delete', [AdminUnitsController::class, 'delete'], [AuthMiddleware::class, TenantResourceAdminMiddleware::class]);
    $router->get('/admin/modpacks', [AdminModpackController::class, 'index'], [AuthMiddleware::class, TenantResourceAdminMiddleware::class]);
    $router->get('/admin/modpacks/create', [AdminModpackController::class, 'create'], [AuthMiddleware::class, TenantResourceAdminMiddleware::class]);
    $router->post('/admin/modpacks/store', [AdminModpackController::class, 'store'], [AuthMiddleware::class, TenantResourceAdminMiddleware::class]);
    $router->get('/admin/modpacks/{id}/edit', [AdminModpackController::class, 'edit'], [AuthMiddleware::class, TenantResourceAdminMiddleware::class]);
    $router->post('/admin/modpacks/{id}/update', [AdminModpackController::class, 'update'], [AuthMiddleware::class, TenantResourceAdminMiddleware::class]);
    $router->post('/admin/modpacks/{id}/delete', [AdminModpackController::class, 'delete'], [AuthMiddleware::class, TenantResourceAdminMiddleware::class]);
    $router->get('/admin/atak-config', [AdminAtakConfigController::class, 'index'], [AuthMiddleware::class, TenantResourceAdminMiddleware::class]);
    $router->post('/admin/atak-config', [AdminAtakConfigController::class, 'store'], [AuthMiddleware::class, TenantResourceAdminMiddleware::class]);
    $router->get('/admin/atak-mod', [AdminAtakModController::class, 'index'], [AuthMiddleware::class, TenantResourceAdminMiddleware::class]);
    $router->post('/admin/atak-mod/upload', [AdminAtakModController::class, 'upload'], [AuthMiddleware::class, TenantResourceAdminMiddleware::class]);
    $router->post('/admin/atak-mod/delete', [AdminAtakModController::class, 'delete'], [AuthMiddleware::class, TenantResourceAdminMiddleware::class]);
    $router->get('/admin/training', [AdminTrainingController::class, 'dashboard'], [AuthMiddleware::class, NonDefaultTenantMiddleware::class]);
    $router->get('/admin/training/courses', [AdminTrainingController::class, 'courses'], [AuthMiddleware::class, NonDefaultTenantMiddleware::class]);
    $router->get('/admin/training/enrollments', [AdminTrainingController::class, 'enrollments'], [AuthMiddleware::class, NonDefaultTenantMiddleware::class]);
    $router->get('/admin/training/reports', [AdminTrainingController::class, 'reports'], [AuthMiddleware::class, NonDefaultTenantMiddleware::class]);
    $router->get('/admin/training/certificates', [AdminTrainingController::class, 'certificates'], [AuthMiddleware::class, NonDefaultTenantMiddleware::class]);
    $router->get('/admin/training/audit', [AdminTrainingController::class, 'audit'], [AuthMiddleware::class, NonDefaultTenantMiddleware::class]);
    $router->get('/admin/forum-config', [\App\Controllers\Admin\AdminForumConfigController::class, 'index'], [AuthMiddleware::class, TenantResourceAdminMiddleware::class]);

    // Bureau Courrier / Correspondance Officielle
    $router->get('/courrier', [CourrierDashboardController::class, 'index'], [AuthMiddleware::class]);
    $router->get('/courrier/editor', [CourrierEditorController::class, 'index'], [AuthMiddleware::class]);
    $router->get('/courrier/editor/{id}', [CourrierEditorController::class, 'edit'], [AuthMiddleware::class]);
    $router->get('/courrier/read/{id}', [\App\Controllers\Courrier\CourrierReadController::class, 'show'], [AuthMiddleware::class]);
    $router->get('/courrier/notifications', [CourrierNotificationController::class, 'index'], [AuthMiddleware::class]);
    $router->post('/courrier/documents/{id}/notify', [CourrierNotificationController::class, 'notify'], [AuthMiddleware::class]);
    $router->post('/courrier/editor/save', [CourrierEditorController::class, 'save'], [AuthMiddleware::class]);
    $router->get('/courrier/templates', [CourrierTemplateController::class, 'index'], [AuthMiddleware::class]);
    $router->get('/courrier/templates/create', [CourrierTemplateController::class, 'create'], [AuthMiddleware::class]);
    $router->post('/courrier/templates', [CourrierTemplateController::class, 'store'], [AuthMiddleware::class]);
    $router->get('/courrier/templates/{id}/edit', [CourrierTemplateController::class, 'edit'], [AuthMiddleware::class]);
    $router->post('/courrier/templates/{id}', [CourrierTemplateController::class, 'update'], [AuthMiddleware::class]);
    $router->get('/courrier/presets', [CourrierPresetController::class, 'index'], [AuthMiddleware::class]);
    $router->post('/courrier/presets/{id}/default', [CourrierPresetController::class, 'setDefault'], [AuthMiddleware::class]);
    $router->post('/courrier/documents/{id}/workflow', [CourrierWorkflowController::class, 'transition'], [AuthMiddleware::class]);
    $router->post('/courrier/documents/{id}/sign', [CourrierSignatureController::class, 'sign'], [AuthMiddleware::class]);
    $router->get('/courrier/documents/{id}/verify', [CourrierSignatureController::class, 'verify'], [AuthMiddleware::class]);
    $router->get('/courrier/documents/{id}/signature-image', [CourrierSignatureController::class, 'documentSignatureImage'], [AuthMiddleware::class]);
    $router->get('/courrier/verify', [CourrierSignatureController::class, 'verifyByUuid']);
    $router->get('/courrier/my-signatures', [CourrierSignatureController::class, 'mySignatures'], [AuthMiddleware::class]);
    $router->get('/courrier/signatures/{id}/image', [CourrierSignatureController::class, 'signatureImage'], [AuthMiddleware::class]);
    $router->get('/courrier/documents/{id}/print', [CourrierPdfController::class, 'print'], [AuthMiddleware::class]);
    $router->get('/courrier/documents/{id}/pdf', [CourrierPdfController::class, 'pdf'], [AuthMiddleware::class]);
    $router->get('/courrier/documents/{id}/pdf-external', [CourrierPdfController::class, 'pdfExternal'], [AuthMiddleware::class]);
    $router->get('/courrier/api/snippets', [CourrierSnippetController::class, 'list'], [AuthMiddleware::class]);
    $router->get('/courrier/history', [CourrierDashboardController::class, 'history'], [AuthMiddleware::class]);
    $router->get('/courrier/archives', [CourrierDashboardController::class, 'archives'], [AuthMiddleware::class]);

    // Sortie vers lien externe (interstitiel sécurité)
    $router->get('/leave', [ExternalLeaveController::class, 'show'], [AuthMiddleware::class]);

    // Forum
    $router->get('/forum', [ForumController::class, 'index'], [AuthMiddleware::class]);
    $router->get('/forum/category/{slug}', [ForumCategoryController::class, 'show'], [AuthMiddleware::class]);
    $router->get('/forum/topic/{id}', [ForumTopicController::class, 'show'], [AuthMiddleware::class]);
    $router->post('/forum/topic/{id}/reply', [ForumTopicController::class, 'reply'], [AuthMiddleware::class]);
    $router->post('/forum/topic/{id}/subscribe', [ForumTopicController::class, 'subscribe'], [AuthMiddleware::class]);
    $router->post('/forum/topic/{id}/unsubscribe', [ForumTopicController::class, 'unsubscribe'], [AuthMiddleware::class]);
    $router->get('/forum/new-topic', [ForumNewTopicController::class, 'form'], [AuthMiddleware::class]);
    $router->post('/forum/new-topic', [ForumNewTopicController::class, 'store'], [AuthMiddleware::class]);
    $router->get('/back-office/forum-moderation', [ForumModerationDashboardController::class, 'index'], [AuthMiddleware::class, ForumModerationConsoleMiddleware::class]);
    $router->get('/back-office/content-moderation', [ContentModerationController::class, 'index'], [AuthMiddleware::class, ForumModerationConsoleMiddleware::class]);
    $router->post('/back-office/content-moderation/{id}/approve', [ContentModerationController::class, 'approve'], [AuthMiddleware::class, ForumModerationConsoleMiddleware::class]);
    $router->post('/back-office/content-moderation/{id}/reject', [ContentModerationController::class, 'reject'], [AuthMiddleware::class, ForumModerationConsoleMiddleware::class]);
    $router->get('/admin/forum-moderation', fn (\App\Core\Request $r, array $p) => \App\Core\Response::redirect(url('back-office/forum-moderation')), [AuthMiddleware::class]);
    $router->get('/forum/moderation', [ForumModerationController::class, 'index'], [AuthMiddleware::class, ForumModerateMiddleware::class]);
    $router->post('/forum/report/{id}/handle', [ForumModerationController::class, 'handleReport'], [AuthMiddleware::class, ForumModerateMiddleware::class]);
    $router->post('/forum/topic/{id}/lock', [ForumModerationController::class, 'lockTopic'], [AuthMiddleware::class, ForumModerateMiddleware::class]);
    $router->post('/forum/topic/{id}/unlock', [ForumModerationController::class, 'unlockTopic'], [AuthMiddleware::class, ForumModerateMiddleware::class]);
    $router->post('/forum/topic/{id}/pin', [ForumModerationController::class, 'pinTopic'], [AuthMiddleware::class, ForumModerateMiddleware::class]);
    $router->post('/forum/topic/{id}/unpin', [ForumModerationController::class, 'unpinTopic'], [AuthMiddleware::class, ForumModerateMiddleware::class]);

    // API Health (BDD) — pour la page ATAK État de santé
    $router->get('/api/health', [HealthController::class, 'index'], [AuthMiddleware::class]);
    $router->get('/api/me/preferences', [MePreferencesApiController::class, 'handle'], [AuthMiddleware::class]);
    $router->patch('/api/me/preferences', [MePreferencesApiController::class, 'handle'], [AuthMiddleware::class]);
    $router->post('/api/me/preferences', [MePreferencesApiController::class, 'handle'], [AuthMiddleware::class]);

    // API Training (LMS)
    $router->get('/api/training/catalogue', [TrainingApiController::class, 'catalogue'], [AuthMiddleware::class]);
    $router->get('/api/training/courses/{id}', [TrainingApiController::class, 'courseDetail'], [AuthMiddleware::class]);
    $router->post('/api/training/enroll', [TrainingApiController::class, 'enroll'], [AuthMiddleware::class]);
    $router->get('/api/training/enrollments/{id}/progress', [TrainingApiController::class, 'progress'], [AuthMiddleware::class]);
    $router->post('/api/training/progress/lesson', [TrainingApiController::class, 'progressLesson'], [AuthMiddleware::class]);
    $router->post('/api/training/quiz/start', [TrainingApiController::class, 'quizStart'], [AuthMiddleware::class]);
    $router->get('/api/training/quiz/attempts/{id}', [TrainingApiController::class, 'quizAttempt'], [AuthMiddleware::class]);
    $router->post('/api/training/quiz/submit', [TrainingApiController::class, 'quizSubmit'], [AuthMiddleware::class]);
    $router->get('/api/training/certificates/enrollment/{id}', [TrainingApiController::class, 'certificateByEnrollment'], [AuthMiddleware::class]);
    $router->get('/api/training/certificates/{id}/download', [TrainingApiController::class, 'certificateDownload'], [AuthMiddleware::class]);
    $router->get('/api/training/admin/courses', [TrainingApiController::class, 'adminCourses'], [AuthMiddleware::class]);
    $router->post('/api/training/admin/courses', [TrainingApiController::class, 'adminCourseSave'], [AuthMiddleware::class]);
    $router->post('/api/training/admin/courses/{id}', [TrainingApiController::class, 'adminCourseSave'], [AuthMiddleware::class]);
    $router->post('/api/training/admin/assign', [TrainingApiController::class, 'adminAssign'], [AuthMiddleware::class]);

    // API ATAK Full PHP (parité Node — polling, pas de Socket.IO)
    $router->get('/api/atak/ping', [AtakApiController::class, 'ping']);
    $router->get('/api/atak/whoami', [AtakApiController::class, 'whoami']);
    $router->get('/api/atak/stats', [AtakApiController::class, 'stats']);
    $router->get('/api/markers', [AtakApiController::class, 'markersIndex']);
    $router->post('/api/markers', [AtakApiController::class, 'markersStore']);
    $router->delete('/api/markers/{id}', [AtakApiController::class, 'markersDelete']);
    $router->get('/api/atak/markers', [AtakApiController::class, 'markersIndex']);
    $router->post('/api/atak/marker', [AtakApiController::class, 'markerUpsert']);
    $router->get('/api/units', [AtakApiController::class, 'unitsIndex']);
    $router->post('/api/units', [AtakApiController::class, 'unitsStore']);
    $router->patch('/api/units/{id}', [AtakApiController::class, 'unitsUpdate']);
    $router->post('/api/atak/position', [AtakApiController::class, 'position']);
    $router->get('/api/chat', [AtakApiController::class, 'chatIndex']);
    $router->post('/api/chat', [AtakApiController::class, 'chatStore']);
    $router->get('/api/pings', [AtakApiController::class, 'pingsIndex']);
    $router->post('/api/pings', [AtakApiController::class, 'pingsStore']);
    $router->get('/api/nine-line', [AtakApiController::class, 'nineLineIndex']);
    $router->post('/api/nine-line', [AtakApiController::class, 'nineLineStore']);
    $router->patch('/api/nine-line/{id}', [AtakApiController::class, 'nineLineUpdate']);
    // CAS / 9-Line C2
    $router->get('/api/cas', [AtakApiController::class, 'casIndex']);
    $router->post('/api/cas', [AtakApiController::class, 'casStore']);
    $router->get('/api/cas/{id}', [AtakApiController::class, 'casShow']);
    $router->patch('/api/cas/{id}', [AtakApiController::class, 'casUpdate']);
    $router->post('/api/cas/{id}/ack', [AtakApiController::class, 'casAck']);
    $router->post('/api/cas/{id}/check-line', [AtakApiController::class, 'casCheckLine']);
    $router->post('/api/cas/{id}/status', [AtakApiController::class, 'casStatus']);
    // Recon images (Cams)
    $router->get('/api/recon/images', [AtakApiController::class, 'reconImagesIndex']);
    $router->post('/api/recon/images', [AtakApiController::class, 'reconImagesStore']);
    $router->get('/api/recon/images/{id}', [AtakApiController::class, 'reconImagesShow']);
    $router->post('/api/recon/images/{id}/link-cas', [AtakApiController::class, 'reconImagesLinkCas']);
    // Map shapes (live drawing)
    $router->get('/api/map-shapes', [AtakApiController::class, 'mapShapesIndex']);
    $router->post('/api/map-shapes', [AtakApiController::class, 'mapShapesStore']);
    $router->patch('/api/map-shapes/{id}', [AtakApiController::class, 'mapShapesUpdate']);
    $router->delete('/api/map-shapes/{id}', [AtakApiController::class, 'mapShapesDelete']);
    // Laser codes
    $router->get('/api/atak/laser-codes', [AtakApiController::class, 'laserCodesIndex']);
    $router->post('/api/atak/laser-codes', [AtakApiController::class, 'laserCodesStore']);
    // Flight manifest
    $router->get('/api/flight-manifest', [AtakApiController::class, 'airAssetsIndex']);
    $router->get('/api/atak/designator', [AtakApiController::class, 'designatorIndex']);
    $router->post('/api/atak/designator', [AtakApiController::class, 'designatorStore']);
    $router->post('/api/atak/sigint', [AtakApiController::class, 'sigintStore']);
    $router->get('/api/atak/sigint/zones', [AtakApiController::class, 'sigintZones']);
    $router->get('/api/intel/photos', [AtakApiController::class, 'intelPhotosIndex']);
    $router->post('/api/intel/photos', [AtakApiController::class, 'intelPhotosStore']);
    $router->post('/api/atak/flight-manifest', [AtakApiController::class, 'flightManifestStore']);
    $router->get('/api/atak/air-assets', [AtakApiController::class, 'airAssetsIndex']);
    $router->patch('/api/atak/air-assets/{callsign}/pilot-status', [AtakApiController::class, 'airAssetsPilotStatus']);

    // API C2 — Fire Support
    $router->post('/api/fire-support/calculate', [FireSupportController::class, 'calculate']);
    $router->get('/api/fire-support/units', [FireSupportController::class, 'units']);

    // API C2 — Danger Zones
    $router->get('/api/danger-zones', [DangerZoneController::class, 'index']);
    $router->post('/api/danger-zones', [DangerZoneController::class, 'store']);
    $router->put('/api/danger-zones/{id}', [DangerZoneController::class, 'update']);
    $router->delete('/api/danger-zones/{id}', [DangerZoneController::class, 'delete']);

    // API C2 — Logistics
    $router->post('/api/logistics/update', [LogisticsController::class, 'update']);
    $router->get('/api/logistics/assets', [LogisticsController::class, 'assets']);

    // API C2 — Intel (SITREP fusion)
    $router->post('/api/intel/report', [IntelController::class, 'report']);
    $router->get('/api/intel/fused', [IntelController::class, 'fused']);

    // API C2 — Replay
    $router->get('/api/replay/mission/{missionId}', [ReplayController::class, 'mission']);
    $router->get('/api/replay/events/{missionId}', [ReplayController::class, 'events']);

    // API C2 — IFF
    $router->post('/api/iff/respond', [IffController::class, 'respond']);
    $router->get('/api/iff/current', [IffController::class, 'current']);
    $router->get('/api/iff/assets', [IffController::class, 'assets']);

    // API ATAK Intel (legacy — redirige vers atak_intel, gardé pour compat)
    $router->post('/api/atak/intel', [AtakIntelController::class, 'storeIntel']);

    // API Forum — REST structurée (prioritaire sur le handler legacy)
    $router->get('/api/forum/topics', [ForumRestController::class, 'listTopics'], [AuthMiddleware::class]);
    $router->get('/api/forum/topics/{id}', [ForumRestController::class, 'showTopic'], [AuthMiddleware::class]);
    $router->get('/api/forum/topics/{topicId}/posts', [ForumRestController::class, 'listPosts'], [AuthMiddleware::class]);
    $router->post('/api/forum/posts/{postId}/vote', [ForumRestController::class, 'votePost'], [AuthMiddleware::class]);
    $router->post('/api/forum/report', [ForumRestController::class, 'report'], [AuthMiddleware::class]);
    $router->get('/api/forum/search', [ForumRestController::class, 'search'], [AuthMiddleware::class]);

    // API Forum (JSON, actions legacy)
    $router->get('/api/forum', [ForumApiController::class, 'handle'], [AuthMiddleware::class]);
    $router->post('/api/forum', [ForumApiController::class, 'handle'], [AuthMiddleware::class]);
    $router->post('/api/forum-moderation', [ForumModerationApiController::class, 'handle'], [AuthMiddleware::class, ForumModerateMiddleware::class]);
    $router->post('/api/forum-upload', [ForumUploadController::class, 'handle'], [AuthMiddleware::class]);
    $router->post('/api/admin/forum-categories', [\App\Controllers\Admin\ForumCategoriesApiController::class, 'handle'], [AuthMiddleware::class]);
    $router->post('/api/admin/site-settings', [\App\Controllers\Admin\SiteSettingsApiController::class, 'handle'], [AuthMiddleware::class]);
    $router->post('/api/alerts/dismiss', [AlertDismissController::class, 'handle'], [AuthMiddleware::class]);
    $router->post('/api/back-office/forum-moderation', [\App\Controllers\Admin\ForumModerationAdminApiController::class, 'handle'], [AuthMiddleware::class]);
    $router->post('/api/admin/forum-moderation', [\App\Controllers\Admin\ForumModerationAdminApiController::class, 'handle'], [AuthMiddleware::class]);
};
