<?php

declare(strict_types=1);

use App\Controllers\Web\HomeController;
use App\Controllers\Web\PersonnelController;
use App\Controllers\Web\EnlistmentController;
use App\Controllers\Web\DocumentsController;
use App\Controllers\Web\TrainingController;
use App\Controllers\Web\AtakController;
use App\Controllers\Web\AccountController;
use App\Controllers\Web\ModpackController;
use App\Controllers\Web\ForumController;
use App\Controllers\Web\ForumCategoryController;
use App\Controllers\Web\ForumTopicController;
use App\Controllers\Web\ForumNewTopicController;
use App\Controllers\Web\ForumModerationController;
use App\Controllers\Admin\AdminDashboardController;
use App\Controllers\Admin\AdminUsersController;
use App\Controllers\Admin\AdminUnitsController;
use App\Controllers\Admin\AdminModpackController;
use App\Controllers\Admin\AdminAtakConfigController;
use App\Controllers\Admin\AdminConfigurationController;
use App\Controllers\Admin\AdminRecruitmentsController;
use App\Controllers\Auth\AuthController;
use App\Core\Router;
use App\Middleware\AuthMiddleware;
use App\Middleware\GuestMiddleware;
use App\Middleware\ForumModerateMiddleware;

return function (Router $router) {
    $router->get('/', [HomeController::class, 'index']);
    $router->get('/login', [AuthController::class, 'showLogin'], [GuestMiddleware::class]);
    $router->post('/login', [AuthController::class, 'login'], [GuestMiddleware::class]);
    $router->post('/logout', [AuthController::class, 'logout']);
    $router->get('/forgot-password', [AuthController::class, 'showForgotPassword'], [GuestMiddleware::class]);
    $router->post('/forgot-password', [AuthController::class, 'sendResetLink'], [GuestMiddleware::class]);
    $router->get('/reset-password', [AuthController::class, 'showResetPassword'], [GuestMiddleware::class]);
    $router->post('/reset-password', [AuthController::class, 'processResetPassword'], [GuestMiddleware::class]);
    $router->get('/dashboard', [HomeController::class, 'dashboard'], [AuthMiddleware::class]);
    $router->get('/account', [AccountController::class, 'index'], [AuthMiddleware::class]);
    $router->get('/account/preferences', [AccountController::class, 'preferences'], [AuthMiddleware::class]);
    $router->post('/account/preferences', [AccountController::class, 'preferences'], [AuthMiddleware::class]);
    $router->get('/account/mail', [AccountController::class, 'mail'], [AuthMiddleware::class]);
    $router->post('/account/mail', [AccountController::class, 'mail'], [AuthMiddleware::class]);
    $router->get('/account/image', [AccountController::class, 'image'], [AuthMiddleware::class]);
    $router->post('/account/image', [AccountController::class, 'image'], [AuthMiddleware::class]);
    $router->get('/account/password', [AccountController::class, 'password'], [AuthMiddleware::class]);
    $router->post('/account/password', [AccountController::class, 'password'], [AuthMiddleware::class]);
    $router->get('/personnel/me', [PersonnelController::class, 'me'], [AuthMiddleware::class]);
    $router->get('/personnel/{id}', [PersonnelController::class, 'show'], [AuthMiddleware::class]);
    $router->post('/personnel/{id}/generate-matricule', [PersonnelController::class, 'generateMatricule'], [AuthMiddleware::class]);
    $router->get('/orbat', [PersonnelController::class, 'orbat'], [AuthMiddleware::class]);
    $router->get('/enlistment', [EnlistmentController::class, 'show']);
    $router->post('/enlistment', [EnlistmentController::class, 'store']);
    $router->get('/enlistment/success', [EnlistmentController::class, 'success']);
    $router->get('/enlistment/error', [EnlistmentController::class, 'error']);
    $router->get('/recrutement', [HomeController::class, 'recrutement']);
    $router->get('/equipement', [HomeController::class, 'equipement']);
    $router->get('/documents', [DocumentsController::class, 'index'], [AuthMiddleware::class]);
    $router->get('/documents/{id}/download', [DocumentsController::class, 'download'], [AuthMiddleware::class]);
    $router->get('/modpacks', [ModpackController::class, 'index'], [AuthMiddleware::class]);
    $router->get('/modpacks/images/{id}', [ModpackController::class, 'image'], [AuthMiddleware::class]);
    $router->get('/modpacks/{id}/download', [ModpackController::class, 'download'], [AuthMiddleware::class]);
    $router->get('/modpacks/{slug}', [ModpackController::class, 'show'], [AuthMiddleware::class]);
    $router->get('/formations', [TrainingController::class, 'index'], [AuthMiddleware::class]);
    $router->get('/formations/{slug}', [TrainingController::class, 'show'], [AuthMiddleware::class]);
    $router->get('/atak', [AtakController::class, 'index'], [AuthMiddleware::class]);
    $router->get('/atak/tuto', [AtakController::class, 'tuto'], [AuthMiddleware::class]);
    $router->get('/tacmap', [HomeController::class, 'tacmap'], [AuthMiddleware::class]);
    $router->get('/admin', [AdminDashboardController::class, 'index'], [AuthMiddleware::class]);
    $router->get('/admin/users', [AdminUsersController::class, 'index'], [AuthMiddleware::class]);
    $router->get('/admin/users/create', [AdminUsersController::class, 'create'], [AuthMiddleware::class]);
    $router->get('/admin/units', [AdminUnitsController::class, 'index'], [AuthMiddleware::class]);
    $router->get('/admin/units/create', [AdminUnitsController::class, 'create'], [AuthMiddleware::class]);
    $router->post('/admin/units/store', [AdminUnitsController::class, 'store'], [AuthMiddleware::class]);
    $router->get('/admin/units/{id}/edit', [AdminUnitsController::class, 'edit'], [AuthMiddleware::class]);
    $router->post('/admin/units/{id}/update', [AdminUnitsController::class, 'update'], [AuthMiddleware::class]);
    $router->post('/admin/units/{id}/delete', [AdminUnitsController::class, 'delete'], [AuthMiddleware::class]);
    $router->get('/admin/modpacks', [AdminModpackController::class, 'index'], [AuthMiddleware::class]);
    $router->get('/admin/modpacks/create', [AdminModpackController::class, 'create'], [AuthMiddleware::class]);
    $router->post('/admin/modpacks/store', [AdminModpackController::class, 'store'], [AuthMiddleware::class]);
    $router->get('/admin/modpacks/{id}/edit', [AdminModpackController::class, 'edit'], [AuthMiddleware::class]);
    $router->post('/admin/modpacks/{id}/update', [AdminModpackController::class, 'update'], [AuthMiddleware::class]);
    $router->post('/admin/modpacks/{id}/delete', [AdminModpackController::class, 'delete'], [AuthMiddleware::class]);
    $router->get('/admin/atak-config', [AdminAtakConfigController::class, 'index'], [AuthMiddleware::class]);
    $router->post('/admin/atak-config', [AdminAtakConfigController::class, 'store'], [AuthMiddleware::class]);
    $router->get('/admin/configuration', [AdminConfigurationController::class, 'index'], [AuthMiddleware::class]);
    $router->get('/admin/recruitments', [AdminRecruitmentsController::class, 'index'], [AuthMiddleware::class]);

    // Forum
    $router->get('/forum', [ForumController::class, 'index'], [AuthMiddleware::class]);
    $router->get('/forum/category/{slug}', [ForumCategoryController::class, 'show'], [AuthMiddleware::class]);
    $router->get('/forum/topic/{id}', [ForumTopicController::class, 'show'], [AuthMiddleware::class]);
    $router->post('/forum/topic/{id}/reply', [ForumTopicController::class, 'reply'], [AuthMiddleware::class]);
    $router->post('/forum/topic/{id}/subscribe', [ForumTopicController::class, 'subscribe'], [AuthMiddleware::class]);
    $router->post('/forum/topic/{id}/unsubscribe', [ForumTopicController::class, 'unsubscribe'], [AuthMiddleware::class]);
    $router->get('/forum/new-topic', [ForumNewTopicController::class, 'form'], [AuthMiddleware::class]);
    $router->post('/forum/new-topic', [ForumNewTopicController::class, 'store'], [AuthMiddleware::class]);
    $router->get('/forum/moderation', [ForumModerationController::class, 'index'], [AuthMiddleware::class, ForumModerateMiddleware::class]);
    $router->post('/forum/report/{id}/handle', [ForumModerationController::class, 'handleReport'], [AuthMiddleware::class, ForumModerateMiddleware::class]);
    $router->post('/forum/topic/{id}/lock', [ForumModerationController::class, 'lockTopic'], [AuthMiddleware::class, ForumModerateMiddleware::class]);
    $router->post('/forum/topic/{id}/unlock', [ForumModerationController::class, 'unlockTopic'], [AuthMiddleware::class, ForumModerateMiddleware::class]);
    $router->post('/forum/topic/{id}/pin', [ForumModerationController::class, 'pinTopic'], [AuthMiddleware::class, ForumModerateMiddleware::class]);
    $router->post('/forum/topic/{id}/unpin', [ForumModerationController::class, 'unpinTopic'], [AuthMiddleware::class, ForumModerateMiddleware::class]);
};
