<?php

declare(strict_types=1);

namespace App\Services\Rbac;

/**
 * Correspondance emploi métier (slug interne) → code de spécialité militaire américain.
 * Titres Army alignés sur le DA PAM 611-21 ; les exceptions Air Force emploient leur AFSC AFECD.
 * Les codes « officier » utilisent la convention AOC (ex. 11A, 35D) ; les grades du rang le format CMF + spécialité (ex. 11B, 68W).
 *
 * @phpstan-type MosPair array{0: string, 1: string}
 */
final class UsArmyMosCatalog
{
    /**
     * @return array<string, MosPair> slug interne → [code MOS/AOC, intitulé officiel anglais]
     */
    public static function byJobRoleSlug(): array
    {
        return [
            'command_unit_commander' => ['11A', 'Infantry Officer'],
            'command_executive_officer' => ['11A', 'Infantry Officer'],
            'command_senior_officer' => ['11A', 'Infantry Officer'],
            'command_duty_officer' => ['11A', 'Infantry Officer'],
            'operations_officer' => ['11A', 'Infantry Officer'],
            'staff_plans_officer' => ['11A', 'Infantry Officer'],
            'staff_battle_captain' => ['11A', 'Infantry Officer'],
            'staff_joint_coordination_officer' => ['13A', 'Field Artillery Officer'],
            'hr' => ['42A', 'Human Resources Specialist'],
            'admin_staff_officer' => ['42H', 'Human Resources Officer'],
            'admin_unit_secretary' => ['42A', 'Human Resources Specialist'],
            'admin_hr_officer' => ['42H', 'Human Resources Officer'],
            'admin_hr_technician' => ['42A', 'Human Resources Specialist'],
            'admin_finance_officer' => ['36A', 'Financial Manager Officer'],
            'admin_finance_technician' => ['36B', 'Financial Management Technician'],
            'admin_operative_clerk' => ['42A', 'Human Resources Specialist'],
            'admin_legal_advisor' => ['27A', 'Judge Advocate'],
            'admin_protocol_officer' => ['42H', 'Human Resources Officer'],
            'aero_tactical_pilot' => ['15A', 'Aviation Officer'],
            'aero_weapon_systems_officer' => ['15A', 'Aviation Officer'],
            'aero_loadmaster' => ['88H', 'Cargo Specialist'],
            'aero_air_delivery_chief' => ['88H', 'Cargo Specialist'],
            'aero_refuel_operator' => ['92F', 'Petroleum Supply Specialist'],
            'aero_ground_support_chief' => ['15P', 'Aviation Operations Specialist'],
            'aero_160th_soar_pilot' => ['CMF 15', 'Army Aviation (aircraft qualification dependent)'],
            'fires_jtac' => ['13F', 'Fire Support Specialist'],
            'fires_forward_observer' => ['13F', 'Fire Support Specialist'],
            'fires_support_officer' => ['13A', 'Field Artillery Officer'],
            'fires_gun_chief' => ['13B', 'Cannon Crewmember'],
            'fires_gun_crew' => ['13B', 'Cannon Crewmember'],
            'arty_group_leader' => ['13B', 'Cannon Crewmember'],
            'arty_fire_direction' => ['13J', 'Fire Control Specialist'],
            'arty_mortar_squad' => ['11C', 'Indirect Fire Infantryman'],
            'arty_radar_operator' => ['13R', 'Field Artillery Radar Operator'],
            'armor_platoon_leader' => ['19A', 'Armor Officer'],
            'armor_vehicle_commander' => ['19K', 'M1 Armor Crewman'],
            'armor_driver' => ['19K', 'M1 Armor Crewman'],
            'armor_gunner' => ['19K', 'M1 Armor Crewman'],
            'armor_loader' => ['19K', 'M1 Armor Crewman'],
            'armor_cavalry_scout' => ['19D', 'Cavalry Scout'],
            'armor_recovery_operator' => ['91H', 'Track Vehicle Repairer'],
            'instructor' => ['79R', 'Recruiter'],
            'instruction_trainer' => ['79S', 'Career Counselor'],
            'training_officer' => ['79S', 'Career Counselor'],
            'instruction_evaluator' => ['79S', 'Career Counselor'],
            'edu_academic_instructor' => ['09L', 'Interpreter / Translator'],
            'edu_doctrine_officer' => ['34A', 'Force Sustainment Officer'],
            'edu_bandmaster' => ['42S', 'Special Band Officer'],
            'edu_musician' => ['42R', 'Musician'],
            'sf_team_leader' => ['18A', 'Special Forces Officer'],
            'sf_operator' => ['18B', 'Special Forces Weapons Sergeant'],
            'sf_comms' => ['18E', 'Special Forces Communications Sergeant'],
            'sf_intelligence' => ['18F', 'Special Forces Intelligence Sergeant'],
            'sf_medic' => ['18D', 'Special Forces Medical Sergeant'],
            'sf_air_force_cct' => ['1Z2X1', 'Combat Control'],
            'sf_air_force_pj' => ['1Z1X1', 'Pararescue'],
            'sf_air_force_tacp' => ['1Z3X1', 'Tactical Air Control Party'],
            'sf_cag_b_squadron_operator' => ['NON PUBLIC', 'CAG duty position not publicly classified'],
            'engineer_sapper' => ['12B', 'Combat Engineer'],
            'engineer_eod' => ['89D', 'Explosive Ordnance Disposal Specialist'],
            'engineer_group_chief' => ['12A', 'Engineer Officer'],
            'engineer_infra_technician' => ['12N', 'Horizontal Construction Engineer'],
            'engineer_works_lead' => ['12A', 'Engineer Officer'],
            'engineer_cbrn_specialist' => ['74D', 'Chemical, Biological, Radiological and Nuclear (CBRN) Specialist'],
            'engineer_bridge_raft' => ['12C', 'Bridge Crewmember'],
            'engineer_urban_breach' => ['12B', 'Combat Engineer'],
            'infantry_section_chief' => ['11A', 'Infantry Officer'],
            'infantry_group_chief' => ['11B', 'Infantryman'],
            'infantry_team_chief' => ['11B', 'Infantryman'],
            'infantry_rifleman' => ['11B', 'Infantryman'],
            'infantry_grenadier' => ['11B', 'Infantryman'],
            'infantry_sharpshooter' => ['11B', 'Infantryman'],
            'infantry_marksman' => ['11B', 'Infantryman'],
            'infantry_sniper' => ['11B', 'Infantryman'],
            'infantry_machine_gunner' => ['11B', 'Infantryman'],
            'infantry_radio_operator' => ['25U', 'Signal Support Systems Specialist'],
            'infantry_scout' => ['19D', 'Cavalry Scout'],
            'infantry_team_pair_chief' => ['11B', 'Infantryman'],
            'infantry_at_specialist' => ['11B', 'Infantryman'],
            'infantry_mortar_operator' => ['11C', 'Indirect Fire Infantryman'],
            'cyber_telecoms_group_chief' => ['25U', 'Signal Support Systems Specialist'],
            'cyber_signal_operator' => ['25U', 'Signal Support Systems Specialist'],
            'cyber_technician' => ['17C', 'Cyber Operations Specialist'],
            'cyber_systems_technician' => ['25B', 'Information Technology Specialist'],
            'cyber_network_technician' => ['25N', 'Nodal Network Systems Operator-Maintainer'],
            'cyber_dev_technician' => ['25D', 'Cyber Network Defender'],
            'cyber_telecom_expert_officer' => ['25A', 'Signal Officer'],
            'cyber_is_expert_officer' => ['25A', 'Signal Officer'],
            'cyber_sec_expert_officer' => ['17A', 'Cyber Corps Officer'],
            'cyber_it_telecom_officer' => ['25A', 'Signal Officer'],
            'cyber_ew_technician' => ['29E', 'Electronic Warfare Specialist'],
            'cyber_satcom_operator' => ['25S', 'Satellite Communication Systems Operator-Maintainer'],
            'logistics_officer' => ['90A', 'Logistics Corps Officer'],
            'staff_sustainment_lead' => ['92Y', 'Unit Supply Specialist'],
            'staff_logistics_flow_manager' => ['88N', 'Transportation Management Coordinator'],
            'logistics_driver' => ['88M', 'Motor Transport Operator'],
            'logistics_convoy_chief' => ['88H', 'Cargo Specialist'],
            'log_supply_group_chief' => ['92A', 'Automated Logistical Specialist'],
            'log_warehouse_chief' => ['92A', 'Automated Logistical Specialist'],
            'log_ammo_mag_chief' => ['89B', 'Ammunition Specialist'],
            'log_fuel_specialist' => ['92F', 'Petroleum Supply Specialist'],
            'log_rations_manager' => ['92G', 'Culinary Specialist'],
            'logistics_mechanic' => ['91B', 'Wheeled Vehicle Mechanic'],
            'logistics_maint_technician' => ['91A', 'M1 Abrams Tank System Maintainer'],
            'logistics_fleet_manager' => ['91Z', 'Mechanical Maintenance Supervisor'],
            'maint_armorer' => ['91F', 'Small Arms / Artillery Repairer'],
            'maint_ground_support' => ['15R', 'AH-64 Attack Helicopter Repairer'],
            'maint_elec_tech' => ['91C', 'Utilities Equipment Repairer'],
            'maint_quality_controller' => ['91X', 'Maintenance Supervisor'],
            'intelligence_officer' => ['35D', 'All-Source Intelligence Officer'],
            'staff_intel_analyst' => ['35F', 'Intelligence Analyst'],
            'staff_intel_cell' => ['35F', 'Intelligence Analyst'],
            'staff_intel_exploitation' => ['35N', 'Signals Intelligence Analyst'],
            'intel_humint' => ['35M', 'Human Intelligence Collector'],
            'intel_geo' => ['35G', 'Geospatial Intelligence Imagery Analyst'],
            'intel_sigint_tech' => ['35N', 'Signals Intelligence Analyst'],
            'intel_osint' => ['35F', 'Intelligence Analyst'],
            'intel_counterint' => ['35D', 'Military Intelligence Officer'],
            'cater_field_kitchen_chief' => ['92G', 'Culinary Specialist'],
            'cater_cook' => ['92G', 'Culinary Specialist'],
            'cater_baker' => ['92G', 'Culinary Specialist'],
            'cater_dietitian' => ['65C', 'Dietitian'],
            'cater_hygiene' => ['92G', 'Culinary Specialist'],
            'medical_officer' => ['60A', 'Medical Corps Officer'],
            'medical_nurse' => ['66S', 'Clinical Nurse'],
            'medical_auxiliary' => ['68C', 'Practical Nursing Specialist'],
            'medical_first_responder' => ['68W', 'Combat Medic Specialist'],
            'medical_dentist' => ['63A', 'Dental Corps Officer'],
            'medical_pharmacist' => ['65A', 'Pharmacy Officer'],
            'medical_lab_tech' => ['68K', 'Medical Laboratory Specialist'],
            'medical_combat_paramedic' => ['68W', 'Combat Medic Specialist'],
            'sec_military_police' => ['31B', 'Military Police'],
            'sec_installation_guard' => ['31B', 'Military Police'],
            'sec_sentinel' => ['11B', 'Infantryman'],
            'sec_k9_team_lead' => ['31K', 'Military Working Dog Handler'],
            'sec_k9_handler' => ['31K', 'Military Working Dog Handler'],
            'sec_firefighter' => ['12M', 'Firefighter'],
            'sec_prevention_advisor' => ['12H', 'Construction Engineering Supervisor'],
            'sport_physical_instructor' => ['79S', 'Career Counselor'],
            'sport_rehab_coach' => ['68W', 'Combat Medic Specialist'],
            'sport_facility_manager' => ['88N', 'Transportation Management Coordinator'],
        ];
    }

    public static function forSlug(string $slug): ?array
    {
        $map = self::byJobRoleSlug();

        return $map[$slug] ?? null;
    }
}
