<?php

declare(strict_types=1);

/**
 *  portail Athena — chemins relatifs passés à url() (sans domaine ni préfixe /public).
 *
 * Permissions : voir Gate / header actuel (documents.view, courrier.view, admin.*, etc.).
 *
 * Méga-menus : accent (sky|amber|emerald|violet|rose|slate), variant (layout), sections.slot (primary|center|secondary),
 * live (placeholders ou futurs flux), featured.cta_intent (open|monitor|resume|administer|view_activity|access).
 */
return [
    'brand' => [
        'name' => 'Athena',
        'subtitle' => '',
        'tagline' => '',
        'path' => '',
    ],

    'search' => [
        'enabled' => true,
        'shortcut' => true,
        'placeholder' => 'Rechercher un module, un document, un personnel…',
        'path' => 'search',
        'method' => 'get',
        'param' => 'q',
    ],

    'menu' => [
        [
            'label' => 'Accueil',
            'type' => 'link',
            'path' => '',
            'guest_only' => true,
        ],
        [
            'label' => 'Commandement',
            'type' => 'mega',
            'auth_only' => true,
            'icon' => 'crosshair',
            'accent' => 'sky',
            'variant' => 'operations',
            'featured' => [
                'eyebrow' => 'Pilotage',
                'title' => 'Centre de commandement',
                'description' => 'Hub, briefings, manœuvres et outils de coordination de la communauté.',
                'image' => 'assets/img/nav/operations.jpg',
                'image_enabled' => true,
                'image_position' => 'center',
                'overlay' => 'dark',
                'cta_label' => 'Ouvrir le centre',
                'cta_path' => 'hub',
                'cta_intent' => 'open',
            ],
            'sections' => [
                [
                    'title' => 'Pilotage & coordination',
                    'slot' => 'primary',
                    'links' => [
                        ['label' => 'Centre de commandement', 'path' => 'hub', 'description' => 'Modules, raccourcis et synthèse'],
                        ['label' => 'Briefing', 'path' => 'dashboard', 'description' => 'Synthèse personnelle et actualités'],
                        ['label' => 'Boîte de réception', 'path' => 'boite-reception', 'description' => 'Messages, activité et éléments à traiter'],
                        ['label' => 'Manœuvres', 'path' => 'manoeuvres', 'description' => 'Présences et confirmations aux créneaux'],
                        ['label' => 'Communautés', 'path' => 'communities', 'description' => 'Registre et accès aux espaces'],
                        ['label' => 'Premiers pas', 'path' => 'onboarding', 'description' => 'Parcours d’accueil dans le portail'],
                    ],
                ],
                [
                    'title' => 'Forum & échanges',
                    'slot' => 'primary',
                    'links' => [
                        ['label' => 'Accueil du forum', 'path' => 'forum', 'permission' => 'forum.view', 'module' => 'forum', 'description' => 'Rubriques, sujets et échanges'],
                        ['label' => 'Messagerie interne', 'path' => 'messages', 'description' => 'Échanges avec l’encadrement de votre communauté'],
                        ['label' => 'Publier un sujet', 'path' => 'forum/new-topic', 'permission' => 'forum.create_topic', 'description' => 'Démarrer une discussion'],
                    ],
                ],
                [
                    'title' => 'Situation tactique',
                    'slot' => 'center',
                    'links' => [
                        ['label' => 'Poste de commandement', 'path' => 'c2', 'description' => 'Accès aux modes de coordination'],
                        ['label' => 'Situation tactique (ATAK)', 'path' => 'atak', 'description' => 'Vue opérationnelle'],
                        ['label' => 'Effectifs en liaison', 'path' => 'back-office/atak/operateurs', 'any_permissions' => ['admin.system', 'admin.organization', 'admin.access'], 'description' => 'Tableur des opérateurs connectés'],
                        ['label' => 'Overwatch', 'path' => 'overwatch', 'description' => 'Situation en carte et commandement'],
                        ['label' => 'TACMAP', 'path' => 'tacmap', 'description' => 'Cartographie tactique'],
                        ['label' => 'Cycle de mission', 'path' => 'back-office/atak/cycle-mission', 'description' => 'Briefing, exécution et après-action', 'any_permissions' => ['admin.system', 'admin.organization', 'admin.access']],
                        ['label' => 'Comptes rendus (AAR)', 'path' => 'back-office/atak/comptes-rendus', 'description' => 'Rapports post-opération et suivi des actions', 'any_permissions' => ['admin.system', 'admin.organization', 'admin.access']],
                        ['label' => 'Certificats et terminaux', 'path' => 'back-office/atak/realisme', 'description' => 'Registre ATAK, identifiants de terminal et certificats', 'any_permissions' => ['admin.system', 'admin.organization', 'admin.access']],
                        ['label' => 'Première liaison ATAK', 'path' => 'atak/premiere-liaison', 'description' => 'Mise en service guidée'],
                        ['label' => 'Mur opérationnel', 'path' => 'tableau-operationnel', 'permission' => 'operational.board.view', 'description' => 'Permanences et consignes publiées'],
                    ],
                ],
                [
                    'title' => 'Logistique & salle',
                    'slot' => 'secondary',
                    'links' => [
                        ['label' => 'Équipement', 'path' => 'equipment', 'description' => 'Manuels et fiches matériel'],
                        ['label' => 'Modpacks', 'path' => 'modpacks', 'description' => 'Mods et paquets de la communauté'],
                        ['label' => 'Salle de guerre', 'path' => 'salle-de-guerre', 'description' => 'Espace de briefing collectif'],
                    ],
                ],
            ],
            'live' => [
                [
                    'id' => 'ops_briefing',
                    'type' => 'forum_recent',
                    'enabled' => true,
                    'title' => 'Dernier briefing publié',
                    'empty_message' => 'Aucun briefing récent.',
                ],
                [
                    'id' => 'ops_mission',
                    'type' => 'mission_active',
                    'enabled' => true,
                    'title' => 'Mission active',
                    'empty_message' => 'Aucune mission en cours signalée.',
                ],
            ],
        ],
        [
            'label' => 'Doctrine',
            'type' => 'mega',
            'auth_only' => true,
            'module' => 'documents',
            'icon' => 'folder',
            'accent' => 'amber',
            'variant' => 'resources',
            'featured' => [
                'eyebrow' => 'Documentaire',
                'title' => 'Pôle doctrine',
                'description' => 'Documents, courrier officiel, guides et aide à la recherche.',
                'image' => 'assets/img/nav/resources.jpg',
                'image_enabled' => true,
                'image_position' => 'center',
                'overlay' => 'dark',
                'cta_label' => 'Ouvrir le guide',
                'cta_path' => 'documentation',
                'cta_intent' => 'access',
            ],
            'sections' => [
                [
                    'title' => 'Documents',
                    'slot' => 'primary',
                    'links' => [
                        ['label' => 'Bibliothèque', 'path' => 'documents', 'permission' => 'documents.view', 'description' => 'Consulter les documents publiés'],
                        ['label' => 'Collections', 'path' => 'documents/collections', 'permission' => 'documents.view', 'description' => 'Parcourir les collections documentaires'],
                        ['label' => 'Mon accréditation', 'path' => 'documents/accreditation', 'permission' => 'documents.view', 'description' => 'Vérifier votre niveau de clearance'],
                        ['label' => 'Gestion documentaire', 'path' => 'documents/gestion', 'permission' => 'documents.upload', 'description' => 'Ajouter, classer et suivre les versions'],
                    ],
                ],
                [
                    'title' => 'Correspondance officielle',
                    'slot' => 'center',
                    'links' => [
                        ['label' => 'Tableau du courrier', 'path' => 'courrier', 'permission' => 'courrier.view', 'description' => 'Brouillons, validations et suivi'],
                        ['label' => 'Rédiger un courrier', 'path' => 'courrier/editor', 'permission' => 'courrier.create', 'description' => 'Création et édition'],
                        ['label' => 'Modèles', 'path' => 'courrier/templates', 'any_permissions' => ['courrier.create', 'courrier.validate'], 'description' => 'Gabarits réutilisables'],
                        ['label' => 'Historique', 'path' => 'courrier/history', 'permission' => 'courrier.view', 'description' => 'Activité récente'],
                        ['label' => 'Archives', 'path' => 'courrier/archives', 'any_permissions' => ['courrier.view', 'courrier.archive'], 'description' => 'Courriers classés'],
                        ['label' => 'Traçabilité', 'path' => 'courrier/traceabilite', 'permission' => 'courrier.view', 'description' => 'Checklist et suivi décisionnel'],
                    ],
                ],
                [
                    'title' => 'Aide & recherche',
                    'slot' => 'secondary',
                    'links' => [
                        ['label' => 'Guide du portail', 'path' => 'documentation', 'description' => 'Mode d’emploi intégré au site'],
                        ['label' => 'Bibliothèque de marqueurs', 'path' => 'documentation/marqueurs', 'description' => 'Légende visuelle des symboles carte'],
                        ['label' => 'Recherche', 'path' => 'search', 'description' => 'Parcourir le portail (raccourci clavier selon configuration)'],
                        ['label' => 'Assistant', 'path' => 'assistant', 'description' => 'Aide guidée dans le périmètre de votre communauté'],
                        ['label' => 'Documentation technique du mod', 'path' => 'documentation/references', 'description' => 'Architecture Overwatch, dépendances et build'],
                    ],
                ],
            ],
            'live' => [
                [
                    'id' => 'res_stats',
                    'type' => 'document_stats',
                    'enabled' => true,
                    'title' => 'Synthèse documentaire',
                    'empty_message' => 'Statistiques disponibles prochainement.',
                ],
            ],
        ],
        [
            'label' => 'Effectifs',
            'type' => 'mega',
            'auth_only' => true,
            'module' => 'personnel',
            'icon' => 'users',
            'accent' => 'emerald',
            'variant' => 'personnel',
            'featured' => [
                'eyebrow' => 'Ressources humaines',
                'title' => 'Espace effectifs',
                'description' => 'Fiches, organisation, distinctions et recrutement.',
                'image' => 'assets/img/nav/personnel.jpg',
                'image_enabled' => true,
                'image_position' => 'center',
                'overlay' => 'dark',
                'cta_label' => 'Accéder à ma fiche',
                'cta_path' => 'personnel/me',
                'cta_intent' => 'access',
            ],
            'sections' => [
                [
                    'title' => 'Ma situation',
                    'slot' => 'primary',
                    'links' => [
                        ['label' => 'Ma fiche personnelle', 'path' => 'personnel/me'],
                        ['label' => 'Espace RH et formations', 'path' => 'personnel/mon-espace-rh', 'description' => 'Charte, parcours, ancienneté et programmes de préqualification'],
                        ['label' => 'Distinctions', 'path' => 'distinctions', 'description' => 'Reconnaissances et parcours valorisés'],
                        ['label' => 'Paramètres du compte', 'path' => 'account', 'description' => 'Identité, sécurité et médias'],
                        ['label' => 'Préférences', 'path' => 'account/preferences', 'description' => 'Langue, fuseau et affichage'],
                    ],
                ],
                [
                    'title' => 'Effectifs & annuaire',
                    'slot' => 'center',
                    'links' => [
                        ['label' => 'Annuaire des profils', 'path' => 'personnel', 'description' => 'Rechercher un membre'],
                        ['label' => 'Organisation (ORBAT)', 'path' => 'orbat', 'permission' => 'organization.orbat.view', 'description' => 'Vue hiérarchique des effectifs'],
                        ['label' => 'Candidature', 'path' => 'enlistment', 'description' => 'Déposer ou suivre une candidature'],
                    ],
                ],
                [
                    'title' => 'Recrutement (administrateurs)',
                    'slot' => 'secondary',
                    'links' => [
                        ['label' => 'Bureau recrutement', 'path' => 'back-office/ressources/recrutement', 'any_permissions' => ['organization.recruitment.manage', 'admin.organization', 'admin.access'], 'description' => 'Pilotage : indicateurs, file et analyses'],
                        ['label' => 'Bureau effectifs', 'path' => 'back-office/ressources/effectifs', 'any_permissions' => ['organization.effectifs.hub.view', 'personnel.profile.update', 'personnel.assignments.manage', 'personnel.grades.manage', 'personnel.status.manage', 'admin.organization', 'admin.access'], 'description' => 'Tableur RH nominatif : profils, statuts, affectations, élévations'],
                        ['label' => 'Candidatures recrutement', 'path' => 'back-office/recruitments', 'any_permissions' => ['organization.recruitment.manage', 'admin.organization', 'admin.access'], 'description' => 'File de traitement des candidatures'],
                        ['label' => 'Analyses candidatures', 'path' => 'back-office/ressources/recrutement/analyses', 'any_permissions' => ['organization.recruitment.manage', 'admin.organization', 'admin.access'], 'description' => 'Volumes, canaux et offres liées'],
                        ['label' => 'Paramètres SLA recrutement', 'path' => 'back-office/recruitments/settings', 'any_permissions' => ['organization.recruitment.manage', 'admin.organization', 'admin.access'], 'description' => 'Seuil interne et alertes de blocage'],
                        ['label' => 'Codes d’invitation prioritaires', 'path' => 'back-office/recruitments/codes-invitation', 'any_permissions' => ['organization.recruitment.manage', 'admin.organization', 'admin.access'], 'description' => 'Accélérer une candidature (distinct des invitations e-mail)'],
                        ['label' => 'Structure & grades', 'path' => 'back-office/organisation-effectifs', 'any_permissions' => ['admin.organization', 'admin.access'], 'description' => 'Vue d’ensemble non nominative : organigramme, grades, référentiels (≠ Bureau effectifs)'],
                    ],
                ],
            ],
            'live' => [
                [
                    'id' => 'pers_roster',
                    'type' => 'recent_members',
                    'enabled' => true,
                    'title' => 'Mouvements récents',
                    'empty_message' => 'Aucune mutation récente.',
                ],
            ],
        ],
        [
            'label' => 'Formation',
            'type' => 'mega',
            'auth_only' => true,
            'module' => 'training',
            'icon' => 'academic',
            'accent' => 'emerald',
            'variant' => 'training',
            'featured' => [
                'eyebrow' => 'Parcours',
                'title' => 'Académie Athena',
                'description' => 'Catalogue, parcours, suivi et pilotage de la formation au sein de la communauté.',
                'image' => 'assets/img/nav/training.jpg',
                'image_enabled' => true,
                'image_position' => 'center',
                'overlay' => 'dark',
                'cta_label' => 'Reprendre la formation',
                'cta_path' => 'formations',
                'cta_intent' => 'resume',
            ],
            'sections' => [
                [
                    'title' => 'Catalogue & parcours',
                    'slot' => 'primary',
                    'links' => [
                        ['label' => 'Créer un entraînement', 'path' => 'formations/creer', 'any_permissions' => ['admin.access', 'training.manage', 'training.create'], 'description' => 'Assistant de publication'],
                        ['label' => 'Catalogue', 'path' => 'formations'],
                        ['label' => 'Mes parcours', 'path' => 'formations/mes-formations'],
                        ['label' => 'Sessions & suivi', 'path' => 'formations/sessions', 'description' => 'Créneaux, préparation et qualifications'],
                        ['label' => 'Espace RH et formations', 'path' => 'personnel/mon-espace-rh', 'description' => 'Charte, ancienneté et programmes de préqualification'],
                        ['label' => 'Compétences', 'path' => 'formations/competences', 'permission' => 'training.view', 'description' => 'Progression transversale et jalons'],
                        ['label' => 'Code d’accès', 'path' => 'formations/code-acces', 'permission' => 'training.view', 'description' => 'Débloquer un parcours sur invitation'],
                    ],
                ],
                [
                    'title' => 'Pilotage',
                    'slot' => 'center',
                    'links' => [
                        ['label' => 'Pilotage des formations', 'path' => 'formation', 'any_permissions' => ['admin.access', 'training.manage', 'training.assign', 'training.create', 'training.update', 'training.publish', 'training.delete'], 'description' => 'Tableau de bord LMS de la communauté'],
                        ['label' => 'Feedback post-leçon', 'path' => 'formation/feedback', 'any_permissions' => ['admin.access', 'training.manage', 'training.assign', 'training.create', 'training.update', 'training.publish', 'training.delete'], 'description' => 'Retours apprenants : difficulté, clarté, utilité'],
                        ['label' => 'Charte RH (formations)', 'path' => 'formation/charte-rh', 'any_permissions' => ['admin.access', 'training.manage', 'training.assign', 'training.create', 'training.update', 'training.publish', 'training.delete'], 'description' => 'Texte présenté aux membres avant le catalogue'],
                        ['label' => 'Studio LMS', 'path' => 'formation/studio', 'any_permissions' => ['admin.access', 'training.manage', 'training.assign', 'training.create', 'training.update', 'training.publish', 'training.delete'], 'description' => 'Édition des parcours'],
                        ['label' => 'Pilotage des compétences', 'path' => 'formation/competences/commandement', 'any_permissions' => ['training.manage', 'training.assign'], 'description' => 'Vue encadrement'],
                        ['label' => 'Validation instructeur', 'path' => 'formation/competences/instructeur', 'any_permissions' => ['training.manage', 'training.assign', 'training.submissions.grade', 'training.results.view'], 'description' => 'Évaluations à traiter'],
                        ['label' => 'Publications formation', 'path' => 'formation/publications', 'any_permissions' => ['training.publications.manage', 'training.manage', 'training.publish', 'admin.access'], 'description' => 'Versionning, change log et conformité documentaire'],
                    ],
                ],
                [
                    'title' => 'Documentation',
                    'slot' => 'secondary',
                    'links' => [
                        ['label' => 'Guide du portail', 'path' => 'documentation', 'description' => 'Documentation utilisateur intégrée au site'],
                        ['label' => 'Bibliothèque de marqueurs', 'path' => 'documentation/marqueurs', 'description' => 'Légende visuelle des symboles carte (TACMAP / Overwatch)'],
                        ['label' => 'Documentation technique du mod', 'path' => 'documentation/references', 'description' => 'Architecture Overwatch, bibliothèques et compilation'],
                        ['label' => 'Rubrique Formations (guide)', 'path' => 'documentation#formations', 'description' => 'Section du guide utilisateur'],
                        ['label' => 'Navigation & dashboard (guide)', 'path' => 'documentation#navigation-et-recherche', 'description' => 'Sommaire du guide intégré'],
                        ['label' => 'Coopérations inter-unités (guide)', 'path' => 'documentation#cooperations-inter-unites', 'description' => 'Cycle de vie, espace commun et autorisations entre communautés'],
                    ],
                ],
            ],
            'live' => [
                [
                    'id' => 'train_progress',
                    'type' => 'user_progress',
                    'enabled' => true,
                    'title' => 'Progression',
                    'empty_message' => 'Aucune progression enregistrée pour l’instant.',
                ],
            ],
        ],
        [
            'label' => 'Administration',
            'type' => 'mega',
            'auth_only' => true,
            'any_permissions' => ['admin.system', 'admin.organization', 'admin.access', 'forum.moderate', 'forum.moderate_organization', 'invitations.send', 'interteam.missions.manage', 'interteam.missions.respond', 'cooperation.missions.view', 'cooperation.missions.manage', 'cooperation.missions.create', 'cooperation.missions.respond'],
            'icon' => 'shield',
            'accent' => 'rose',
            'variant' => 'admin',
            'featured' => [
                'eyebrow' => 'Deux périmètres',
                'title' => 'Plateforme et communauté',
                'description' => 'Certains réglages concernent toute la plateforme (équipe d’infrastructure), d’autres votre organisation active. Forum, formations et courrier restent toujours cadrés par la communauté sélectionnée.',
                'image' => 'assets/img/nav/admin.jpg',
                'image_enabled' => true,
                'image_position' => 'center',
                'overlay' => 'dark',
                'cta_label' => 'Administration plateforme',
                'cta_path' => 'admin',
                'cta_permission' => 'admin.system',
                'cta_intent' => 'administer',
            ],
            'sections' => [
                [
                    'title' => 'Plateforme (site entier)',
                    'slot' => 'primary',
                    'links' => [
                        ['label' => 'Tableau de bord plateforme', 'path' => 'admin', 'permission' => 'admin.system'],
                        ['label' => 'Synthèse opérationnelle', 'path' => 'admin/ops-center', 'permission' => 'admin.system', 'description' => 'Signaux critiques et vue transversale'],
                        ['label' => 'Annuaire des communautés', 'path' => 'admin/tenants', 'permission' => 'admin.system', 'description' => 'Liste des organisations et effectifs comptes'],
                        ['label' => 'Indicateurs transverses', 'path' => 'admin/analytics', 'permission' => 'admin.system', 'description' => 'Usage, volumes et répartition sur plusieurs fenêtres de temps'],
                        ['label' => 'Formules d’accès (paliers)', 'path' => 'admin/system/subscription-plans', 'permission' => 'admin.system', 'description' => 'Noms, ordre, fonctionnalités et quotas par offre'],
                        ['label' => 'Comptes utilisateurs (site)', 'path' => 'admin/users', 'permission' => 'admin.system', 'description' => 'Annuaire de tous les comptes, filtres et activation / désactivation'],
                        ['label' => 'Restrictions réseau (site)', 'path' => 'admin/system/blocklist', 'permission' => 'admin.system', 'description' => 'Indicateurs bloqués au niveau plateforme'],
                        ['label' => 'Sanctions au niveau site', 'path' => 'admin/system/member-sanctions', 'permission' => 'admin.system', 'description' => 'Mesures sur un compte après sélection communauté et membre'],
                        ['label' => 'Lettre d’information du site', 'path' => 'admin/newsletter', 'permission' => 'admin.system', 'description' => 'Inscriptions publiques et états des contacts'],
                        ['label' => 'Rôles système', 'path' => 'admin/roles', 'permission' => 'admin.system'],
                        ['label' => 'Rôles site (affectations)', 'path' => 'admin/site-roles', 'permission' => 'admin.system'],
                        ['label' => 'Paramètres système', 'path' => 'admin/settings', 'permission' => 'admin.system'],
                        ['label' => 'Alertes plateforme', 'path' => 'admin/system/alerts', 'permission' => 'admin.system'],
                        ['label' => 'Maintenance BDD', 'path' => 'admin/maintenance', 'permission' => 'admin.system'],
                        ['label' => 'Tâches automatiques', 'path' => 'admin/system/cron', 'permission' => 'admin.system', 'description' => 'Planification et historique des travaux récurrents'],
                        ['label' => 'Journaux / audit', 'path' => 'admin/audit', 'permission' => 'admin.system'],
                        ['label' => 'Mises à jour plateforme', 'path' => 'admin/system/updates', 'permission' => 'admin.system', 'description' => 'Déposer et déployer un package de mise à jour versionné'],
                        ['label' => 'Publications et préqualification', 'path' => 'admin/system/deployment', 'permission' => 'admin.system', 'description' => 'Versions par environnement et communautés de test'],
                    ],
                ],
                [
                    'title' => 'Modules métier (communauté active)',
                    'slot' => 'secondary',
                    'links' => [
                        ['label' => 'Modpacks', 'path' => 'back-office/ressources/modpacks', 'any_permissions' => ['admin.system', 'admin.organization', 'admin.access']],
                        ['label' => 'Configuration ATAK', 'path' => 'back-office/ressources/atak-config', 'any_permissions' => ['admin.system', 'admin.organization', 'admin.access']],
                        ['label' => 'Renseignement — codes d’accès', 'path' => 'back-office/renseignement/codes', 'any_permissions' => ['admin.system', 'admin.organization', 'admin.access', 'atak.sse.grant'], 'description' => 'Délivrer des codes temporaires au portail de renseignement classifié'],
                        ['label' => 'Cycle de mission', 'path' => 'back-office/atak/cycle-mission', 'any_permissions' => ['admin.system', 'admin.organization', 'admin.access'], 'description' => 'Créer, ouvrir et clôturer une mission (briefing → carte → après-action)'],
                        ['label' => 'Comptes rendus (AAR)', 'path' => 'back-office/atak/comptes-rendus', 'any_permissions' => ['admin.system', 'admin.organization', 'admin.access'], 'description' => 'Rapports post-opération, points relevés et actions de suivi'],
                        ['label' => 'Certificats et terminaux', 'path' => 'back-office/atak/realisme', 'any_permissions' => ['admin.system', 'admin.organization', 'admin.access'], 'description' => 'Terminaux in-game, certificats et rattachement aux profils'],
                        ['label' => 'Effectifs en liaison', 'path' => 'back-office/atak/operateurs', 'any_permissions' => ['admin.system', 'admin.organization', 'admin.access'], 'description' => 'Tableur des opérateurs connectés'],
                        ['label' => 'Mod ATAK', 'path' => 'back-office/ressources/atak-mod', 'any_permissions' => ['admin.system', 'admin.organization', 'admin.access']],
                        ['label' => 'Configuration forum', 'path' => 'back-office/ressources/forum-config', 'any_permissions' => ['admin.system', 'admin.organization', 'admin.access']],
                        ['label' => 'Formations (LMS)', 'path' => 'formation', 'any_permissions' => ['admin.access', 'training.manage', 'training.assign', 'training.create', 'training.update', 'training.publish', 'training.delete']],
                        ['label' => 'Publications formation', 'path' => 'formation/publications', 'any_permissions' => ['training.publications.manage', 'training.manage', 'training.publish', 'admin.access'], 'description' => 'Back-office publications, versionning et change log'],
                        ['label' => 'Gestion documentaire', 'path' => 'documents/gestion', 'any_permissions' => ['admin.system', 'documents.upload', 'admin.access']],
                        ['label' => 'Doctrine & SOP', 'path' => 'back-office/doctrine', 'any_permissions' => ['admin.system', 'admin.organization', 'admin.access']],
                        ['label' => 'Coopérations inter-unités', 'path' => 'back-office/cooperation/missions', 'any_permissions' => ['admin.system', 'admin.organization', 'admin.access', 'interteam.missions.manage', 'interteam.missions.respond', 'cooperation.missions.view', 'cooperation.missions.manage', 'cooperation.missions.respond']],
                    ],
                ],
                [
                    'title' => 'Organisation (back-office)',
                    'slot' => 'center',
                    'links' => [
                        ['label' => 'Back-office communauté', 'path' => 'back-office', 'any_permissions' => ['admin.organization', 'admin.access']],
                        ['label' => 'Centre d’opérations admin', 'path' => 'back-office/centre-operations', 'any_permissions' => ['admin.organization', 'admin.access'], 'description' => 'File actionnable, playbooks, audit et objectifs KPI'],
                        ['label' => 'Mur opérationnel', 'path' => 'tableau-operationnel', 'permission' => 'operational.board.view', 'description' => 'Permanences et consignes publiées'],
                        ['label' => 'Pilotage du mur opérationnel', 'path' => 'back-office/tableau-operationnel', 'any_permissions' => ['operational.board.edit', 'admin.organization', 'admin.access', 'admin.system'], 'description' => 'Publication et mise à jour des entrées'],
                        ['label' => 'E-mails aux membres', 'path' => 'back-office/communications', 'any_permissions' => ['comms.email.send.orbat', 'comms.email.send.mission', 'comms.email.send.activity', 'comms.email.send.custom', 'comms.email.broadcast', 'comms.email_templates.manage', 'comms.notifications.history.view'], 'description' => 'Diffusions, modèles et groupes de destinataires'],
                        ['label' => 'Paramètres de la communauté', 'path' => 'back-office/community', 'any_permissions' => ['admin.organization', 'admin.access'], 'description' => 'Identité, modules et options'],
                        ['label' => 'Mise à niveau', 'path' => 'back-office/mise-a-niveau', 'any_permissions' => ['admin.organization', 'admin.access', 'tenant.configuration.manage', 'admin.settings.manage'], 'description' => 'Configurations complémentaires après les évolutions de la plateforme'],
                        ['label' => 'Paramètres d’inscription', 'path' => 'back-office/community/inscription', 'any_permissions' => ['admin.organization', 'admin.access'], 'description' => 'Mode de candidature et dossier'],
                        ['label' => 'Vitrine publique', 'path' => 'back-office/community/presentation', 'any_permissions' => ['admin.organization', 'admin.access'], 'description' => 'Page publique de présentation'],
                        ['label' => 'Médias de la communauté', 'path' => 'back-office/media', 'any_permissions' => ['media.view', 'media.upload', 'media.collections.manage', 'media.publish', 'media.manage', 'admin.organization', 'admin.access'], 'description' => 'Images, vidéos et collections pour la page publique'],
                        ['label' => 'Événements (gestion)', 'path' => 'back-office/events', 'any_permissions' => ['admin.organization', 'admin.access'], 'description' => 'Calendrier, RSVP, pointage et réponses nominatives par créneau'],
                        ['label' => 'Planification de mission', 'path' => 'back-office/planification', 'any_permissions' => ['admin.organization', 'admin.access'], 'description' => 'Organisation de combat, affectations et documents d’ordre'],
                        ['label' => 'Insights présence événements', 'path' => 'back-office/events/insights', 'any_permissions' => ['admin.organization', 'admin.access'], 'description' => 'KPIs présence, no-show et créneaux recommandés'],
                        ['label' => 'Dossiers de recrutement', 'path' => 'back-office/recruitments', 'any_permissions' => ['admin.organization', 'admin.access']],
                        ['label' => 'Onboarding membres', 'path' => 'back-office/onboarding-members', 'any_permissions' => ['admin.organization', 'admin.access'], 'description' => 'Suivi J7/J14, activation cross-modules et relances'],
                        ['label' => 'Rubriques du forum', 'path' => 'back-office/categories', 'any_permissions' => ['admin.organization', 'admin.access'], 'description' => 'Arborescence des catégories et sous-rubriques'],
                        ['label' => 'Nouvelle invitation', 'path' => 'back-office/invitations', 'any_permissions' => ['admin.organization', 'admin.access', 'invitations.send']],
                        ['label' => 'Invitations envoyées', 'path' => 'back-office/invitations/envoyees', 'any_permissions' => ['admin.organization', 'admin.access', 'invitations.send']],
                        ['label' => 'Utilisateurs', 'path' => 'back-office/users', 'any_permissions' => ['admin.organization', 'admin.access']],
                        ['label' => 'Bureau de suivi roleplay', 'path' => 'back-office/roleplay-followup', 'any_permissions' => ['admin.organization', 'admin.access'], 'description' => 'Tutorat, étapes d’immersion et bilans'],
                        ['label' => 'Échéances roleplay', 'path' => 'back-office/roleplay-followup/echeances', 'any_permissions' => ['admin.organization', 'admin.access'], 'description' => 'Entretiens, médical et rotations'],
                        ['label' => 'Réglages d’immersion', 'path' => 'back-office/roleplay/immersion', 'any_permissions' => ['admin.organization', 'admin.access'], 'description' => 'Activation et listes du suivi d’immersion'],
                        ['label' => 'Bureau effectifs', 'path' => 'back-office/ressources/effectifs', 'any_permissions' => ['organization.effectifs.hub.view', 'personnel.profile.update', 'personnel.assignments.manage', 'personnel.grades.manage', 'personnel.status.manage', 'admin.organization', 'admin.access'], 'description' => 'Tableur RH nominatif : profils, statuts, affectations, élévations'],
                        ['label' => 'Structure & grades', 'path' => 'back-office/organisation-effectifs', 'any_permissions' => ['admin.organization', 'admin.access'], 'description' => 'Vue d’ensemble non nominative : organigramme, grades, référentiels (≠ Bureau effectifs)'],
                        ['label' => 'Rôles et droits (communauté)', 'path' => 'back-office/roles', 'any_permissions' => ['admin.organization', 'admin.access']],
                        ['label' => 'Rôles & permissions', 'path' => 'back-office/roles-permissions', 'any_permissions' => ['admin.organization', 'admin.access', 'admin.roles.manage', 'admin.permissions.manage'], 'description' => 'Matrice d’accès par module (membres, opérations, ATAK, finances, systèmes)'],
                        ['label' => 'Gestion des accès', 'path' => 'back-office/access-management', 'any_permissions' => ['admin.organization', 'admin.access', 'admin.access.manage'], 'description' => 'Rôles, règles particulières et test d’accès'],
                        ['label' => 'Raccourcis dashboard', 'path' => 'back-office/dashboard-pins', 'any_permissions' => ['dashboard.pins.manage']],
                        ['label' => 'Profils permissions (rôles)', 'path' => 'back-office/roles/presets', 'any_permissions' => ['admin.organization', 'admin.roles.manage', 'admin.permissions.manage']],
                        ['label' => 'Rôles & fonctions (toile)', 'path' => 'back-office/roles-functions', 'any_permissions' => ['admin.organization', 'admin.roles.manage', 'admin.permissions.manage']],
                        ['label' => 'Modération forum', 'path' => 'back-office/forum-moderation', 'any_permissions' => ['forum.moderate', 'forum.moderate_organization', 'forum.topic.pin', 'forum.reports.manage', 'forum.post.edit_any', 'admin.organization', 'admin.access']],
                        ['label' => 'Modération fichiers', 'path' => 'admin/content-moderation', 'any_permissions' => ['forum.moderate', 'forum.moderate_organization', 'forum.topic.pin', 'forum.reports.manage', 'admin.organization', 'admin.access']],
                        ['label' => 'Restrictions membres (organisation)', 'path' => 'back-office/moderation', 'any_permissions' => ['admin.members.moderate'], 'description' => 'Limitations d’activité dans la communauté (formations, documents, etc.)'],
                        ['label' => 'Export conformité', 'path' => 'back-office/conformite/export-dossier', 'any_permissions' => ['admin.organization', 'admin.access'], 'description' => 'Dossier réglementaire pour audit'],
                        ['label' => 'Intégrations externes', 'path' => 'back-office/integrations', 'any_permissions' => ['admin.organization', 'admin.access'], 'description' => 'Clés d’accès (selon formule d’hébergement ; sinon page d’information pour passer à une offre adaptée)'],
                        ['label' => 'Doctrine & SOP', 'path' => 'back-office/doctrine', 'any_permissions' => ['admin.organization', 'admin.access'], 'description' => 'SOP versionnées, date d’effet et accusés de lecture'],
                        ['label' => 'Indicateurs d’activité', 'path' => 'back-office/analytics', 'any_permissions' => ['admin.organization', 'admin.access']],
                        ['label' => 'Conversion communautés', 'path' => 'back-office/analytics/conversion', 'any_permissions' => ['admin.organization', 'admin.access'], 'description' => 'Entonnoir visites → CTA → candidatures → acceptations'],
                        ['label' => 'Configuration générale', 'path' => 'back-office/configuration', 'any_permissions' => ['admin.organization', 'admin.access']],
                        ['label' => 'Audit organisation', 'path' => 'back-office/audit', 'any_permissions' => ['admin.organization', 'admin.access']],
                    ],
                ],
            ],
            'live' => [
                [
                    'id' => 'adm_alerts',
                    'type' => 'security_digest',
                    'enabled' => true,
                    'title' => 'Alertes & état',
                    'empty_message' => 'Aucun incident critique signalé.',
                ],
            ],
        ],
    ],
];
