<?php

declare(strict_types=1);

/**
 * Presets « métier » pour remplir rapidement rôles et dotations du dossier personnel.
 * Champs optionnels : seuls ceux renseignés sont appliqués côté client.
 *
 * @return list<array{
 *   id: string,
 *   label: string,
 *   description: string,
 *   primary_role?: string,
 *   job_role_slug?: string,
 *   secondary_role?: string,
 *   equipment_class?: string,
 *   kit_assigned?: string,
 *   radio_assigned?: string,
 *   vehicle_authorized?: string,
 *   weapon_specialty?: string,
 * }>
 */
return [
    [
        'id' => 'officier_operations',
        'label' => 'Officier opérations',
        'description' => 'Coordination des opérations, briefs, liaisons inter-unités.',
        'primary_role' => 'Officier opérations',
        'secondary_role' => 'Liaison',
        'equipment_class' => 'Command & Control',
        'kit_assigned' => 'C2 léger / tablette mission',
        'radio_assigned' => 'PRC-152',
        'vehicle_authorized' => 'Utility / VT4',
        'weapon_specialty' => 'Carabine / pistolet',
    ],
    [
        'id' => 'chef_section',
        'label' => 'Chef de section',
        'description' => 'Encadrement d’une section d’infanterie.',
        'job_role_slug' => 'chef-de-section',
        'primary_role' => 'Chef de section',
        'secondary_role' => 'Instruc tireur',
        'equipment_class' => 'Rifleman Medium',
        'kit_assigned' => 'Assault + médical léger',
        'radio_assigned' => 'PRC-152',
        'weapon_specialty' => 'Fusil d’assaut / grenade',
    ],
    [
        'id' => 'fusilier',
        'label' => 'Fusilier',
        'description' => 'Combattant polyvalent en section.',
        'job_role_slug' => 'fusilier',
        'primary_role' => 'Fusilier',
        'secondary_role' => '',
        'equipment_class' => 'Rifleman Light',
        'kit_assigned' => 'Standard',
        'radio_assigned' => 'PRC-343',
        'weapon_specialty' => 'Fusil d’assaut',
    ],
    [
        'id' => 'jtac',
        'label' => 'JTAC / FO',
        'description' => 'Guidage feu indirect et appuis aériens.',
        'primary_role' => 'JTAC',
        'secondary_role' => 'Observateur avancé',
        'equipment_class' => 'JTAC',
        'kit_assigned' => 'Laser désignation / binos',
        'radio_assigned' => 'PRC-117 / PRC-152',
        'weapon_specialty' => 'Carabine compacte',
    ],
    [
        'id' => 'medic',
        'label' => 'Medic / secouriste',
        'description' => 'Soutien sanitaire au plus près du combat.',
        'job_role_slug' => 'medic',
        'primary_role' => 'Medic',
        'secondary_role' => 'Secouriste',
        'equipment_class' => 'Medic',
        'kit_assigned' => 'Sac médical TCCC',
        'radio_assigned' => 'PRC-343',
        'weapon_specialty' => 'Pistolet / carabine légère',
    ],
    [
        'id' => 'pilote',
        'label' => 'Pilote / équipage',
        'description' => 'Conduite d’aéronef ou équipage spécialisé.',
        'primary_role' => 'Pilote',
        'secondary_role' => 'Navigateur',
        'equipment_class' => 'Aviation',
        'kit_assigned' => 'Hélio / NVG',
        'radio_assigned' => 'Radio aviation',
        'vehicle_authorized' => 'Hélicoptère / transport',
        'weapon_specialty' => 'Pistolet de bord',
    ],
    [
        'id' => 'logistique',
        'label' => 'Logistique',
        'description' => 'Ravitaillement, maintenance légère, transport.',
        'job_role_slug' => 'logistique-r',
        'primary_role' => 'Logistique',
        'secondary_role' => 'Conducteur',
        'equipment_class' => 'Support',
        'kit_assigned' => 'Outils / caisses',
        'radio_assigned' => 'PRC-343',
        'vehicle_authorized' => 'Camion / MRAP cargo',
        'weapon_specialty' => 'Pistolet / fusil compact',
    ],
    [
        'id' => 'renseignement',
        'label' => 'Renseignement',
        'description' => 'Collecte, analyse, diffusion contrôlée.',
        'primary_role' => 'Officier renseignement',
        'secondary_role' => 'Analyste',
        'equipment_class' => 'ISR',
        'kit_assigned' => 'Capteurs / photo',
        'radio_assigned' => 'PRC-152',
        'weapon_specialty' => 'PDW / discret',
    ],
];
