/*
    Libellés français des marqueurs, repris du catalogue web (public/assets/js/arma-marker-catalog.js)
    pour que le téléphone et Athena nomment les marqueurs pareil. Clé : classe CfgMarkers en minuscules.
*/
private _cache = uiNamespace getVariable ["COMSPEC_ATAK_MarkerLabels", createHashMap];
if ((count _cache) > 0) exitWith { _cache };
_cache = createHashMapFromArray [
    ["mil_dot", "Repère"],
    ["mil_box", "Carré"],
    ["mil_triangle", "Triangle"],
    ["mil_circle", "Cercle"],
    ["mil_marker", "Repère"],
    ["mil_flag", "Drapeau"],
    ["mil_arrow", "Flèche"],
    ["mil_arrow2", "Flèche double"],
    ["mil_ambush", "Embuscade"],
    ["mil_destroy", "Destruction"],
    ["mil_objective", "Objectif"],
    ["mil_unknown", "Inconnu"],
    ["mil_warning", "Alerte"],
    ["mil_join", "Ralliement"],
    ["mil_pickup", "Récupération"],
    ["mil_start", "Départ"],
    ["mil_end", "Arrivée"],
    ["hd_dot", "Repère"],
    ["hd_box", "Carré"],
    ["hd_triangle", "Triangle"],
    ["hd_circle", "Cercle"],
    ["hd_flag", "Drapeau"],
    ["hd_arrow", "Flèche"],
    ["hd_arrow2", "Flèche double"],
    ["hd_ambush", "Embuscade"],
    ["hd_destroy", "Destruction"],
    ["hd_objective", "Objectif"],
    ["hd_unknown", "Inconnu"],
    ["hd_warning", "Alerte"],
    ["hd_join", "Ralliement"],
    ["hd_pickup", "Récupération"],
    ["hd_start", "Départ"],
    ["hd_end", "Arrivée"],
    ["loc_hospital", "Poste médical"],
    ["loc_fuelstation", "Station-service"],
    ["loc_church", "Église"],
    ["loc_transmitter", "Antenne"],
    ["loc_lighthouse", "Phare"],
    ["loc_power", "Électricité"],
    ["loc_stack", "Cheminée"],
    ["loc_bunker", "Bunker"],
    ["loc_quay", "Quai"],
    ["loc_busstop", "Arrêt"],
    ["loc_tourism", "Tourisme"],
    ["loc_viewpoint", "Point de vue"],
    ["loc_rockarea", "Rocher"],
    ["loc_fortification", "Fortification"],
    ["loc_crossroad", "Carréfour"],
    ["empty", "Vide"],
    ["flag", "Drapeau"],
    ["contact_arrow1", "Contact flèche"],
    ["contact_arrow2", "Contact flèche"],
    ["contact_arrow3", "Contact flèche"],
    ["contact_dots1", "Contact"],
    ["contact_circle1", "Contact cercle"],
    ["contact_pencilcircle1", "Contact"],
    ["b_inf", "Infanterie amie"],
    ["o_inf", "Infanterie hostile"],
    ["n_inf", "Infanterie inconnue"],
    ["c_inf", ""],
    ["u_inf", ""],
    ["b_mech_inf", "Infanterie mécanisée amie"],
    ["o_mech_inf", "Infanterie mécanisée hostile"],
    ["n_mech_inf", "Infanterie mécanisée inconnue"],
    ["c_mech_inf", ""],
    ["u_mech_inf", ""],
    ["b_motor_inf", "Infanterie motorisée amie"],
    ["o_motor_inf", "Infanterie motorisée hostile"],
    ["n_motor_inf", ""],
    ["c_motor_inf", ""],
    ["u_motor_inf", ""],
    ["b_armor", "Blindé ami"],
    ["o_armor", "Blindé hostile"],
    ["n_armor", "Blindé inconnu"],
    ["c_armor", ""],
    ["u_armor", ""],
    ["b_recon", "Reconnaissance amie"],
    ["o_recon", "Reconnaissance hostile"],
    ["n_recon", "Reconnaissance inconnue"],
    ["c_recon", ""],
    ["u_recon", ""],
    ["b_air", "Hélicoptère ami"],
    ["o_air", "Hélicoptère hostile"],
    ["n_air", ""],
    ["c_air", ""],
    ["u_air", ""],
    ["b_plane", ""],
    ["o_plane", ""],
    ["n_plane", ""],
    ["c_plane", ""],
    ["u_plane", ""],
    ["b_uav", ""],
    ["o_uav", ""],
    ["n_uav", ""],
    ["c_uav", ""],
    ["u_uav", ""],
    ["b_naval", ""],
    ["o_naval", ""],
    ["n_naval", ""],
    ["c_naval", ""],
    ["u_naval", ""],
    ["b_art", ""],
    ["o_art", ""],
    ["n_art", ""],
    ["c_art", ""],
    ["u_art", ""],
    ["b_mortar", ""],
    ["o_mortar", ""],
    ["n_mortar", ""],
    ["c_mortar", ""],
    ["u_mortar", ""],
    ["b_antiair", ""],
    ["o_antiair", ""],
    ["n_antiair", ""],
    ["c_antiair", ""],
    ["u_antiair", ""],
    ["b_support", ""],
    ["o_support", ""],
    ["n_support", ""],
    ["c_support", ""],
    ["u_support", ""],
    ["b_maint", ""],
    ["o_maint", ""],
    ["n_maint", ""],
    ["c_maint", ""],
    ["u_maint", ""],
    ["b_med", ""],
    ["o_med", ""],
    ["n_med", ""],
    ["c_med", ""],
    ["u_med", ""],
    ["b_hq", ""],
    ["o_hq", ""],
    ["n_hq", ""],
    ["c_hq", ""],
    ["u_hq", ""],
    ["b_ordnance", ""],
    ["o_ordnance", ""],
    ["n_ordnance", ""],
    ["c_ordnance", ""],
    ["u_ordnance", ""],
    ["b_installation", ""],
    ["o_installation", ""],
    ["n_installation", ""],
    ["c_installation", ""],
    ["u_installation", ""],
    ["b_unknown", ""],
    ["o_unknown", ""],
    ["n_unknown", ""],
    ["c_unknown", ""],
    ["u_unknown", ""],
    ["b_service", ""],
    ["o_service", ""],
    ["n_service", ""],
    ["c_service", ""],
    ["u_service", ""],
    ["b_car", ""],
    ["o_car", ""],
    ["n_car", ""],
    ["c_car", ""],
    ["u_car", ""],
    ["b_ship", ""],
    ["o_ship", ""],
    ["n_ship", ""],
    ["c_ship", ""],
    ["u_ship", ""],
    ["mplus_markers", "MarkersPlus"],
    ["mplus_aapoint", "Point générique"],
    ["mplus_ambush", "Embuscade"],
    ["mplus_attackbyfire", "Attaque par le feu"],
    ["mplus_breach", "Brèche"],
    ["mplus_bypass", "Contourner"],
    ["mplus_clear", "Nettoyer"],
    ["mplus_disengage", "Désengager"],
    ["mplus_exfiltrate", "Exfiltrer"],
    ["mplus_followassume", "Suivre et prendre le relais"],
    ["mplus_followsupport", "Suivre et appuyer"],
    ["mplus_occupy", "Occuper"],
    ["mplus_retain", "Conserver"],
    ["mplus_secure", "Sécuriser"],
    ["mplus_seize", "Saisir"],
    ["mplus_supportbyfire", "Appui par le feu"],
    ["mplus_block", "Bloquer"],
    ["mplus_canalize", "Canaliser"],
    ["mplus_contain", "Contenir"],
    ["mplus_destroy", "Détruire"],
    ["mplus_disrupt", "Perturber"],
    ["mplus_fix", "Fixer"],
    ["mplus_isolate", "Isoler"],
    ["mplus_interdict", "Interdire"],
    ["mplus_neutralize", "Neutraliser"],
    ["mplus_supress", "Supprimer"],
    ["mplus_turn", "Faire pivoter"],
    ["mplus_cordonknock", "Cordon et frappe"],
    ["mplus_cordonsearch", "Cordon et fouille"],
    ["mplus_guard", "Garde"],
    ["mplus_screen", "Ã‰cran"],
    ["mplus_cover", "Couverture"],
    ["mplus_feintattack", "Flèche feinte"],
    ["mplus_mainattack", "Flèche d'attaque principale"],
    ["mplus_phaseline", "Ligne de phase"],
    ["mplus_checkpoint", "Point de contrÃ´le"],
    ["mplus_linkuppoint", "Point de jonction"],
    ["mplus_passagepoint", "Point de passage"],
    ["mplus_rallypoint", "Point de ralliement"],
    ["mplus_releasepoint", "Point de libÃ©ration"],
    ["mplus_startpoint", "Point de depart"],
    ["mplus_departurepoint", "Point de depart opÃ©rationnel"],
    ["mplus_civpoint", "Point de regroupement civils"],
    ["mplus_iprp", "Point recuperation personnel isolÃ©"],
    ["mplus_sarpoint", "Point SAR"],
    ["mplus_ammopoint", "Point munitions"],
    ["mplus_ccppoint", "Point de ramassage blessÃ©s"],
    ["mplus_medevac", "Point evacuation mÃ©dicale"],
    ["mplus_r3p", "Point R3P"],
    ["mplus_waypoint", "Waypoint"]
];
uiNamespace setVariable ["COMSPEC_ATAK_MarkerLabels", _cache];
_cache
