params [["_from", ""], ["_body", ""], ["_time", "--:--"]];
if (!hasInterface || {_from isEqualTo ""}) exitWith {};
private _data = uiNamespace getVariable ["COMSPEC_ATAK_Data", createHashMap];
private _p2p = _data getOrDefault ["p2p", []];
_p2p pushBack createHashMapFromArray [["peer", _from], ["dir", "in"], ["body", _body], ["time", _time], ["read", false]];
while {(count _p2p) > 200} do { _p2p deleteAt 0; };
_data set ["p2p", _p2p];
private _preview = [_body, (_body select [0, 60]) + "…"] select ((count _body) > 60);
["MESSAGE", format ["%1 : %2", _from, _preview], 5, 40] call comspec_atak_native_fnc_notify;
if (isNull (findDisplay 88500)) then { systemChat format ["[ATAK] Message de %1", _from]; };
