params ["_display", ["_exitCode", 0]];
[] call comspec_atak_native_fnc_schedulerStop;
private _state = uiNamespace getVariable ["COMSPEC_ATAK_State", createHashMap];
_state set ["display", displayNull];
private _chat = uiNamespace getVariable ["COMSPEC_ATAK_ChatEdit", controlNull];
if (!isNull _chat) then { uiNamespace setVariable ["COMSPEC_ATAK_ChatDraft", ctrlText _chat]; };
uiNamespace setVariable ["COMSPEC_ATAK_ChatEdit", controlNull];
uiNamespace setVariable ["COMSPEC_ATAK_PageControls", []];
uiNamespace setVariable ["COMSPEC_ATAK_DockControls", []];
uiNamespace setVariable ["COMSPEC_ATAK_ToastControls", []];
profileNamespace setVariable ["COMSPEC_ATAK_LastPage", _state getOrDefault ["activePage", "LAUNCHER"]];
saveProfileNamespace;
uiNamespace setVariable ["COMSPEC_ATAK_Display", displayNull];
["INFO", "UI", format ["Display closed (%1); handlers cleaned", _exitCode]] call comspec_atak_native_fnc_log;
