<?php declare(strict_types=1); ob_start(); $h=static fn(mixed $v):string=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8'); ?>
<div class="breadcrumb">Athena / SSE / Dossiers d’intérêt / <strong>Ouverture</strong></div>
<div class="page-heading"><div><div class="page-heading-overline">Acquisition // Levée de doute</div><h1>Ouvrir un dossier d’intérêt</h1><p>Le statut initial sera « Signalement reçu ». Il ne crée aucune personne identifiée.</p></div><div class="page-reference"><strong>Nouveau // SSE-DI</strong>Référence attribuée automatiquement</div></div>
<form method="post" action="<?= $h(url('atak/sse/interet')) ?>"><?= \App\Core\Csrf::field() ?>
<section class="panel"><div class="panel-header"><div class="panel-title"><span class="panel-index">01</span>Hypothèse initiale</div></div><div class="panel-body"><div class="grid-2"><div><label>Désignation temporaire *</label><input name="temporary_designation" required placeholder="INDIVIDU-ALPHA-017"></div><div><label>Alias supposé</label><input name="suspected_alias"></div><div><label>Sexe apparent</label><input name="apparent_sex"></div><div><label>Tranche d’âge estimée</label><input name="estimated_age_range" placeholder="30–40 ans"></div><div><label>Nationalité supposée</label><input name="suspected_nationality"></div><div><label>Affiliation supposée</label><input name="suspected_affiliation"></div><div><label>Niveau de confiance initial</label><select name="confidence_level"><?php foreach($confidenceLevels as $k=>$v): ?><option value="<?= $h($k) ?>"><?= $h($v) ?></option><?php endforeach ?></select></div><div><label>Intérêt opérationnel</label><select name="interest_level"><?php foreach($interestLevels as $k=>$v): ?><option value="<?= $h($k) ?>"><?= $h($v) ?></option><?php endforeach ?></select></div></div><label>Motif d’ouverture *</label><textarea name="opening_reason" required></textarea><label>Unité ou opérateur à l’origine</label><input name="origin_operator"></div></section>
<section class="panel"><div class="panel-header"><div class="panel-title"><span class="panel-index">02</span>Éléments observés</div></div><div class="panel-body"><p class="sse-note">Décrire les photographies, biométries partielles, signes distinctifs, tenue, véhicule, identifiants, lieux, accompagnants et coordonnées.</p><textarea name="observed_elements" rows="8"></textarea><div class="grid-2"><div><label>Date et heure d’acquisition</label><input type="datetime-local" name="acquisition_at"></div><div><label>Mission d’origine</label><input name="mission_label"></div></div></div></section>
<section class="panel"><div class="panel-header"><div class="panel-title"><span class="panel-index">03</span>Analyse</div></div><div class="panel-body"><div class="grid-2"><div><label>Faits établis</label><textarea name="analysis_facts"></textarea></div><div><label>Éléments supposés / hypothèses</label><textarea name="analysis_assumptions"></textarea></div><div><label>Contradictions</label><textarea name="analysis_contradictions"></textarea></div><div><label>Questions restantes</label><textarea name="analysis_questions"></textarea></div><div><label>Besoins de collecte</label><textarea name="collection_needs"></textarea></div><div><label>Risque opérationnel</label><textarea name="operational_risk"></textarea></div></div><label>Recommandations de contrôle</label><textarea name="recommendations"></textarea></div></section>
<section class="panel"><div class="panel-header"><div class="panel-title"><span class="panel-index">04</span>Traçabilité</div></div><div class="panel-body"><div class="grid-2"><div><label>Source</label><input name="source_label"></div><div><label>Fiabilité de la source</label><select name="source_reliability"><option value="">Non évaluée</option><option>A — fiable</option><option>B — généralement fiable</option><option>C — assez fiable</option><option>D — peu fiable</option><option>E — non fiable</option></select></div></div><button class="btn" type="submit">Enregistrer le signalement</button></div></section></form>
<?php $sseContent=ob_get_clean(); require __DIR__.'/_layout.php';
