<?php declare(strict_types=1); ob_start(); $h = static fn(mixed $v): string => htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); ?>
<div class="breadcrumb">Athena / SSE / <strong>Dossiers d’intérêt</strong></div>
<div class="page-heading"><div><div class="page-heading-overline">SSE-DI // Qualification</div><h1>Dossiers d’intérêt</h1><p>Qualification, collecte et consolidation des sujets d’intérêt. Une hypothèse de travail n’est jamais une identité confirmée.</p></div><div class="page-reference"><strong>Vue // File opérateur</strong>Réf. ATH-SSE-DI</div></div>
<div class="security-notice"><div class="security-notice-code">DOCTRINE</div><div><strong>Validation humaine obligatoire</strong><span>Les propositions automatiques aident l’analyse. Elles ne valent ni identification, ni validation, ni preuve.</span></div></div>
<form class="toolbar" method="get"><div class="toolbar-field"><label for="q">Recherche</label><input id="q" name="q" value="<?= $h($filters['q']) ?>" placeholder="Référence, désignation, alias"></div><div class="toolbar-field"><label for="status">État de traitement</label><select id="status" name="status"><option value="">Tous les états</option><?php foreach($statuses as $key=>$label): ?><option value="<?= $h($key) ?>" <?= $filters['status']===$key?'selected':'' ?>><?= $h($label) ?></option><?php endforeach ?></select></div><div class="toolbar-actions"><button class="btn">Filtrer</button><?php if($canManage): ?><a class="btn btn--ghost" href="<?= $h(url('atak/sse/interet/nouveau')) ?>">+ Ouvrir un dossier d’intérêt</a><?php endif ?></div></form>
<section class="panel"><div class="panel-header"><div class="panel-title"><span class="panel-index">DI.01</span>File des sujets d’intérêt</div><div class="panel-meta"><?= count($interestCases) ?> résultat(s)</div></div>
<?php if($interestCases===[]): ?><div class="empty-state"><div class="empty-state-inner"><div class="empty-symbol">DI</div><strong>Aucun dossier d’intérêt</strong><p>Ouvrez un dossier à partir d’un signalement brut ou d’une acquisition terrain, sans conclure prématurément à une identité.</p><?php if($canManage): ?><a class="btn" href="<?= $h(url('atak/sse/interet/nouveau')) ?>">Ouvrir un dossier d’intérêt</a><?php endif ?></div></div>
<?php else: ?><div class="table-wrap"><table><thead><tr><th>Référence</th><th>Sujet d’intérêt</th><th>État</th><th>Confiance</th><th>Intérêt</th><th>Dernière activité</th><th></th></tr></thead><tbody><?php foreach($interestCases as $case): ?><tr><td class="record-id"><?= $h($case['reference_code']) ?></td><td><span class="record-name"><?= $h($case['temporary_designation']) ?></span><span class="record-sub"><?= $h($case['suspected_alias'] ?: 'Alias non renseigné') ?></span></td><td><span class="badge"><?= $h($case['status_label']) ?></span></td><td><?= $h($case['confidence_label']) ?></td><td><span class="badge <?= $case['interest_level']==='critique'?'badge--red':($case['interest_level']==='prioritaire'?'badge--amber':'') ?>"><?= $h($case['interest_label']) ?></span></td><td class="record-id"><?= $h(substr((string)$case['updated_at'],0,16)) ?></td><td><a class="link" href="<?= $h(url('atak/sse/interet/'.$case['id'])) ?>">Ouvrir →</a></td></tr><?php endforeach ?></tbody></table></div><?php endif ?>
</section>
<?php $sseContent=ob_get_clean(); require __DIR__.'/_layout.php';
