<?php

declare(strict_types=1);

namespace Tests\Unit;

use PHPUnit\Framework\TestCase;

final class AtakOverwatchBetaAssetTest extends TestCase
{
    public function testBetaWorkspaceRouteAndCoreInteractionsArePresent(): void
    {
        $routes = file_get_contents(dirname(__DIR__, 2) . '/routes/web.php');
        $view = file_get_contents(dirname(__DIR__, 2) . '/views/atak-overwatch-beta.php');
        $dashboardAside = file_get_contents(dirname(__DIR__, 2) . '/views/partials/dashboard_aside.php');
        $sidebar = file_get_contents(dirname(__DIR__, 2) . '/views/partials/ath_sidebar_nav.php');

        self::assertIsString($routes);
        self::assertIsString($view);
        self::assertIsString($dashboardAside);
        self::assertIsString($sidebar);
        self::assertStringContainsString("'/-ATAK-OVERWATCH-Beta'", $routes);
        self::assertStringContainsString("'/atak-overwatch-beta'", $routes);
        self::assertStringContainsString("url('-ATAK-OVERWATCH-Beta')", $dashboardAside);
        self::assertStringContainsString("'Overwatch Beta'", $sidebar);
        self::assertStringNotContainsString("require base_path('views/atak.php')", $view);
        self::assertStringContainsString('class="ow-shell"', $view);
        self::assertStringContainsString('id="ow-map"', $view);
        self::assertStringContainsString("[AtakController::class, 'overwatchBeta']", $routes);

        $atakController = file_get_contents(dirname(__DIR__, 2) . '/app/Controllers/Web/AtakController.php');
        $atakApiController = file_get_contents(dirname(__DIR__, 2) . '/app/Controllers/Api/AtakApiController.php');
        $overwatchJs = file_get_contents(dirname(__DIR__, 2) . '/public/assets/js/atak-overwatch-beta.js');
        $gotakJs = file_get_contents(dirname(__DIR__, 2) . '/public/assets/js/atak-overwatch-gotak.js');
        $realtimeJs = file_get_contents(dirname(__DIR__, 2) . '/public/assets/js/atak-realtime.js');
        $p2Js = file_get_contents(dirname(__DIR__, 2) . '/public/assets/js/atak-overwatch-p2.js');
        $recipe = file_get_contents(dirname(__DIR__, 2) . '/scripts/qa/atak-overwatch-beta-recipe.sh');
        self::assertIsString($atakController);
        self::assertIsString($atakApiController);
        self::assertIsString($overwatchJs);
        self::assertIsString($gotakJs);
        self::assertIsString($realtimeJs);
        self::assertIsString($p2Js);
        self::assertIsString($recipe);
        self::assertStringContainsString("\$params['_overwatch_beta'] = true", $atakController);
        self::assertStringContainsString("'atakOverwatchBeta' => !empty(\$params['_overwatch_beta'])", $atakController);
        self::assertStringContainsString('window.ATAK_OVERWATCH_BETA = true', $view);
        self::assertStringContainsString('atak-overwatch-beta.css', $view);
        self::assertStringContainsString("'/api/units?mapId='", $overwatchJs);
        self::assertStringContainsString('extra.movement_heading', $overwatchJs);
        self::assertStringContainsString('extra.speed_ms', $overwatchJs);
        self::assertStringContainsString('extra.asl_z', $overwatchJs);
        self::assertStringContainsString('extra.link_state', $overwatchJs);
        self::assertStringContainsString('extra.transmit_mode', $overwatchJs);
        self::assertStringContainsString('source_arma', $overwatchJs);
        self::assertStringContainsString("kv('Liaison'", $overwatchJs);
        self::assertStringContainsString("kv('Transmission'", $overwatchJs);
        self::assertStringContainsString('L.map(\'ow-map\'', $overwatchJs);
        self::assertStringContainsString('window.MGRS_CRS', $overwatchJs);
        self::assertStringContainsString('athena:atak-fond-look', $overwatchJs);
        self::assertStringContainsString('data-ow-look', $view);
        self::assertStringContainsString('id="ow-settings"', $view);
        self::assertStringContainsString('id="ow-chat"', $view);
        self::assertStringContainsString('window.OverwatchBeta', $overwatchJs);
        self::assertStringContainsString('window.ATAK_CSRF', $view);
        self::assertStringContainsString('atak-overwatch-gotak.js', $view);
        self::assertStringContainsString("'/api/nine-line'", $overwatchJs);
        self::assertStringContainsString('patients_t1_urgent', $overwatchJs);
        self::assertStringContainsString("'/api/sse/notes/web'", $gotakJs);
        self::assertStringContainsString("'/api/atak/terrain/profile'", $gotakJs);
        self::assertStringContainsString("'/api/atak/activity'", $gotakJs);
        self::assertStringContainsString('data-tool="eta"', $view);
        self::assertStringContainsString('id="ow-geofence"', $view);
        self::assertStringContainsString('id="ow-squad-links"', $view);
        self::assertStringContainsString('data-tool="circle"', $view);
        self::assertStringContainsString('data-tool="los"', $view);
        self::assertStringContainsString('data-tool="po"', $view);
        self::assertStringContainsString('placeReachPoint', $overwatchJs);
        self::assertStringContainsString('/api/atak/waypoint-routes', $overwatchJs);
        self::assertStringContainsString('id="ow-group-task-host"', $view);
        self::assertStringContainsString('ow-group-task-form', $overwatchJs);
        self::assertStringContainsString('submitGroupTask', $overwatchJs);
        self::assertStringContainsString('/api/atak/orders', $overwatchJs);
        self::assertStringContainsString('data-squad-task', $overwatchJs);
        self::assertStringContainsString('id="ow-fs-alert-host"', $view);
        self::assertStringContainsString('submitFullscreenAlert', $overwatchJs);
        self::assertStringContainsString("order_type: 'NOTIFY_FULL'", $overwatchJs);
        self::assertStringContainsString('data-tool="rally"', $view);
        self::assertStringContainsString('placeRallyPoint', $overwatchJs);
        self::assertStringContainsString("zone_type: 'RALLY_POINT'", $overwatchJs);
        self::assertStringContainsString('/api/atak/zones', $overwatchJs);
        self::assertStringContainsString('id="ow-rally-markers"', $view);
        self::assertStringContainsString("'tacticalZonesDestroy'", $routes);
        self::assertStringContainsString('id="ow-follow"', $view);
        self::assertStringContainsString('id="ow-po-markers"', $view);
        self::assertStringContainsString("'/api/atak/markers/'", $overwatchJs);
        self::assertStringContainsString('loadPoMarkers', $overwatchJs);
        self::assertStringContainsString("'/api/atak/terrain/los'", $overwatchJs);
        self::assertStringContainsString('altitudeAtPoint', $overwatchJs);
        self::assertStringContainsString('observer_from_unit', $overwatchJs);
        self::assertStringContainsString('data-chat-tab="squads"', $view);
        self::assertStringContainsString('renderSquadLinks', $overwatchJs);
        self::assertStringContainsString('id="ow-empty"', $view);
        self::assertStringContainsString('id="ow-empty-dismiss"', $view);
        self::assertStringContainsString('Masquer', $view);
        self::assertStringContainsString('dismissEmptyNotice', $overwatchJs);
        self::assertStringContainsString('athena:overwatch-empty-dismissed', $overwatchJs);
        self::assertStringContainsString('id="ow-disclaimer"', $view);
        self::assertStringContainsString('atak-map-crs.js', $view);
        self::assertStringContainsString('data-view="comms"', $view);
        self::assertStringContainsString("'/api/chat?mapId='", $overwatchJs);
        self::assertStringContainsString('ow-unread', $overwatchJs);
        self::assertStringContainsString('deleteOwnChat', $overwatchJs);
        self::assertStringContainsString('/api/chat/purge', $overwatchJs);
        self::assertStringContainsString('Vider le fil', $view);
        self::assertStringContainsString("delete('/api/chat/{id}'", $routes);
        self::assertStringContainsString("'/api/pings'", $overwatchJs);
        self::assertStringContainsString('renderMap();', $overwatchJs);
        self::assertStringContainsString('renderList();', $overwatchJs);
        self::assertStringContainsString('syncStatus(true)', $overwatchJs);
        self::assertStringContainsString('window.__OVERWATCH_STANDALONE__', $overwatchJs);
        self::assertStringContainsString("'/api/atak/stream'", $routes);
        self::assertStringContainsString('text/event-stream', $atakApiController);
        self::assertStringContainsString("new EventSource(base + '/api/atak/stream", $realtimeJs);
        self::assertStringContainsString('setRealtimeActive(active)', $realtimeJs);
        self::assertSame('support', \App\Support\AtakChatChannel::normalizeKey('SUPPORT'));
        self::assertSame('Support technique', \App\Support\AtakChatChannel::labelFor('support'));
        self::assertStringContainsString("FORMAT = 'athena-overwatch-mission'", $p2Js);
        self::assertStringContainsString('MAX_IMPORT_SHAPES = 50', $p2Js);
        self::assertStringContainsString('ATAKMapShapes.createShape', $p2Js);
        self::assertStringContainsString('stream anonyme refusé', $recipe);
        self::assertStringContainsString("event: units", $recipe);
        self::assertStringNotContainsString('ALPHA 1-1', $view);
        self::assertStringNotContainsString('CONTACT C-018', $view);
        self::assertStringContainsString('Space+Grotesk', $view);
        self::assertStringContainsString('IBM+Plex+Sans', $view);
        self::assertStringContainsString('data-ow-collapse-settings', $view);
        self::assertStringContainsString('id="ow-stats"', $view);
        self::assertStringContainsString('id="ow-presence-heat"', $view);
        self::assertStringContainsString('id="atak-terrain-hillshade"', $view);
        self::assertStringContainsString('id="atak-terrain-slope"', $view);
        self::assertStringContainsString('id="atak-scene-buildings"', $view);
        self::assertStringContainsString('atak-terrain.js', $view);
        self::assertStringContainsString('atak-scene-3d.js', $view);
        self::assertStringContainsString('arma-map-markers.js', $view);
        self::assertStringContainsString('id="ow-chat-raw"', $view);
        self::assertStringContainsString('is-settings-collapsed', $overwatchJs);
        self::assertStringContainsString("'/api/atak/markers?mapId='", $overwatchJs);
        self::assertStringContainsString("'/api/atak/terminals'", $overwatchJs);
        self::assertStringContainsString('parseCommsBody', $overwatchJs);
        self::assertStringContainsString('placeContextMenu', $overwatchJs);
        self::assertStringContainsString('isDragTool', $overwatchJs);
        self::assertStringContainsString('renderPresenceHeat', $overwatchJs);
        self::assertStringNotContainsString('ATAKAerial.setMode', $overwatchJs);
        self::assertStringNotContainsString('workspace.classList.toggle(\'is-tools\'', $overwatchJs);
        self::assertStringContainsString('kv(\'Certificat\'', $overwatchJs);
        self::assertStringContainsString('kv(\'Batterie\'', $overwatchJs);
        self::assertStringContainsString('kv(\'Adresse réseau\'', $overwatchJs);
        self::assertStringContainsString('maskIpForDisplay', $overwatchJs);
        self::assertStringContainsString('data-ctx="delete"', $view);
        self::assertStringContainsString('hitDeletable', $overwatchJs);
        self::assertStringContainsString('deleteMapTarget', $overwatchJs);
        self::assertStringContainsString('bindLayerContext', $overwatchJs);
        self::assertStringContainsString("'/api/map-shapes/'", $overwatchJs);
        self::assertStringContainsString("'/api/pings/'", $overwatchJs);
        self::assertStringNotContainsString("action: 'send'", $overwatchJs);
        self::assertStringContainsString('data-send-photo', $overwatchJs);
        self::assertStringContainsString('atak:mapready', $overwatchJs);
        self::assertStringContainsString('fanLatLng', $overwatchJs);
        self::assertStringContainsString('armaDuplicatesBft', $overwatchJs);
        self::assertStringContainsString('Au même point', $overwatchJs);
        self::assertStringContainsString('id="ow-show-labels"', $view);
        self::assertStringContainsString('Sans groupe', $overwatchJs);
        self::assertStringNotContainsString("clean(unit.call_sign || unit.callsign || unit.name || unit.label, 'CONTACT')", $overwatchJs);
        self::assertStringContainsString('tooOldToShow', $overwatchJs);
        self::assertStringContainsString('STALE_HIDE_SEC', $overwatchJs);
        self::assertStringContainsString('is-squad-pulse', $overwatchJs);
        self::assertStringContainsString('id="ow-squad-color"', $view);
        self::assertStringContainsString('is-offline', $overwatchJs);
        self::assertStringContainsString('data-ow-rail-more', $view);
        self::assertStringContainsString('id="ow-rail-extra"', $view);
        self::assertStringContainsString('aria-controls="ow-rail-extra"', $view);
        self::assertStringContainsString('data-ow-more', $view);
        self::assertStringContainsString('data-ow-replay', $view);
        self::assertStringNotContainsString('class="ow-map-tools"', $view);
        self::assertStringContainsString('ow-map-tools{display:none', $view);
        self::assertStringContainsString('Assistance technique', $view);
        self::assertStringContainsString('ow-fil-empty', $overwatchJs);
        self::assertStringContainsString('prioLabel', $overwatchJs);
        self::assertStringNotContainsString('Fil — Comms', $view);
        $css = file_get_contents(dirname(__DIR__, 2) . '/public/assets/css/atak-overwatch-beta.css');
        self::assertIsString($css);
        self::assertStringContainsString('--ow-chat-inset', $css);
        self::assertStringContainsString('.ow-rail-extra', $css);
        self::assertStringContainsString('.ow-map-tools{display:none', $css);
        self::assertStringContainsString('.ow-ctx-danger', $css);
        self::assertStringContainsString('id="ow-ui-font"', $view);
        self::assertStringContainsString('id="ow-grid-overlay"', $view);
        self::assertStringContainsString('id="ow-nvg"', $view);
        self::assertStringContainsString('data-ow-notes', $view);
        self::assertStringContainsString('data-tool="goto"', $view);
        self::assertStringContainsString('data-tool="range"', $view);
        self::assertStringContainsString('atak-overwatch-tools.js', $view);
        self::assertStringContainsString('patchDisplayPrefs', $overwatchJs);
        $toolsJs = file_get_contents(dirname(__DIR__, 2) . '/public/assets/js/atak-overwatch-tools.js');
        self::assertIsString($toolsJs);
        self::assertStringContainsString('drawGrid', $toolsJs);
        self::assertStringContainsString('placeRange', $toolsJs);
        self::assertStringContainsString('applyFonts', $toolsJs);
        self::assertStringContainsString('openNotes', $toolsJs);
        self::assertStringContainsString('openIntercept', $gotakJs);
        self::assertStringContainsString('ow-drawer-close', $view);
        self::assertStringContainsString('button.ow-mate', $css);
        self::assertStringContainsString('ow-drawer-actions', $overwatchJs);
        self::assertStringContainsString('function displayValue', $overwatchJs);
        self::assertStringContainsString('class="ow-mate"', $overwatchJs);
        self::assertStringContainsString('ip.match(/(\\d{1,3}(?:\\.\\d{1,3}){3})/)', $overwatchJs);
    }
}
