<?php

declare(strict_types=1);

namespace Tests\Unit;

use App\Support\DevDispatchCatalog;
use PHPUnit\Framework\TestCase;

final class DevDispatchCatalogTest extends TestCase
{
    public function testCatalogHasSpotrepTechrepAndOneUpdatePerWaveItem(): void
    {
        $all = DevDispatchCatalog::all();
        $byKind = ['spotrep' => 0, 'techrep' => 0, 'update' => 0];
        foreach ($all as $row) {
            $kind = (string) ($row['kind'] ?? '');
            self::assertArrayHasKey($kind, $byKind);
            $byKind[$kind]++;
        }

        self::assertSame(3, $byKind['spotrep']);
        self::assertSame(3, $byKind['techrep']);
        self::assertSame(198, $byKind['update']);
        self::assertCount(204, $all);
    }

    public function testFeaturedIsLatestSpotrep(): void
    {
        $featured = DevDispatchCatalog::featured();
        self::assertNotNull($featured);
        self::assertSame('spotrep', $featured['kind']);
        self::assertSame('00003', $featured['number_pad']);
        self::assertTrue($featured['featured']);
        self::assertSame('Athena Operations', $featured['reporter']);
        self::assertSame('on September 1, 2026', $featured['reported_on']);
        self::assertStringContainsString('nouveautes/spotrep/00003', (string) $featured['href']);
    }

    public function testFindResolvesPaddedAndRawNumbers(): void
    {
        $a = DevDispatchCatalog::find('spotrep', '2');
        $b = DevDispatchCatalog::find('SPOTREP', '00002');
        self::assertNotNull($a);
        self::assertNotNull($b);
        self::assertSame($a['id'], $b['id']);

        $update = DevDispatchCatalog::find('update', '198');
        self::assertNotNull($update);
        self::assertSame('00198', $update['number_pad']);
        $hub = DevDispatchCatalog::find('update', '225');
        self::assertNotNull($hub);
        self::assertSame('00225', $hub['number_pad']);
        self::assertStringContainsString('hub', strtolower((string) $hub['title']));
        $pause = DevDispatchCatalog::find('update', '227');
        self::assertNotNull($pause);
        self::assertSame('00227', $pause['number_pad']);
        self::assertStringContainsString('affichage', strtolower((string) $pause['title']));
        $verify = DevDispatchCatalog::find('update', '228');
        self::assertNotNull($verify);
        self::assertSame('00228', $verify['number_pad']);
        self::assertStringContainsString('relev', strtolower((string) $verify['title']));
        $toolbar = DevDispatchCatalog::find('update', '229');
        self::assertNotNull($toolbar);
        self::assertSame('00229', $toolbar['number_pad']);
        self::assertStringContainsString('barre', strtolower((string) $toolbar['title']));
        $coverage = DevDispatchCatalog::find('update', '230');
        self::assertNotNull($coverage);
        self::assertSame('00230', $coverage['number_pad']);
        self::assertStringContainsString('affichage', strtolower((string) $coverage['title']));
        $modules = DevDispatchCatalog::find('update', '231');
        self::assertNotNull($modules);
        self::assertSame('00231', $modules['number_pad']);
        self::assertStringContainsString('modules carte', strtolower((string) $modules['title']));
        $roster = DevDispatchCatalog::find('update', '232');
        self::assertNotNull($roster);
        self::assertSame('00232', $roster['number_pad']);
        self::assertStringContainsString('terminaux', strtolower((string) $roster['title']));
        $reports = DevDispatchCatalog::find('update', '233');
        self::assertNotNull($reports);
        self::assertSame('00233', $reports['number_pad']);
        self::assertStringContainsString('signalement', strtolower((string) $reports['title']));
        $deferred = DevDispatchCatalog::find('update', '234');
        self::assertNotNull($deferred);
        self::assertSame('00234', $deferred['number_pad']);
        self::assertStringContainsString('diff', strtolower((string) $deferred['title']));
        $lostLink = DevDispatchCatalog::find('update', '235');
        self::assertNotNull($lostLink);
        self::assertSame('00235', $lostLink['number_pad']);
        self::assertStringContainsString('liaison perdue', strtolower((string) $lostLink['title']));
        $cascade = DevDispatchCatalog::find('update', '236');
        self::assertNotNull($cascade);
        self::assertSame('00236', $cascade['number_pad']);
        self::assertStringContainsString('carte', strtolower((string) $cascade['title']));
        $sceneCount = DevDispatchCatalog::find('update', '237');
        self::assertNotNull($sceneCount);
        self::assertSame('00237', $sceneCount['number_pad']);
        self::assertStringContainsString('bâtiment', strtolower((string) $sceneCount['title']));
        $dispatchSheet = DevDispatchCatalog::find('update', '238');
        self::assertNotNull($dispatchSheet);
        self::assertSame('00238', $dispatchSheet['number_pad']);
        self::assertStringContainsString('fiche de mise à jour', strtolower((string) $dispatchSheet['title']));
        $toolbarCss = DevDispatchCatalog::find('update', '243');
        self::assertNotNull($toolbarCss);
        self::assertSame('00243', $toolbarCss['number_pad']);
        self::assertStringContainsString('barre', strtolower((string) $toolbarCss['title']));
        $relief3d = DevDispatchCatalog::find('update', '239');
        self::assertNotNull($relief3d);
        self::assertSame('00239', $relief3d['number_pad']);
        self::assertStringContainsString('relief', strtolower((string) $relief3d['title']));
        $kimmirut = DevDispatchCatalog::find('update', '240');
        self::assertNotNull($kimmirut);
        self::assertSame('00240', $kimmirut['number_pad']);
        self::assertStringContainsString('kimmirut', strtolower((string) $kimmirut['title']));
        $lossCross = DevDispatchCatalog::find('update', '241');
        self::assertNotNull($lossCross);
        self::assertSame('00241', $lossCross['number_pad']);
        self::assertStringContainsString('croix de perte de liaison', strtolower((string) $lossCross['title']));
        $missionsPortal = DevDispatchCatalog::find('update', '244');
        self::assertNotNull($missionsPortal);
        self::assertSame('00244', $missionsPortal['number_pad']);
        self::assertStringContainsString('portail missions', strtolower((string) $missionsPortal['title']));
        $errorPolish = DevDispatchCatalog::find('update', '245');
        self::assertNotNull($errorPolish);
        self::assertSame('00245', $errorPolish['number_pad']);
        self::assertStringContainsString('erreur', strtolower((string) $errorPolish['title']));
        $effectifsHints = DevDispatchCatalog::find('update', '246');
        self::assertNotNull($effectifsHints);
        self::assertSame('00246', $effectifsHints['number_pad']);
        self::assertStringContainsString('effectifs', strtolower((string) $effectifsHints['title']));
        $reliefVisible = DevDispatchCatalog::find('update', '247');
        self::assertNotNull($reliefVisible);
        self::assertSame('00247', $reliefVisible['number_pad']);
        self::assertStringContainsString('relief', strtolower((string) $reliefVisible['title']));
        $vehiclesBanner = DevDispatchCatalog::find('update', '248');
        self::assertNotNull($vehiclesBanner);
        self::assertSame('00248', $vehiclesBanner['number_pad']);
        self::assertStringContainsString('engin', strtolower((string) $vehiclesBanner['title']));
        $zeusIcons = DevDispatchCatalog::find('update', '249');
        self::assertNotNull($zeusIcons);
        self::assertSame('00249', $zeusIcons['number_pad']);
        self::assertStringContainsString('symbole', strtolower((string) $zeusIcons['title']));
        $gpsZones = DevDispatchCatalog::find('update', '250');
        self::assertNotNull($gpsZones);
        self::assertSame('00250', $gpsZones['number_pad']);
        self::assertStringContainsString('itinéraire', strtolower((string) $gpsZones['title']));
        $profileGaps = DevDispatchCatalog::find('update', '251');
        self::assertNotNull($profileGaps);
        self::assertSame('00251', $profileGaps['number_pad']);
        self::assertStringContainsString('profils à compléter', strtolower((string) $profileGaps['title']));
        $seniorityRapid = DevDispatchCatalog::find('update', '252');
        self::assertNotNull($seniorityRapid);
        self::assertSame('00252', $seniorityRapid['number_pad']);
        self::assertStringContainsString('ancienneté', strtolower((string) $seniorityRapid['title']));
        $alertPreview = DevDispatchCatalog::find('update', '253');
        self::assertNotNull($alertPreview);
        self::assertSame('00253', $alertPreview['number_pad']);
        self::assertStringContainsString('aperçu', strtolower((string) $alertPreview['title']));
        $boSearch = DevDispatchCatalog::find('update', '254');
        self::assertNotNull($boSearch);
        self::assertSame('00254', $boSearch['number_pad']);
        self::assertStringContainsString('recherche', strtolower((string) $boSearch['title']));
        $realTenure = DevDispatchCatalog::find('update', '255');
        self::assertNotNull($realTenure);
        self::assertSame('00255', $realTenure['number_pad']);
        self::assertStringContainsString('ancienneté', strtolower((string) $realTenure['title']));
        $memberHub = DevDispatchCatalog::find('update', '256');
        self::assertNotNull($memberHub);
        self::assertSame('00256', $memberHub['number_pad']);
        self::assertStringContainsString('fiche membre', strtolower((string) $memberHub['title']));
        $catalogAdmin = DevDispatchCatalog::find('update', '260');
        self::assertNotNull($catalogAdmin);
        self::assertSame('00260', $catalogAdmin['number_pad']);
        self::assertStringContainsString('administrer', strtolower((string) $catalogAdmin['title']));
        $platformAdmin = DevDispatchCatalog::find('update', '261');
        self::assertNotNull($platformAdmin);
        self::assertSame('00261', $platformAdmin['number_pad']);
        self::assertStringContainsString('administration du site', strtolower((string) $platformAdmin['title']));
        $overwatchUi = DevDispatchCatalog::find('update', '262');
        self::assertNotNull($overwatchUi);
        self::assertSame('00262', $overwatchUi['number_pad']);
        self::assertStringContainsString('zeus', strtolower((string) $overwatchUi['title']));
        $athenaGate = DevDispatchCatalog::find('update', '263');
        self::assertNotNull($athenaGate);
        self::assertSame('00263', $athenaGate['number_pad']);
        self::assertStringContainsString('athena', strtolower((string) $athenaGate['title']));
        $equipmentHub = DevDispatchCatalog::find('update', '265');
        self::assertNotNull($equipmentHub);
        self::assertSame('00265', $equipmentHub['number_pad']);
        self::assertStringContainsString('tenues', strtolower((string) $equipmentHub['title']));
        $effectifsGrade = DevDispatchCatalog::find('update', '266');
        self::assertNotNull($effectifsGrade);
        self::assertSame('00266', $effectifsGrade['number_pad']);
        self::assertStringContainsString('grade', strtolower((string) $effectifsGrade['title']));
        $dupUi = DevDispatchCatalog::find('update', '267');
        self::assertNotNull($dupUi);
        self::assertSame('00267', $dupUi['number_pad']);
        self::assertStringContainsString('fiches jumelles', strtolower((string) $dupUi['title']));
        $hrVault = DevDispatchCatalog::find('update', '268');
        self::assertNotNull($hrVault);
        self::assertSame('00268', $hrVault['number_pad']);
        self::assertStringContainsString('pièces rh', strtolower((string) $hrVault['title']));
        $charterUi = DevDispatchCatalog::find('update', '269');
        self::assertNotNull($charterUi);
        self::assertSame('00269', $charterUi['number_pad']);
        self::assertStringContainsString('charte', strtolower((string) $charterUi['title']));
        $rolesAir = DevDispatchCatalog::find('update', '270');
        self::assertNotNull($rolesAir);
        self::assertSame('00270', $rolesAir['number_pad']);
        self::assertStringContainsString('rôles', strtolower((string) $rolesAir['title']));
        $gpsRoute = DevDispatchCatalog::find('update', '272');
        self::assertNotNull($gpsRoute);
        self::assertSame('00272', $gpsRoute['number_pad']);
        self::assertStringContainsString('itinéraire', strtolower((string) $gpsRoute['title']));
        $terminalPack = DevDispatchCatalog::find('update', '271');
        self::assertNotNull($terminalPack);
        self::assertSame('00271', $terminalPack['number_pad']);
        self::assertStringContainsString('pack', strtolower((string) $terminalPack['title']));
        $dupDesk = DevDispatchCatalog::find('update', '273');
        self::assertNotNull($dupDesk);
        self::assertSame('00273', $dupDesk['number_pad']);
        self::assertStringContainsString('fiches jumelles', strtolower((string) $dupDesk['title']));
        $communityIcons = DevDispatchCatalog::find('update', '274');
        self::assertNotNull($communityIcons);
        self::assertSame('00274', $communityIcons['number_pad']);
        self::assertStringContainsString('icônes', strtolower((string) $communityIcons['title']));
        $icemanHud = DevDispatchCatalog::find('update', '275');
        self::assertNotNull($icemanHud);
        self::assertSame('00275', $icemanHud['number_pad']);
        self::assertStringContainsString('tablette atak', strtolower((string) $icemanHud['title']));
        $publicDossier = DevDispatchCatalog::find('update', '277');
        self::assertNotNull($publicDossier);
        self::assertSame('00277', $publicDossier['number_pad']);
        self::assertStringContainsString('dossier public', strtolower((string) $publicDossier['title']));
        $corrRh = DevDispatchCatalog::find('update', '278');
        self::assertNotNull($corrRh);
        self::assertSame('00278', $corrRh['number_pad']);
        self::assertStringContainsString('corriger sa fiche', strtolower((string) $corrRh['title']));
        $dashHub = DevDispatchCatalog::find('update', '279');
        self::assertNotNull($dashHub);
        self::assertSame('00279', $dashHub['number_pad']);
        self::assertStringContainsString('tableau de bord', strtolower((string) $dashHub['title']));
        $mapChips = DevDispatchCatalog::find('update', '280');
        self::assertNotNull($mapChips);
        self::assertSame('00280', $mapChips['number_pad']);
        self::assertStringContainsString('rapports', strtolower((string) $mapChips['title']));
        $toolbarStay = DevDispatchCatalog::find('update', '276');
        self::assertNotNull($toolbarStay);
        self::assertSame('00276', $toolbarStay['number_pad']);
        self::assertStringContainsString('barre d’outils', strtolower((string) $toolbarStay['title']));
        $idStrip = DevDispatchCatalog::find('update', '281');
        self::assertNotNull($idStrip);
        self::assertSame('00281', $idStrip['number_pad']);
        self::assertStringContainsString('identité', strtolower((string) $idStrip['title']));
        $updateModal = DevDispatchCatalog::find('update', '282');
        self::assertNotNull($updateModal);
        self::assertSame('00282', $updateModal['number_pad']);
        self::assertStringContainsString('actualiser', strtolower((string) $updateModal['title']));
        $packVersions = DevDispatchCatalog::find('update', '283');
        self::assertNotNull($packVersions);
        self::assertSame('00283', $packVersions['number_pad']);
        self::assertStringContainsString('pack actuel', strtolower((string) $packVersions['title']));
        $qrReadable = DevDispatchCatalog::find('update', '284');
        self::assertNotNull($qrReadable);
        self::assertSame('00284', $qrReadable['number_pad']);
        self::assertStringContainsString('qr', strtolower((string) $qrReadable['title']));
        $escBanner = DevDispatchCatalog::find('update', '285');
        self::assertNotNull($escBanner);
        self::assertSame('00285', $escBanner['number_pad']);
        self::assertStringContainsString('bandeau', strtolower((string) $escBanner['title']));
        $arsenalDrawer = DevDispatchCatalog::find('update', '286');
        self::assertNotNull($arsenalDrawer);
        self::assertSame('00286', $arsenalDrawer['number_pad']);
        self::assertStringContainsString('tenues', strtolower((string) $arsenalDrawer['title']));
        $reliefSplit = DevDispatchCatalog::find('update', '287');
        self::assertNotNull($reliefSplit);
        self::assertSame('00287', $reliefSplit['number_pad']);
        self::assertStringContainsString('relief', strtolower((string) $reliefSplit['title']));
        $wardrobeQueue = DevDispatchCatalog::find('update', '288');
        self::assertNotNull($wardrobeQueue);
        self::assertSame('00288', $wardrobeQueue['number_pad']);
        self::assertStringContainsString('tenues hors liaison', strtolower((string) $wardrobeQueue['title']));
        $athenaHome = DevDispatchCatalog::find('update', '289');
        self::assertNotNull($athenaHome);
        self::assertSame('00289', $athenaHome['number_pad']);
        self::assertStringContainsString('quatre vues', strtolower((string) $athenaHome['title']));
        $hudLabels = DevDispatchCatalog::find('update', '290');
        self::assertNotNull($hudLabels);
        self::assertSame('00290', $hudLabels['number_pad']);
        self::assertStringContainsString('vocabulaire', strtolower((string) $hudLabels['title']));
        $reportsUi = DevDispatchCatalog::find('update', '291');
        self::assertNotNull($reportsUi);
        self::assertSame('00291', $reportsUi['number_pad']);
        self::assertStringContainsString('comptes-rendus', strtolower((string) $reportsUi['title']));
        $integration = DevDispatchCatalog::find('update', '292');
        self::assertNotNull($integration);
        self::assertSame('00292', $integration['number_pad']);
        self::assertStringContainsString('parcours d’arrivée', strtolower((string) $integration['title']));
        $mapInventory = DevDispatchCatalog::find('update', '293');
        self::assertNotNull($mapInventory);
        self::assertSame('00293', $mapInventory['number_pad']);
        self::assertStringContainsString('affichage', strtolower((string) $mapInventory['title']));
        $rhParcours = DevDispatchCatalog::find('update', '294');
        self::assertNotNull($rhParcours);
        self::assertSame('00294', $rhParcours['number_pad']);
        self::assertStringContainsString('dossier rh', strtolower((string) $rhParcours['title']));
        $fileGateSpace = DevDispatchCatalog::find('update', '295');
        self::assertNotNull($fileGateSpace);
        self::assertSame('00295', $fileGateSpace['number_pad']);
        self::assertStringContainsString('dossier', strtolower((string) $fileGateSpace['title']));
        $passwordNoSteam = DevDispatchCatalog::find('update', '296');
        self::assertNotNull($passwordNoSteam);
        self::assertSame('00296', $passwordNoSteam['number_pad']);
        self::assertStringContainsString('steam', strtolower((string) $passwordNoSteam['title']));
        $posJournal = DevDispatchCatalog::find('update', '297');
        self::assertNotNull($posJournal);
        self::assertSame('00297', $posJournal['number_pad']);
        self::assertStringContainsString('positions', strtolower((string) $posJournal['title']));
        $rhOneStep = DevDispatchCatalog::find('update', '298');
        self::assertNotNull($rhOneStep);
        self::assertSame('00298', $rhOneStep['number_pad']);
        self::assertStringContainsString('démarche rh', strtolower((string) $rhOneStep['title']));
        $selectContrast = DevDispatchCatalog::find('update', '299');
        self::assertNotNull($selectContrast);
        self::assertSame('00299', $selectContrast['number_pad']);
        self::assertStringContainsString('listes', strtolower((string) $selectContrast['title']));
        $overwatchReady = DevDispatchCatalog::find('update', '300');
        self::assertNotNull($overwatchReady);
        self::assertSame('00300', $overwatchReady['number_pad']);
        self::assertStringContainsString('identité', strtolower((string) $overwatchReady['title']));
        $accessGap = DevDispatchCatalog::find('update', '301');
        self::assertNotNull($accessGap);
        self::assertSame('00301', $accessGap['number_pad']);
        self::assertStringContainsString('accès', strtolower((string) $accessGap['title']));
        $armaChatSilent = DevDispatchCatalog::find('update', '302');
        self::assertNotNull($armaChatSilent);
        self::assertSame('00302', $armaChatSilent['number_pad']);
        self::assertStringContainsString('chat du jeu', strtolower((string) $armaChatSilent['title']));
        $phoneCs = DevDispatchCatalog::find('update', '303');
        self::assertNotNull($phoneCs);
        self::assertSame('00303', $phoneCs['number_pad']);
        self::assertStringContainsString('indicatif', strtolower((string) $phoneCs['title']));
        $modelesUi = DevDispatchCatalog::find('update', '305');
        self::assertNotNull($modelesUi);
        self::assertSame('00305', $modelesUi['number_pad']);
        self::assertStringContainsString('modèles', strtolower((string) $modelesUi['title']));
        $playerLook = DevDispatchCatalog::find('update', '304');
        self::assertNotNull($playerLook);
        self::assertSame('00304', $playerLook['number_pad']);
        self::assertStringContainsString('apparence', strtolower((string) $playerLook['title']));
        $opsLight = DevDispatchCatalog::find('update', '306');
        self::assertNotNull($opsLight);
        self::assertSame('00306', $opsLight['number_pad']);
        self::assertStringContainsString('espaces opérationnels', strtolower((string) $opsLight['title']));
        $athenaJournal = DevDispatchCatalog::find('update', '307');
        self::assertNotNull($athenaJournal);
        self::assertSame('00307', $athenaJournal['number_pad']);
        self::assertStringContainsString('journal athena', strtolower((string) $athenaJournal['title']));
        $zeusPin = DevDispatchCatalog::find('update', '308');
        self::assertNotNull($zeusPin);
        self::assertSame('00308', $zeusPin['number_pad']);
        self::assertStringContainsString('point carte', strtolower((string) $zeusPin['title']));
        $overwatch150 = DevDispatchCatalog::find('update', '318');
        self::assertNotNull($overwatch150);
        self::assertSame('00318', $overwatch150['number_pad']);
        self::assertStringContainsString('identité', strtolower((string) $overwatch150['title']));
        $restoreSansSteam = DevDispatchCatalog::find('update', '321');
        self::assertNotNull($restoreSansSteam);
        self::assertSame('00321', $restoreSansSteam['number_pad']);
        self::assertStringContainsString('session', strtolower((string) $restoreSansSteam['title']));
        $sharedRelief = DevDispatchCatalog::find('update', '322');
        self::assertNotNull($sharedRelief);
        self::assertSame('00322', $sharedRelief['number_pad']);
        self::assertStringContainsString('ombrage', strtolower((string) $sharedRelief['title']));
        $steamLinkLogin = DevDispatchCatalog::find('update', '325');
        self::assertNotNull($steamLinkLogin);
        self::assertSame('00325', $steamLinkLogin['number_pad']);
        self::assertStringContainsString('steam', strtolower((string) $steamLinkLogin['title']));
        $steamDash = DevDispatchCatalog::find('update', '326');
        self::assertNotNull($steamDash);
        self::assertSame('00326', $steamDash['number_pad']);
        self::assertStringContainsString('tableau de bord', strtolower((string) $steamDash['title']));
        $mapIconsStay = DevDispatchCatalog::find('update', '327');
        self::assertNotNull($mapIconsStay);
        self::assertSame('00327', $mapIconsStay['number_pad']);
        self::assertStringContainsString('liaison', strtolower((string) $mapIconsStay['title']));
        $effectifsVisible = DevDispatchCatalog::find('update', '328');
        self::assertNotNull($effectifsVisible);
        self::assertSame('00328', $effectifsVisible['number_pad']);
        self::assertStringContainsString('effectifs', strtolower((string) $effectifsVisible['title']));
        $rhCardsOpen = DevDispatchCatalog::find('update', '329');
        self::assertNotNull($rhCardsOpen);
        self::assertSame('00329', $rhCardsOpen['number_pad']);
        self::assertStringContainsString('absence', strtolower((string) $rhCardsOpen['title']));
        $aceAthena = DevDispatchCatalog::find('update', '330');
        self::assertNotNull($aceAthena);
        self::assertSame('00330', $aceAthena['number_pad']);
        self::assertStringContainsString('athena', strtolower((string) $aceAthena['title']));
        $miInstall = DevDispatchCatalog::find('update', '331');
        self::assertNotNull($miInstall);
        self::assertSame('00331', $miInstall['number_pad']);
        self::assertStringContainsString('intégration', strtolower((string) $miInstall['title']));
        $photoConnect = DevDispatchCatalog::find('update', '332');
        self::assertNotNull($photoConnect);
        self::assertSame('00332', $photoConnect['number_pad']);
        self::assertStringContainsString('photo', strtolower((string) $photoConnect['title']));
        $wardrobeSend = DevDispatchCatalog::find('update', '333');
        self::assertNotNull($wardrobeSend);
        self::assertSame('00333', $wardrobeSend['number_pad']);
        self::assertStringContainsString('tenue', strtolower((string) $wardrobeSend['title']));
        $wardrobeUi = DevDispatchCatalog::find('update', '334');
        self::assertNotNull($wardrobeUi);
        self::assertSame('00334', $wardrobeUi['number_pad']);
        self::assertStringContainsString('arsenal', strtolower((string) $wardrobeUi['title']));
        $coverUpload = DevDispatchCatalog::find('update', '335');
        self::assertNotNull($coverUpload);
        self::assertSame('00335', $coverUpload['number_pad']);
        self::assertStringContainsString('photo', strtolower((string) $coverUpload['title']));
        $tenueItems = DevDispatchCatalog::find('update', '336');
        self::assertNotNull($tenueItems);
        self::assertSame('00336', $tenueItems['number_pad']);
        self::assertStringContainsString('équipement', strtolower((string) $tenueItems['title']));
        $atakWindows = DevDispatchCatalog::find('update', '337');
        self::assertNotNull($atakWindows);
        self::assertSame('00337', $atakWindows['number_pad']);
        self::assertStringContainsString('téléphone', strtolower((string) $atakWindows['title']));
        $map2d = DevDispatchCatalog::find('update', '338');
        self::assertNotNull($map2d);
        self::assertSame('00338', $map2d['number_pad']);
        self::assertStringContainsString('plat', strtolower((string) $map2d['title']));
        $quickPic = DevDispatchCatalog::find('update', '339');
        self::assertNotNull($quickPic);
        self::assertSame('00339', $quickPic['number_pad']);
        self::assertStringContainsString('caméra', strtolower((string) $quickPic['title']));
        $frsPhone = DevDispatchCatalog::find('update', '340');
        self::assertNotNull($frsPhone);
        self::assertSame('00340', $frsPhone['number_pad']);
        self::assertStringContainsString('fiche', strtolower((string) $frsPhone['title']));
        $soundsRelief = DevDispatchCatalog::find('update', '341');
        self::assertNotNull($soundsRelief);
        self::assertSame('00341', $soundsRelief['number_pad']);
        self::assertStringContainsString('relief', strtolower((string) $soundsRelief['title']));
        $bftGroup = DevDispatchCatalog::find('update', '342');
        self::assertNotNull($bftGroup);
        self::assertSame('00342', $bftGroup['number_pad']);
        self::assertStringContainsString('effectif', strtolower((string) $bftGroup['title']));
        $loginTile = DevDispatchCatalog::find('update', '343');
        self::assertNotNull($loginTile);
        self::assertSame('00343', $loginTile['number_pad']);
        self::assertStringContainsString('connexion', strtolower((string) $loginTile['title']));
        $aceLogin = DevDispatchCatalog::find('update', '344');
        self::assertNotNull($aceLogin);
        self::assertSame('00344', $aceLogin['number_pad']);
        self::assertStringContainsString('connexion', strtolower((string) $aceLogin['title']));
        $aceAtakMenus = DevDispatchCatalog::find('update', '345');
        self::assertNotNull($aceAtakMenus);
        self::assertSame('00345', $aceAtakMenus['number_pad']);
        self::assertStringContainsString('ace', strtolower((string) $aceAtakMenus['title']));
        $mobileChat = DevDispatchCatalog::find('update', '346');
        self::assertNotNull($mobileChat);
        self::assertSame('00346', $mobileChat['number_pad']);
        self::assertStringContainsString('tchat', strtolower((string) $mobileChat['title']));
        $radioAlign = DevDispatchCatalog::find('update', '347');
        self::assertNotNull($radioAlign);
        self::assertSame('00347', $radioAlign['number_pad']);
        self::assertStringContainsString('journal radio', strtolower((string) $radioAlign['title']));
        $docsAuthored = DevDispatchCatalog::find('update', '348');
        self::assertNotNull($docsAuthored);
        self::assertSame('00348', $docsAuthored['number_pad']);
        self::assertStringContainsString('manuels', strtolower((string) $docsAuthored['title']));
        $pdfLocal = DevDispatchCatalog::find('update', '349');
        self::assertNotNull($pdfLocal);
        self::assertSame('00349', $pdfLocal['number_pad']);
        self::assertStringContainsString('aperçu pdf', strtolower((string) $pdfLocal['title']));
        $courrierHeader = DevDispatchCatalog::find('update', '350');
        self::assertNotNull($courrierHeader);
        self::assertSame('00350', $courrierHeader['number_pad']);
        self::assertStringContainsString('en-tête', strtolower((string) $courrierHeader['title']));
        $courrierSig = DevDispatchCatalog::find('update', '351');
        self::assertNotNull($courrierSig);
        self::assertSame('00351', $courrierSig['number_pad']);
        self::assertStringContainsString('signature', strtolower((string) $courrierSig['title']));
        $dossierVide = DevDispatchCatalog::find('update', '352');
        self::assertNotNull($dossierVide);
        self::assertSame('00352', $dossierVide['number_pad']);
        self::assertStringContainsString('choix de vue', strtolower((string) $dossierVide['title']));
        $arsenalGroups = DevDispatchCatalog::find('update', '353');
        self::assertNotNull($arsenalGroups);
        self::assertSame('00353', $arsenalGroups['number_pad']);
        self::assertStringContainsString('collection', strtolower((string) $arsenalGroups['title']));
        $photoFiche = DevDispatchCatalog::find('update', '354');
        self::assertNotNull($photoFiche);
        self::assertSame('00354', $photoFiche['number_pad']);
        self::assertStringContainsString('photos', strtolower((string) $photoFiche['title']));
        self::assertStringContainsString('fiche', strtolower((string) $photoFiche['title']));
        $bftCs = DevDispatchCatalog::find('update', '355');
        self::assertNotNull($bftCs);
        self::assertSame('00355', $bftCs['number_pad']);
        self::assertStringContainsString('indicatif', strtolower((string) $bftCs['title']));
        $steamBoot = DevDispatchCatalog::find('update', '356');
        self::assertNotNull($steamBoot);
        self::assertSame('00356', $steamBoot['number_pad']);
        self::assertStringContainsString('steam', strtolower((string) $steamBoot['title']));
        $panicPoste = DevDispatchCatalog::find('update', '357');
        self::assertNotNull($panicPoste);
        self::assertSame('00357', $panicPoste['number_pad']);
        self::assertStringContainsString('urgence', strtolower((string) $panicPoste['title']));
        $emailPrivacy = DevDispatchCatalog::find('update', '358');
        self::assertNotNull($emailPrivacy);
        self::assertSame('00358', $emailPrivacy['number_pad']);
        self::assertStringContainsString('e-mail', strtolower((string) $emailPrivacy['title']));
        $athenaJournal = DevDispatchCatalog::find('update', '359');
        self::assertNotNull($athenaJournal);
        self::assertSame('00359', $athenaJournal['number_pad']);
        self::assertStringContainsString('athena', strtolower((string) $athenaJournal['title']));
        self::assertStringContainsString('journal', strtolower((string) $athenaJournal['title']));
        $mapToolsHud = DevDispatchCatalog::find('update', '360');
        self::assertNotNull($mapToolsHud);
        self::assertSame('00360', $mapToolsHud['number_pad']);
        self::assertStringContainsString('boussole', strtolower((string) $mapToolsHud['title']));
        $photoFolder = DevDispatchCatalog::find('update', '361');
        self::assertNotNull($photoFolder);
        self::assertSame('00361', $photoFolder['number_pad']);
        self::assertStringContainsString('photos', strtolower((string) $photoFolder['title']));
        $roleLibre = DevDispatchCatalog::find('update', '362');
        self::assertNotNull($roleLibre);
        self::assertSame('00362', $roleLibre['number_pad']);
        self::assertStringContainsString('rôle', strtolower((string) $roleLibre['title']));
        $acctBanner = DevDispatchCatalog::find('update', '363');
        self::assertNotNull($acctBanner);
        self::assertSame('00363', $acctBanner['number_pad']);
        self::assertStringContainsString('compte', strtolower((string) $acctBanner['title']));
        $playersMap = DevDispatchCatalog::find('update', '364');
        self::assertNotNull($playersMap);
        self::assertSame('00364', $playersMap['number_pad']);
        self::assertStringContainsString('opérateurs', strtolower((string) $playersMap['title']));
        $chargeAtak = DevDispatchCatalog::find('update', '365');
        self::assertNotNull($chargeAtak);
        self::assertSame('00365', $chargeAtak['number_pad']);
        self::assertStringContainsString('charge', strtolower((string) $chargeAtak['title']));
        $termCert = DevDispatchCatalog::find('update', '366');
        self::assertNotNull($termCert);
        self::assertSame('00366', $termCert['number_pad']);
        self::assertStringContainsString('certificat', strtolower((string) $termCert['title']));
        $ghosts = DevDispatchCatalog::find('update', '367');
        self::assertNotNull($ghosts);
        self::assertSame('00367', $ghosts['number_pad']);
        self::assertStringContainsString('liaison', strtolower((string) $ghosts['title']));
        $c2Chrome = DevDispatchCatalog::find('update', '368');
        self::assertNotNull($c2Chrome);
        self::assertSame('00368', $c2Chrome['number_pad']);
        self::assertStringContainsString('outils', strtolower((string) $c2Chrome['title']));
        $dossierName = DevDispatchCatalog::find('update', '369');
        self::assertNotNull($dossierName);
        self::assertSame('00369', $dossierName['number_pad']);
        self::assertStringContainsString('prénom', strtolower((string) $dossierName['title']));
        $functionKits = DevDispatchCatalog::find('update', '370');
        self::assertNotNull($functionKits);
        self::assertSame('00370', $functionKits['number_pad']);
        self::assertStringContainsString('accès', strtolower((string) $functionKits['title']));
        $coverStorage = DevDispatchCatalog::find('update', '371');
        self::assertNotNull($coverStorage);
        self::assertSame('00371', $coverStorage['number_pad']);
        self::assertStringContainsString('photos', strtolower((string) $coverStorage['title']));
        $kitShowcase = DevDispatchCatalog::find('update', '372');
        self::assertNotNull($kitShowcase);
        self::assertSame('00372', $kitShowcase['number_pad']);
        self::assertStringContainsString('tenues', strtolower((string) $kitShowcase['title']));
        $kitRbac = DevDispatchCatalog::find('update', '373');
        self::assertNotNull($kitRbac);
        self::assertSame('00373', $kitRbac['number_pad']);
        self::assertStringContainsString('communauté', strtolower((string) $kitRbac['title']));
        $availDash = DevDispatchCatalog::find('update', '374');
        self::assertNotNull($availDash);
        self::assertSame('00374', $availDash['number_pad']);
        self::assertStringContainsString('disponibilité', strtolower((string) $availDash['title']));
        $kitsPick = DevDispatchCatalog::find('update', '375');
        self::assertNotNull($kitsPick);
        self::assertSame('00375', $kitsPick['number_pad']);
        self::assertStringContainsString('kits', strtolower((string) $kitsPick['title']));
        $dashboardLogin = DevDispatchCatalog::find('update', '376');
        self::assertNotNull($dashboardLogin);
        self::assertSame('00376', $dashboardLogin['number_pad']);
        self::assertStringContainsString('tableau de bord', strtolower((string) $dashboardLogin['title']));
        $upgradeResume = DevDispatchCatalog::find('update', '377');
        self::assertNotNull($upgradeResume);
        self::assertSame('00377', $upgradeResume['number_pad']);
        self::assertStringContainsString('mise à jour du portail', strtolower((string) $upgradeResume['title']));
        $docEditFile = DevDispatchCatalog::find('update', '381');
        self::assertNotNull($docEditFile);
        self::assertSame('00381', $docEditFile['number_pad']);
        self::assertStringContainsString('fichier', strtolower((string) $docEditFile['title']));
        $dossiers = DevDispatchCatalog::find('update', '382');
        self::assertNotNull($dossiers);
        self::assertSame('00382', $dossiers['number_pad']);
        self::assertStringContainsString('dossiers', strtolower((string) $dossiers['title']));
        $forgotPwd = DevDispatchCatalog::find('update', '383');
        self::assertNotNull($forgotPwd);
        self::assertSame('00383', $forgotPwd['number_pad']);
        self::assertStringContainsString('mot de passe oublié', strtolower((string) $forgotPwd['title']));
        $publicTenants = DevDispatchCatalog::find('update', '384');
        self::assertNotNull($publicTenants);
        self::assertSame('00384', $publicTenants['number_pad']);
        self::assertStringContainsString('fiches publiques', strtolower((string) $publicTenants['title']));
        $dashBands = DevDispatchCatalog::find('update', '386');
        self::assertNotNull($dashBands);
        self::assertSame('00386', $dashBands['number_pad']);
        self::assertStringContainsString('tableau de bord', strtolower((string) $dashBands['title']));
        $slugEverywhere = DevDispatchCatalog::find('update', '385');
        self::assertNotNull($slugEverywhere);
        self::assertSame('00385', $slugEverywhere['number_pad']);
        self::assertStringContainsString('formations', strtolower((string) $slugEverywhere['title']));
        $ficheCaptures = DevDispatchCatalog::find('update', '387');
        self::assertNotNull($ficheCaptures);
        self::assertSame('00387', $ficheCaptures['number_pad']);
        self::assertStringContainsString('fiche', strtolower((string) $ficheCaptures['title']));
        $welcomePhotos = DevDispatchCatalog::find('update', '388');
        self::assertNotNull($welcomePhotos);
        self::assertSame('00388', $welcomePhotos['number_pad']);
        self::assertStringContainsString('bienvenue', strtolower((string) $welcomePhotos['title']));
        $dossierTenure = DevDispatchCatalog::find('update', '389');
        self::assertNotNull($dossierTenure);
        self::assertSame('00389', $dossierTenure['number_pad']);
        self::assertStringContainsString('ancienneté', strtolower((string) $dossierTenure['title']));
        $noOrgDossier = DevDispatchCatalog::find('update', '391');
        self::assertNotNull($noOrgDossier);
        self::assertSame('00391', $noOrgDossier['number_pad']);
        self::assertStringContainsString('communauté', strtolower((string) $noOrgDossier['title']));
        $dutyPos = DevDispatchCatalog::find('update', '390');
        self::assertNotNull($dutyPos);
        self::assertSame('00390', $dutyPos['number_pad']);
        self::assertStringContainsString('formation', strtolower((string) $dutyPos['title']));
        $idCartouche = DevDispatchCatalog::find('update', '392');
        self::assertNotNull($idCartouche);
        self::assertSame('00392', $idCartouche['number_pad']);
        self::assertStringContainsString('identité', strtolower((string) $idCartouche['title']));
        $dossierEdit = DevDispatchCatalog::find('update', '393');
        self::assertNotNull($dossierEdit);
        self::assertSame('00393', $dossierEdit['number_pad']);
        self::assertStringContainsString('dossier', strtolower((string) $dossierEdit['title']));
        $dashBanner = DevDispatchCatalog::find('update', '394');
        self::assertNotNull($dashBanner);
        self::assertSame('00394', $dashBanner['number_pad']);
        self::assertStringContainsString('bandeau', strtolower((string) $dashBanner['title']));
        self::assertStringContainsString('tableau de bord', strtolower((string) $dashBanner['title']));
        $journalFix = DevDispatchCatalog::find('update', '395');
        self::assertNotNull($journalFix);
        self::assertSame('00395', $journalFix['number_pad']);
        self::assertStringContainsString('journal', strtolower((string) $journalFix['title']));
        $rpMenu = DevDispatchCatalog::find('update', '396');
        self::assertNotNull($rpMenu);
        self::assertSame('00396', $rpMenu['number_pad']);
        self::assertStringContainsString('étape', strtolower((string) $rpMenu['title']));
        $steamReady = DevDispatchCatalog::find('update', '397');
        self::assertNotNull($steamReady);
        self::assertSame('00397', $steamReady['number_pad']);
        self::assertStringContainsString('steam', strtolower((string) $steamReady['title']));
        $mapUi = DevDispatchCatalog::find('update', '398');
        self::assertNotNull($mapUi);
        self::assertSame('00398', $mapUi['number_pad']);
        self::assertStringContainsString('carte', strtolower((string) $mapUi['title']));
        $spot03 = DevDispatchCatalog::find('spotrep', '3');
        self::assertNotNull($spot03);
        self::assertTrue((bool) $spot03['featured']);
        self::assertStringContainsString('tablette', strtolower((string) $spot03['title']));
        $update249 = strtolower(DevDispatchCatalog::publicCorpus());
        self::assertStringContainsString('mot de passe s’affichait en clair', $update249);
        self::assertStringContainsString('inclinaison, amplification du relief', $update249);
        self::assertNull(DevDispatchCatalog::find('spotrep', '999'));
        self::assertNull(DevDispatchCatalog::find('memo', '1'));
    }

    public function testPublicTextsStayHumanReadable(): void
    {
        $corpus = DevDispatchCatalog::publicCorpus();
        foreach ([
            'sqf',
            'endpoint',
            '/api/',
            'json',
            'sql',
            'mariadb',
            'pbo',
            'cfgfunctions',
            'post /',
            'get /',
            'rebuild',
        ] as $banned) {
            self::assertStringNotContainsString($banned, $corpus, $banned);
        }
        self::assertStringContainsString('ombrage', $corpus);
        self::assertStringContainsString('organigramme', $corpus);
        self::assertStringContainsString('points numérotés', $corpus);
    }
}
